(test "Package explorer — A. deep link"
  (setup
    ; A. deep link

    (initial-location "/packages/roc-json")
  )
  (steps
    (expect-current-location "/packages/roc-json")
    (expect-document-title "roc-json - Package Explorer")
    (expect-visible (role heading :name "Package Explorer"))
    (expect-visible (role region :name "Package Explorer"))
    (expect-visible (role region :name "Package detail"))
    (expect-visible (role heading :name "Package detail"))
    (expect-visible (role region :name "Overview"))
    (expect-visible (role region :name "Versions"))
    (expect-visible (role region :name "Version history"))
    (expect-visible (role region :name "Dependencies"))
    (expect-visible (role region :name "Dependency list"))
    (expect-visible (role link :name "Back to search"))
    (expect-absent (role region :name "Package search"))
    (expect-absent (role region :name "Search results"))
    (expect-text (test-id "package-id") "Package: roc-json")
    (expect-text (test-id "panel-summary") "Panels: 0 ready, 3 loading, 0 failed")
    (expect-visible (text "Some panels are still loading."))
    (expect-absent (text "All panels settled."))
    (expect-text (test-id "overview-status") "Overview: loading")
    (expect-text (test-id "overview-empty") "Overview details pending.")
    (expect-text (test-id "versions-status") "Versions: loading")
    (expect-text (test-id "versions-empty") "Version history pending.")
    (expect-text (test-id "deps-status") "Dependencies: loading")
    (expect-text (test-id "deps-empty") "Dependency list pending.")
    ; The search query is a separate source, so a cold deep link also starts the
    ; empty-query search. The context line is the map2 fan-in of route + matches.
    (expect-text (test-id "context") "Context: package roc-json (0 search matches retained)")
    (expect-pending-task "detail" 1)
    (expect-pending-task "versions" 1)
    (expect-pending-task "deps" 1)
    (expect-pending-task "search" 1)
    (expect-canceled-task "detail" 0)
    (expect-canceled-task "versions" 0)
    (expect-canceled-task "deps" 0)
    (expect-cleanup "package detail panels" 0)
  )
)
