(test "Package explorer — G. Back and Forward"
  (setup (manual-effects))
  (steps
    ; Retain search results while navigation changes the visible page.
    (stub-http "initial search" :url "/api/packages/search?q=" :status 200 :body "roc-json|JSON codec for Roc;roc-http|HTTP client for Roc;roc-parser|Parser combinators for Roc")
    (run-effect 1)
    (click (role link :name "Open roc-json"))
    ; Settle the first visit before exercising browser history.
    (stub-http "versions" :url "/api/packages/versions?q=%72%6f%63%2d%6a%73%6f%6e" :status 200 :body "1.2.0|2026-05-02")
    (run-effect 3)
    (stub-http "dependencies" :url "/api/packages/deps?q=%72%6f%63%2d%6a%73%6f%6e" :status 200 :body "roc-parser|0.4.0")
    (run-effect 4)
    (stub-http-reject "overview timeout" :kind timeout :detail "")
    (run-effect 2)

    ; G. Back and Forward

    (history-back)
    (expect-current-location "/")
    (expect-document-title "Package Explorer")
    (expect-visible (role region :name "Package search"))
    (expect-absent (role region :name "Package detail"))
    (expect-text (test-id "search-status") "Search status: 3 packages")
    (expect-text (test-id "context") "Context: search results (3 matches)")
    (expect-cleanup "package detail panels" 1)
    (history-forward)
    (expect-current-location "/packages/roc-json")
    (expect-document-title "roc-json - Package Explorer")
    (expect-visible (role region :name "Package detail"))
    (expect-text (test-id "package-id") "Package: roc-json")
    (expect-text (test-id "panel-summary") "Panels: 0 ready, 3 loading, 0 failed")
    (expect-pending-effects 3)
    ; The overview succeeds this time; every field is derived from one payload.
    (stub-http "detail on return" :url "/api/packages/detail?q=%72%6f%63%2d%6a%73%6f%6e" :status 200 :body "roc-json|JSON codec for Roc|Apache-2.0|18422")
    (run-effect 5)
    (expect-text (test-id "overview-status") "Overview: ready")
    (expect-text (test-id "overview-summary") "Summary: JSON codec for Roc")
    (expect-text (test-id "overview-license") "License: Apache-2.0")
    (expect-text (test-id "overview-downloads") "Downloads: 18422")
    (expect-absent (test-id "overview-empty"))
    (expect-text (test-id "panel-summary") "Panels: 1 ready, 2 loading, 0 failed")
    ; A package with nothing published and nothing depended on: both empty branches.
    (stub-http "versions on return" :url "/api/packages/versions?q=%72%6f%63%2d%6a%73%6f%6e" :status 200 :body "")
    (run-effect 6)
    (stub-http "deps on return" :url "/api/packages/deps?q=%72%6f%63%2d%6a%73%6f%6e" :status 200 :body "")
    (run-effect 7)
    (expect-text (test-id "versions-status") "Versions: none published")
    (expect-text (test-id "versions-empty") "No versions published yet.")
    (expect-text (test-id "deps-status") "Dependencies: none")
    (expect-text (test-id "deps-empty") "This package has no dependencies.")
    (expect-text (test-id "panel-summary") "Panels: 3 ready, 0 loading, 0 failed")
    (expect-visible (text "All panels settled."))
    (history-back)
    (expect-current-location "/")
    (expect-visible (role region :name "Package search"))
    (expect-cleanup "package detail panels" 2)
  )
)
