(test "Markdown editor — Back to the sample document: the whole graph restores."
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (uncheck (label "Number the outline"))
    (check (label "Number the outline"))
    (mark-metrics)
    (select-option (label "Reading speed") "100")
    (select-option (label "Reading speed") "300")
    (select-option (label "Reading speed") "200")
    (mark-metrics)
    (click (role button :name "Append a word"))
    (mark-metrics)
    (click (role button :name "Append a section"))
    (click (role button :name "Append a section"))
    (click (role button :name "Load heading drill"))
    (mark-metrics)
    (click (role button :name "Move the last section up"))
    (mark-metrics)
    (click (role button :name "Remove the last section"))
    (mark-metrics)
    (click (role button :name "Append a section"))
    (mark-metrics)
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Load document without headings"))
    (click (role button :name "Clear document"))
    (fill (label "Markdown source") "word")
    (fill (label "Markdown source") "# Only")
    (fill (label "Markdown source") "## Costs & Trade-offs (2026)")
    (fill (label "Markdown source") "An unmatched ** stays literal, so does a lone ` backtick.")
    (fill (label "Markdown source") "The text [not a link( and ![not an image( are left alone.")
    (fill (label "Markdown source") "#nospace is not a heading, and neither is a bare # on its own line.")
    (fill (label "Markdown source") "# ***")
    (click (role button :name "Append a section"))
    (fill (label "Markdown source") "## Use **map2** for `fan-in`")
    (fill (label "Markdown source") "# One")
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Demote the last heading"))
    (mark-metrics)
    (click (role button :name "Demote the last heading"))
    (mark-metrics)
    (click (role button :name "Demote the last heading"))
    (fill (label "Markdown source") "# One")
    (click (role button :name "Append a section"))
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Demote the last heading"))

    ; 11. Back to the sample document: the whole graph restores.
    ; ---------------------------------------------------------------------------

    (click (role button :name "Load sample document"))
    (expect-text (test-id "stat-words") "147")
    (expect-text (test-id "stat-characters") "822")
    (expect-text (test-id "stat-headings") "5")
    (expect-text (test-id "stat-reading") "1 min")
    (expect-visible (test-id "toc:roc-signals-field-guide"))
    (expect-visible (test-id "toc:performance"))
    (expect-visible (text "Keep derived values derived."))
  )
)
