(test "Markdown editor — Edge case: an empty document. All four views stay locatable."
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (uncheck (label "Number the outline"))
    (check (label "Number the outline"))
    (mark-metrics)
    (select-option (label "Reading speed") "100")
    (select-option (label "Reading speed") "300")
    (select-option (label "Reading speed") "200")
    (mark-metrics)
    (click (role button :name "Append a word"))
    (mark-metrics)
    (click (role button :name "Append a section"))
    (click (role button :name "Append a section"))
    (click (role button :name "Load heading drill"))
    (mark-metrics)
    (click (role button :name "Move the last section up"))
    (mark-metrics)
    (click (role button :name "Remove the last section"))
    (mark-metrics)
    (click (role button :name "Append a section"))
    (mark-metrics)
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Load document without headings"))

    ; 8. Edge case: an empty document. All four views stay locatable.
    ; ---------------------------------------------------------------------------

    (click (role button :name "Clear document"))
    (expect-value (label "Markdown source") "")
    (expect-visible (role region :name "Preview"))
    (expect-visible (text "Preview is empty: type markdown to see it rendered."))
    (expect-visible (role region :name "Table of contents"))
    (expect-visible (text "No headings yet: add a line that starts with a hash."))
    (expect-text (test-id "stat-words") "Words: 0")
    (expect-text (test-id "stat-characters") "Characters: 0")
    (expect-text (test-id "stat-headings") "Headings: 0")
    (expect-text (test-id "stat-reading") "Reading time: 0 min")
    (expect-text (test-id "stat-summary") "Summary: 0 words | 0 characters | 0 headings | 0 min")
    ; A single word is enough to bring the preview back and round the estimate up.
    (fill (label "Markdown source") "word")
    (expect-absent (text "Preview is empty: type markdown to see it rendered."))
    (expect-visible (text "word"))
    (expect-text (test-id "stat-words") "Words: 1")
    (expect-text (test-id "stat-reading") "Reading time: 1 min")
    (expect-visible (text "No headings yet: add a line that starts with a hash."))
    ; A single heading is the smallest possible outline.
    (fill (label "Markdown source") "# Only")
    (expect-absent (text "No headings yet: add a line that starts with a hash."))
    (expect-visible (test-id "toc:only"))
    (expect-attr (test-id "toc:only") data-level "1")
    (expect-text (test-id "stat-headings") "Headings: 1")
  )
)
