(test "Markdown editor — Edge case: markdown special characters and text that looks like markup."
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (uncheck (label "Number the outline"))
    (check (label "Number the outline"))
    (mark-metrics)
    (select-option (label "Reading speed") "100")
    (select-option (label "Reading speed") "300")
    (select-option (label "Reading speed") "200")
    (mark-metrics)
    (click (role button :name "Append a word"))
    (mark-metrics)
    (click (role button :name "Append a section"))
    (click (role button :name "Append a section"))
    (click (role button :name "Load heading drill"))
    (mark-metrics)
    (click (role button :name "Move the last section up"))
    (mark-metrics)
    (click (role button :name "Remove the last section"))
    (mark-metrics)
    (click (role button :name "Append a section"))
    (mark-metrics)
    (click (role button :name "Demote the last heading"))
    (click (role button :name "Load document without headings"))
    (click (role button :name "Clear document"))
    (fill (label "Markdown source") "word")
    (fill (label "Markdown source") "# Only")

    ; 9. Edge case: markdown special characters and text that looks like markup.
    ; ---------------------------------------------------------------------------

    (fill (label "Markdown source") "## Costs & Trade-offs (2026)")
    (expect-text (test-id "stat-headings") "Headings: 1")
    (expect-visible (text "Costs & Trade-offs (2026)"))
    ; Punctuation and case collapse into one slug; the ampersand and parens drop.
    (expect-visible (test-id "toc:costs-trade-offs-2026"))
    (expect-attr (test-id "toc:costs-trade-offs-2026") href "#costs-trade-offs-2026")
    (fill (label "Markdown source") "An unmatched ** stays literal, so does a lone ` backtick.")
    (expect-text (test-id "stat-headings") "Headings: 0")
    (expect-visible (text "An unmatched ** stays literal, so does a lone ` backtick."))
    (fill (label "Markdown source") "The text [not a link( and ![not an image( are left alone.")
    (expect-visible (text "The text [not a link( and ![not an image( are left alone."))
    (expect-text (test-id "stat-headings") "Headings: 0")
    (fill (label "Markdown source") "#nospace is not a heading, and neither is a bare # on its own line.")
    (expect-visible (text "#nospace is not a heading, and neither is a bare # on its own line."))
    (expect-text (test-id "stat-headings") "Headings: 0")
    (expect-visible (text "No headings yet: add a line that starts with a hash."))
    ; A heading made only of punctuation still gets a usable anchor.
    (fill (label "Markdown source") "# ***")
    (expect-text (test-id "stat-headings") "Headings: 1")
    (expect-visible (test-id "toc:section"))
    (expect-attr (test-id "toc:section") href "#section")
    (click (role button :name "Append a section"))
    (expect-text (test-id "stat-headings") "Headings: 2")
    (expect-visible (test-id "toc:section"))
    (expect-visible (test-id "toc:new-section"))
    ; Inline markup inside a heading is stripped for the outline label and slug,
    ; but still rendered as structure in the preview.
    (fill (label "Markdown source") "## Use **map2** for `fan-in`")
    (expect-text (test-id "stat-headings") "Headings: 1")
    (expect-visible (test-id "toc:use-map2-for-fan-in"))
    (expect-visible (text "1. Use map2 for fan-in"))
    (expect-visible (text "Use "))
    (expect-visible (text "map2"))
    (expect-visible (text "fan-in"))
  )
)
