(test "Markdown editor — Initial render: every region, heading, and derived value."
  (steps
    ; 1. Initial render: every region, heading, and derived value.
    ; ---------------------------------------------------------------------------

    (expect-visible (role heading :name "Markdown Editor"))
    (expect-visible (text "One source string, four independently derived views."))
    (expect-visible (role region :name "Editor"))
    (expect-visible (role heading :name "Editor"))
    (expect-attr (role region :name "Editor") data-panel "editor")
    (expect-visible (role button :name "Load sample document"))
    (expect-visible (role button :name "Load document without headings"))
    (expect-visible (role button :name "Load heading drill"))
    (expect-visible (role button :name "Append a word"))
    (expect-visible (role button :name "Append a section"))
    (expect-visible (role button :name "Move the last section up"))
    (expect-visible (role button :name "Demote the last heading"))
    (expect-visible (role button :name "Remove the last section"))
    (expect-visible (role button :name "Clear document"))
    (expect-visible (role region :name "Preview"))
    (expect-visible (role heading :name "Preview"))
    (expect-attr (role region :name "Preview") data-panel "preview")
    (expect-absent (text "Preview is empty: type markdown to see it rendered."))
    (expect-visible (role region :name "Table of contents"))
    (expect-visible (role heading :name "Table of contents"))
    (expect-attr (role region :name "Table of contents") data-panel "outline")
    (expect-checked (label "Number the outline") true)
    (expect-absent (text "No headings yet: add a line that starts with a hash."))
    (expect-visible (role region :name "Statistics"))
    (expect-visible (role heading :name "Statistics"))
    (expect-attr (role region :name "Statistics") data-panel "statistics")
    (expect-value (label "Reading speed") "200")
    (expect-text (test-id "stat-words") "Words: 147")
    (expect-text (test-id "stat-characters") "Characters: 821")
    (expect-text (test-id "stat-headings") "Headings: 5")
    (expect-text (test-id "stat-reading") "Reading time: 1 min")
    (expect-text (test-id "stat-summary") "Summary: 147 words | 821 characters | 5 headings | 1 min")
    ; Preview view: headings, paragraphs, nested list, quote, fence, inline markup.
    (expect-visible (text "Roc Signals Field Guide"))
    (expect-visible (text "Signals keep the graph alive instead of rebuilding a whole view after every event."))
    (expect-visible (text "Getting Started"))
    (expect-visible (text "roc check main.roc"))
    (expect-visible (text "Read the guide end to end"))
    (expect-visible (text "Skim the gallery examples"))
    (expect-visible (text "Live search covers async and cleanup"))
    (expect-visible (text "Write the spec first"))
    (expect-visible (text "Editor Notes"))
    (expect-visible (text "Deep Dive"))
    (expect-visible (text "Performance"))
    (expect-visible (text "Keep derived values derived."))
    (expect-visible (text "map2"))
    (expect-visible (text "combine"))
    (expect-visible (text "the guide"))
    ; Markup that is not markup stays literal in the preview.
    (expect-visible (text "Special characters such as * and _ and # stay literal when they are not real markup."))
    (expect-visible (text "A line that says 2 * 3 = 6 is arithmetic, not emphasis, and [not a link( either."))
    ; A "# ..." line inside a fence is code, not a heading: it renders verbatim and
    ; the outline below has exactly five entries, not six.
    (expect-visible (text "# this hash lives inside a fence and is not a heading"))
    ; Outline view: one row per heading, in document order, with levels.
    (expect-visible (test-id "toc:roc-signals-field-guide"))
    (expect-visible (test-id "toc:getting-started"))
    (expect-visible (test-id "toc:editor-notes"))
    (expect-visible (test-id "toc:deep-dive"))
    (expect-visible (test-id "toc:performance"))
    (expect-attr (test-id "toc:roc-signals-field-guide") data-level "1")
    (expect-attr (test-id "toc:getting-started") data-level "2")
    (expect-attr (test-id "toc:editor-notes") data-level "3")
    ; The document jumps from level three straight to level five; the outline keeps
    ; the real level rather than normalizing it away.
    (expect-attr (test-id "toc:deep-dive") data-level "5")
    (expect-attr (test-id "toc:performance") data-level "2")
    ; The outline is numbered on mount, so its labels stay distinct from the
    ; preview's heading text even though both show the same titles.
    (expect-visible (text "1. Roc Signals Field Guide"))
    (expect-visible (text "2. Getting Started"))
    (expect-visible (text "3. Editor Notes"))
    (expect-visible (text "4. Deep Dive"))
    (expect-visible (text "5. Performance"))
  )
)
