(test "Loan comparator — editing scenario C does not disturb A or B"
  (steps
    ; Given the state established by earlier scenarios
    (select-option (label "Comparison pair") "ac")
    (select-option (label "Comparison pair") "bc")
    (select-option (label "Comparison pair") "ac")
    (mark-metrics)
    (fill (label "Scenario A annual rate") "3")
    (mark-metrics)
    (fill (label "Scenario A extra payment") "50")
    (mark-metrics)
    (fill (label "Scenario A extra payment") "0")
    (fill (label "Scenario A annual rate") "0")
    (fill (label "Scenario A term months") "1")
    (fill (label "Scenario A principal") "0")
    (fill (label "Scenario A principal") "2400")
    (fill (label "Scenario A term months") "12")
    (fill (label "Scenario A annual rate") "6")
    (fill (label "Scenario A annual rate") "abc")
    (fill (label "Scenario A term months") "zz")
    (fill (label "Scenario A annual rate") "6")
    (fill (label "Scenario A term months") "12")

    ; 11. editing scenario C does not disturb A or B

    (mark-metrics)
    (fill (label "Scenario C annual rate") "9")
    (expect-text (test-id "c-payment") "$109.64")
    (expect-text (test-id "c-total-interest") "$231.34")
    (expect-text (test-id "c-month-1") "Month 1 | interest $18.00 | principal $91.64 | balance $2308.36")
    (expect-text (test-id "c-month-24") "Month 24 | interest $0.81 | principal $108.81 | balance $0.00")
    (expect-text (test-id "a-payment") "$206.56")
    (expect-text (test-id "a-month-1") "Month 1 | interest $12.00 | principal $194.56 | balance $2205.44")
    (expect-text (test-id "b-payment") "$213.24")
    (expect-text (test-id "b-month-1") "Month 1 | interest $24.00 | principal $189.24 | balance $2210.76")
    (expect-text (test-id "interest-spread") "$152.72")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta dirty_source_roots 1)
    ; Exactly twelve more than scenario A's edit above, because scenario C has
    ; 24 schedule rows instead of 12. Scenario A's and B's schedules stay quiet.
    (expect-metric-delta derived_calls_into_roc 57)
    (expect-metric-delta rows_reused 27)
    (select-option (label "Comparison pair") "bc")
    (expect-text (test-id "break-even") "Month 24")
    (select-option (label "Comparison pair") "ab")
    (expect-text (test-id "break-even") "Never")
  )
)
