(test "Loan comparator — initial mounted state"
  (steps
    ; 1. initial mounted state

    (expect-visible (role heading :name "Loan Comparator"))
    (expect-visible (role region :name "Loan Comparator"))
    (expect-visible (role region :name "Scenario A"))
    (expect-visible (role region :name "Scenario B"))
    (expect-visible (role region :name "Scenario C"))
    (expect-visible (role region :name "Scenario A schedule"))
    (expect-visible (role region :name "Scenario B schedule"))
    (expect-visible (role region :name "Scenario C schedule"))
    (expect-visible (role region :name "Comparison"))
    (expect-visible (role region :name "Scenario summaries"))
    (expect-visible (role heading :name "Scenario A"))
    (expect-visible (role heading :name "Scenario B"))
    (expect-visible (role heading :name "Scenario C"))
    (expect-visible (role heading :name "Comparison"))
    (expect-value (label "Scenario A principal") "2400")
    (expect-value (label "Scenario A annual rate") "6")
    (expect-value (label "Scenario A term months") "12")
    (expect-value (label "Scenario A extra payment") "0")
    (expect-value (label "Scenario B principal") "2400")
    (expect-value (label "Scenario B annual rate") "12")
    (expect-value (label "Scenario B term months") "12")
    (expect-value (label "Scenario B extra payment") "0")
    (expect-value (label "Scenario C principal") "2400")
    (expect-value (label "Scenario C annual rate") "6")
    (expect-value (label "Scenario C term months") "24")
    (expect-value (label "Scenario C extra payment") "0")
    (expect-text (test-id "a-inputs") "Scenario A inputs: inputs ok")
    (expect-text (test-id "b-inputs") "Scenario B inputs: inputs ok")
    (expect-text (test-id "c-inputs") "Scenario C inputs: inputs ok")
    (expect-text (test-id "a-rate") "Scenario A rate: 6.00%")
    (expect-text (test-id "b-rate") "Scenario B rate: 12.00%")
    (expect-text (test-id "c-rate") "Scenario C rate: 6.00%")
    (expect-text (test-id "a-payment") "Scenario A monthly payment: $206.56")
    (expect-text (test-id "a-total-interest") "Scenario A total interest: $78.62")
    (expect-text (test-id "a-total-paid") "Scenario A total paid: $2478.62")
    (expect-text (test-id "a-payoff") "Scenario A payoff: 12 months")
    (expect-text (test-id "a-final-balance") "Scenario A final balance: $0.00")
    (expect-text (test-id "b-payment") "Scenario B monthly payment: $213.24")
    (expect-text (test-id "b-total-interest") "Scenario B total interest: $158.78")
    (expect-text (test-id "b-total-paid") "Scenario B total paid: $2558.78")
    (expect-text (test-id "b-payoff") "Scenario B payoff: 12 months")
    (expect-text (test-id "b-final-balance") "Scenario B final balance: $0.00")
    (expect-text (test-id "c-payment") "Scenario C monthly payment: $106.37")
    (expect-text (test-id "c-total-interest") "Scenario C total interest: $152.71")
    (expect-text (test-id "c-total-paid") "Scenario C total paid: $2552.71")
    (expect-text (test-id "c-payoff") "Scenario C payoff: 24 months")
    (expect-text (test-id "c-final-balance") "Scenario C final balance: $0.00")
    ; Amortisation rows: first, second and final month of each schedule.
    (expect-text (test-id "a-month-1") "Scenario A month 1: interest $12.00, principal $194.56, balance $2205.44")
    (expect-text (test-id "a-month-2") "Scenario A month 2: interest $11.02, principal $195.54, balance $2009.90")
    (expect-text (test-id "a-month-12") "Scenario A month 12: interest $1.02, principal $205.44, balance $0.00")
    (expect-text (test-id "b-month-1") "Scenario B month 1: interest $24.00, principal $189.24, balance $2210.76")
    (expect-text (test-id "b-month-12") "Scenario B month 12: interest $2.11, principal $211.03, balance $0.00")
    (expect-text (test-id "c-month-1") "Scenario C month 1: interest $12.00, principal $94.37, balance $2305.63")
    (expect-text (test-id "c-month-24") "Scenario C month 24: interest $0.52, principal $105.68, balance $0.00")
    (expect-absent (test-id "a-month-13"))
    ; Cross-scenario derived comparison.
    (expect-text (test-id "cheapest") "Cheapest: Scenario A at $78.62 total interest")
    (expect-text (test-id "interest-spread") "Interest spread: $80.16")
    (expect-text (test-id "schedule-invariant") "Schedule invariant: all final balances are $0.00")
    (expect-value (label "Comparison pair") "ab")
    (expect-text (test-id "break-even") "Break-even (Scenario A vs Scenario B): none")
    (expect-text (test-id "summary-a") "Scenario A summary: $206.56 per month for 12 months, interest $78.62")
    (expect-text (test-id "summary-b") "Scenario B summary: $213.24 per month for 12 months, interest $158.78")
    (expect-text (test-id "summary-c") "Scenario C summary: $106.37 per month for 24 months, interest $152.71")
  )
)
