(test "Availability picker — boundary times: exactly midnight and exactly 23:30"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Mark review available"))
    (click (role button :name "Mark review busy"))
    (mark-metrics)
    (select-option (label "Timezone") "auckland")
    (click (role button :name "Mark review available"))
    (select-option (label "Timezone") "kolkata")
    (select-option (label "Timezone") "nyc")
    (fill (label "Slot name") "Client call")
    (fill (label "Start time") "25:00")
    (fill (label "Start time") "0830")
    (fill (label "Start time") "08:60")
    (fill (label "Start time") "08:30")
    (fill (label "Length") "0")
    (fill (label "Length") "abc")
    (fill (label "Length") "45")
    (select-option (label "Day") "Fri")
    (mark-metrics)
    (click (role button :name "Add slot"))
    (select-option (label "Timezone") "utc")
    (select-option (label "Timezone") "nyc")
    (click (role button :name "Mark s6 available"))
    (mark-metrics)
    (click (role button :name "Move s6 earlier"))
    (mark-metrics)
    (click (role button :name "Remove sunrise"))
    (click (role button :name "Remove review"))
    (click (role button :name "Remove focus"))
    (click (role button :name "Remove s6"))
    (click (role button :name "Remove midnight"))
    (click (role button :name "Remove standup"))

    ; boundary times: exactly midnight and exactly 23:30
    (fill (label "Slot name") "Midnight watch")
    (fill (label "Start time") "00:00")
    (click (role button :name "Add slot"))
    (expect-text (test-id "when-s1") "Mon 00:00-00:30")
    (fill (label "Slot name") "Late watch")
    (fill (label "Start time") "23:30")
    (click (role button :name "Add slot"))
    (expect-text (test-id "when-s2") "Mon 23:30-00:00")
    (select-option (label "Timezone") "utc")
    (expect-text (test-id "when-s1") "Mon 05:00-05:30")
    (expect-text (test-id "when-s2") "Tue 04:30-05:00")
    (click (role button :name "Mark s1 available"))
    (click (role button :name "Mark s2 available"))
    (expect-text (test-id "summary") "1h 0m")
    (expect-text (test-id "stat-slots") "2")
    (expect-text (test-id "stat-conflicts") "0")
    (expect-text (test-id "free-days") "Wed, Thu, Fri, Sat, Sun")
  )
)
