(test "Availability picker — draft validation"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Mark review available"))
    (click (role button :name "Mark review busy"))
    (mark-metrics)
    (select-option (label "Timezone") "auckland")
    (click (role button :name "Mark review available"))
    (select-option (label "Timezone") "kolkata")
    (select-option (label "Timezone") "nyc")

    ; draft validation
    (fill (label "Slot name") "Client call")
    (expect-text (test-id "draft-status") "Ready to add Client call")
    (expect-disabled (role button :name "Add slot") false)
    (fill (label "Start time") "25:00")
    (expect-text (test-id "draft-status") "Start time must be HH:MM")
    (expect-disabled (role button :name "Add slot") true)
    (fill (label "Start time") "0830")
    (expect-text (test-id "draft-status") "Start time must be HH:MM")
    (fill (label "Start time") "08:60")
    (expect-text (test-id "draft-status") "Start time must be HH:MM")
    (fill (label "Start time") "08:30")
    (fill (label "Length") "0")
    (expect-text (test-id "draft-status") "Length must be 1-720 minutes")
    (expect-disabled (role button :name "Add slot") true)
    (fill (label "Length") "abc")
    (expect-text (test-id "draft-status") "Length must be 1-720 minutes")
    (fill (label "Length") "45")
    (select-option (label "Day") "Fri")
    (expect-text (test-id "draft-status") "Ready to add Client call")
    (expect-disabled (role button :name "Add slot") false)
  )
)
