(test "Token editor — initial state"
  (steps
    ; initial state
    (expect-visible (role heading :name "Design Token Editor"))
    (expect-visible (role region :name "Tokens"))
    (expect-visible (role region :name "Preview"))
    (expect-visible (role region :name "Contrast validation"))
    (expect-visible (role region :name "CSS export"))
    (expect-visible (role heading :name "Tokens"))
    (expect-visible (role heading :name "Preview"))
    (expect-visible (role heading :name "Contrast validation"))
    (expect-visible (role heading :name "CSS export"))
    (expect-value (label "Background colour") "#ffffff")
    (expect-value (label "Text colour") "#767676")
    (expect-value (label "Accent colour") "#2563eb")
    (expect-value (label "Spacing small") "8")
    (expect-value (label "Font size medium") "16")
    (expect-value (label "Corner radius medium") "4")
    (expect-text (test-id "token-validity") "All 6 tokens valid")
    (expect-visible (role region :name "Preview surface"))
    (expect-visible (role region :name "Preview button"))
    (expect-visible (role region :name "Preview badge"))
    (expect-attr (test-id "preview-surface") style "color: #767676; background: #ffffff; padding: 8px; font-size: 16px")
    (expect-attr (test-id "preview-button") style "color: #ffffff; background: #2563eb; padding: 8px; font-size: 16px")
    (expect-attr (test-id "preview-badge") style "color: #ffffff; background: #767676; padding: 8px; font-size: 16px")
    (expect-text (test-id "ratio-text") "4.54:1")
    (expect-text (test-id "aa-text") "AA")
    (expect-text (test-id "ratio-button") "5.16:1")
    (expect-text (test-id "aa-button") "AA")
    (expect-text (test-id "aa-summary") "2 of 2 pairs pass AA")
    (expect-text (test-id "stylesheet") ":root { --color-bg: #ffffff; --color-fg: #767676; --color-accent: #2563eb; --space-sm: 8px; --font-md: 16px; --radius-md: 4px; }")
  )
)
