(test "Token editor — several tokens invalid at once"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Text colour") "#777777")
    (fill (label "Text colour") "#767676")
    (fill (label "Accent colour") "#6f8ff0")
    (fill (label "Accent colour") "#2563eb")
    (fill (label "Text colour") "#77zz77")
    (fill (label "Text colour") "#777")
    (fill (label "Text colour") "#767676")
    (fill (label "Spacing small") "0")
    (fill (label "Spacing small") "")
    (fill (label "Spacing small") "8")
    (mark-metrics)
    (fill (label "Corner radius medium") "12")
    (fill (label "Corner radius medium") "abc")
    (fill (label "Corner radius medium") "4")

    ; several tokens invalid at once
    (fill (label "Background colour") "white")
    (fill (label "Font size medium") "-2")
    (expect-text (test-id "token-validity") "Invalid tokens: color-bg, font-md")
    (expect-text (test-id "ratio-text") "n/a")
    (expect-text (test-id "ratio-button") "n/a")
    (expect-text (test-id "aa-summary") "0 of 2 pairs pass AA")
    (expect-text (test-id "stylesheet") ":root { --color-bg: /* invalid */; --color-fg: #767676; --color-accent: #2563eb; --space-sm: 8px; --font-md: /* invalid */; --radius-md: 4px; }")
    (fill (label "Background colour") "#ffffff")
    (fill (label "Font size medium") "20")
    (expect-text (test-id "token-validity") "All 6 tokens valid")
    (expect-text (test-id "preview-surface") "color: #767676; background: #ffffff; padding: 8px; font-size: 20px")
    (expect-text (test-id "aa-summary") "2 of 2 pairs pass AA")
  )
)
