(test "Select control"
  (steps
    ; Single-value select control scenario

    (expect-visible (role heading :name "Select Control"))
    (expect-attr (role region :name "Select Control") data-fixture "select-control")
    (expect-value (label "Plan") "starter")
    (expect-attr (label "Plan") id "plan-select")
    (expect-attr (text "Starter") value "starter")
    (expect-attr (text "Growth") value "growth")
    (expect-attr (text "Enterprise") value "enterprise")
    (expect-text (text "Selected plan: starter") "Selected plan: starter")
    (expect-text (text "Focus events: 0") "Focus events: 0")
    (expect-text (text "Blur events: 0") "Blur events: 0")
    (expect-text (text "Change events: 0") "Change events: 0")
    (focus (label "Plan"))
    (expect-text (text "Focus events: 1") "Focus events: 1")
    (select-option (label "Plan") "growth")
    (expect-value (label "Plan") "growth")
    (expect-text (text "Selected plan: growth") "Selected plan: growth")
    (expect-text (text "Change events: 1") "Change events: 1")
    (select-option (label "Plan") "enterprise")
    (expect-value (label "Plan") "enterprise")
    (expect-text (text "Selected plan: enterprise") "Selected plan: enterprise")
    (expect-text (text "Change events: 2") "Change events: 2")
    (blur (label "Plan"))
    (expect-text (text "Blur events: 1") "Blur events: 1")
  )
)
