(test "Dependency scheduler — initial render"
  (steps
    ; initial render

    (expect-visible (role heading :name "Dependency Scheduler"))
    (expect-visible (role region :name "Project summary"))
    (expect-visible (role region :name "Schedule"))
    (expect-visible (role region :name "Plan health"))
    (expect-absent (role region :name "Cycle report"))
    (expect-visible (role heading :name "Schedule"))
    (expect-visible (role heading :name "Project summary"))
    (expect-text (test-id "project-summary") "10 days")
    (expect-text (test-id "critical-path") "Write spec → Build API → Integrate → QA pass → Launch")
    (expect-text (test-id "focus-detail") "Earliest day 2 · latest day 3 · slack 1 day · moved 0 days")
    (expect-text (test-id "filter-state") "7 of 7 tasks · plan order")
    (expect-value (label "Focus task") "ui")
    (expect-checked (label "Only critical path") false)
    (expect-checked (label "Sort by slack") false)
    (expect-visible (role region :name "Task Write spec"))
    (expect-visible (role region :name "Task Build API"))
    (expect-visible (role region :name "Task Build UI"))
    (expect-visible (role region :name "Task Write docs"))
    (expect-visible (role region :name "Task Integrate"))
    (expect-visible (role region :name "Task QA pass"))
    (expect-visible (role region :name "Task Launch"))
    (expect-text (test-id "line-spec") "Day 0 → 2")
    (expect-text (test-id "line-api") "Day 2 → 6")
    (expect-text (test-id "line-ui") "Day 2 → 5")
    (expect-text (test-id "slack-ui") "1")
    (expect-text (test-id "line-docs") "Day 2 → 3")
    (expect-text (test-id "slack-docs") "7")
    (expect-text (test-id "line-sync") "Day 6 → 8")
    (expect-text (test-id "line-qa") "Day 8 → 10")
    (expect-text (test-id "deps-qa") "After Integrate")
    (expect-text (test-id "line-launch") "Day 10 → 10")
    (expect-text (test-id "duration-launch") "milestone")
    ; The bar geometry is derived from the same row as the text beside it:
    ; Build API starts on day 2 of a 10 day project and runs for 4 days.
    (expect-attr (test-id "bar-api") style "left: 20%; width: 40%")
    (expect-attr (test-id "bar-launch") style "left: 98%; width: 2%")
    (expect-text (test-id "task-count") "7")
    (expect-text (test-id "path-length") "5")
    (expect-text (test-id "slack-count") "2")
    (expect-text (test-id "axis-end") "Day 10")
    (expect-text (test-id "status-spec") "Critical")
    (expect-text (test-id "status-docs") "Has slack")
    (expect-text (test-id "slack-spec") "0")
    (expect-text (test-id "duration-spec") "2 days")
    (expect-text (test-id "deps-spec") "Starts the project")
    (expect-text (test-id "deps-sync") "After Build API, Build UI")
    (expect-attr (test-id "row-spec") data-tone "critical")
    (expect-attr (test-id "row-ui") data-tone "slack")
    (expect-attr (test-id "row-docs") data-tone "slack")
    (expect-attr (test-id "row-launch") data-tone "critical")
    ; The dependency matrix reflects the stored edges.
    (expect-checked (label "Build API after Write spec") true)
    (expect-checked (label "Build API after Build UI") false)
    (expect-checked (label "Integrate after Build API") true)
    (expect-checked (label "Integrate after Build UI") true)
    (expect-checked (label "Write spec after Launch") false)
  )
)
