(test "Closing protects unsaved board data and waits for the save result"
 (steps
  (fill (label "Task title") "Keep this project")
  (request-window-close)
  (expect-window-closed false)
  (expect-visible (test-id "board-close"))
  (click (role button :name "Keep editing"))
  (expect-absent (test-id "board-close"))
  (expect-value (label "Task title") "Keep this project")
  (request-window-close)
  (click (role button :name "Save and close"))
  (expect-visible (test-id "board-close-saving"))
  (expect-window-closed false)
  (stub-file-reject "board-write" :kind permission-denied :detail "/tmp/board.json")
  (resolve-file-choice "board-save-path" (chosen "/tmp/board.json"))
  (expect-window-closed false)
  (expect-visible (test-id "board-close"))
  (click (role button :name "Save and close"))
  (stub-file-write "board-write" :path "/tmp/board.json" :bytes 1)
  (resolve-file-choice "board-save-path" (chosen "/tmp/board.json"))
  (expect-window-closed true)
 ))
