(test "Repeated titles create distinct tasks and deletion requires confirmation"
  (steps
    (expect-disabled (role button :name "Add task") true)
    (fill (label "New task title") "   ")
    (expect-disabled (role button :name "Add task") true)
    (fill (label "New task title") "Review release notes")
    (mark-metrics)
    (click (role button :name "Add task"))
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-visible (test-id "task-7"))
    (expect-value (label "New task title") "")
    (expect-value (label "Task title") "Review release notes")
    (fill (label "New task title") "Review release notes")
    (click (role button :name "Add task"))
    (expect-visible (test-id "task-7"))
    (expect-visible (test-id "task-8"))
    (click (role button :name "Delete task"))
    (click (role button :name "Cancel deletion"))
    (expect-visible (test-id "task-8"))
    (click (role button :name "Delete task"))
    (mark-metrics)
    (click (role button :name "Confirm delete"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (expect-absent (test-id "task-8"))
    (expect-visible (test-id "task-7"))
    (expect-visible (text "Select a task to edit its details."))))
