(test "Drops and explicit controls share movement without losing task details"
  (steps
    (fill (label "Task notes") "Keep this note through each move.")
    (mark-metrics)
    (custom-event (test-id "task-3") "drop" "task-1")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta move_before 1)
    (expect-text (test-id "column-Planned") "Planned3 tasksNormal priority · JonEdit Write the empty-state copyHigh priority · MayaEdit Sketch the welcome screenHigh priority · SamEdit Review keyboard navigation")
    (expect-value (label "Task notes") "Keep this note through each move.")
    (custom-event (test-id "column-Complete") "drop" "task-1")
    (expect-text (test-id "task-column") "Complete")
    (expect-value (label "Task notes") "Keep this note through each move.")
    (custom-event (test-id "task-6") "drop" "task-1")
    (expect-text (test-id "column-Complete") "Complete2 tasksHigh priority · MayaEdit Sketch the welcome screenLow priority · JonEdit Agree on the launch checklist")
    (mark-metrics)
    (custom-event (test-id "task-1") "drop" "task-1")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta move_before 0)
    (custom-event (test-id "column-Planned") "drop" "task-1")
    (click (role button :name "Move to top"))
    (expect-text (test-id "task-column") "Planned")
    (expect-value (label "Task notes") "Keep this note through each move.")))
