(test "Drops and explicit controls share movement without losing task details"
  (steps
    (fill (label "Task notes") "Keep this note through each move.")
    (mark-metrics)
    (custom-event (test-id "task-3") "drop" "task-1")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta move_before 1)
    (expect-text (test-id "column-Planned") "Planned3 tasksWrite the empty-state copyNormal priority · JonEditSketch the welcome screenHigh priority · MayaEditReview keyboard navigationHigh priority · SamEdit")
    (expect-value (label "Task notes") "Keep this note through each move.")
    (custom-event (test-id "column-Complete") "drop" "task-1")
    (expect-text (test-id "task-column") "Complete")
    (expect-value (label "Task notes") "Keep this note through each move.")
    (custom-event (test-id "task-6") "drop" "task-1")
    (expect-text (test-id "column-Complete") "Complete2 tasksSketch the welcome screenHigh priority · MayaEditAgree on the launch checklistLow priority · JonEdit")
    (mark-metrics)
    (custom-event (test-id "task-1") "drop" "task-1")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta move_before 0)
    (custom-event (test-id "column-Planned") "drop" "task-1")
    (click (role button :name "Move to top"))
    (expect-text (test-id "task-column") "Planned")
    (expect-value (label "Task notes") "Keep this note through each move.")))
