(test "Dismissed choosers and write failures preserve unsaved data and permit a retry"
 (steps
  (stub-file-choice "board-save-path" (canceled))
  (click (role button :name "Save"))
  (expect-text (test-id "board-status") "Unsaved changes")
  (expect-text (test-id "board-problem") "Operation canceled; the current board is unchanged.")
  (stub-file-choice "board-save-path" (chosen "/tmp/project.board.json"))
  (stub-file-reject "board-write" :kind permission-denied :detail "/tmp/project.board.json")
  (click (role button :name "Save"))
  (expect-text (test-id "board-problem") "Permission denied: /tmp/project.board.json")
  (expect-text (test-id "board-path") "Untitled board")
  (expect-value (label "Task title") "Sketch the welcome screen")
  (stub-file-choice "board-save-path" (chosen "/tmp/project.board.json"))
  (click (role button :name "Save"))
  (expect-text (test-id "board-status") "Saved")
 ))
