(test "Opening validates complete documents and preserves the current board on refusal"
 (steps
  (fill (label "Task title") "Keep this draft")
  (click (role button :name "Open…"))
  (expect-visible (test-id "board-discard"))
  (click (role button :name "Keep editing"))
  (expect-pending-task "board-open" 0)
  (click (role button :name "Open…"))
  (click (role button :name "Discard and open"))
  (resolve-task "board-open" "6:files16:chosen23:/tmp/project.board.json")
  (resolve-task "board-read" "6:files123:/tmp/project.board.json8:not json")
  (expect-value (label "Task title") "Keep this draft")
  (expect-text (test-id "board-path") "Untitled board")
  (expect-text (test-id "board-problem") "This file is not a complete board JSON document")
  (click (role button :name "Open…"))
  (click (role button :name "Discard and open"))
  (resolve-task "board-open" "6:files16:chosen23:/tmp/project.board.json")
  (resolve-task "board-read" "6:files123:/tmp/project.board.json63:{\"version\":1,\"next\":1,\"planned\":[],\"progress\":[],\"complete\":[]}")
  (expect-text (test-id "board-status") "Saved")
  (expect-text (test-id "board-path") "/tmp/project.board.json")
  (expect-absent (test-id "task-1"))
  (expect-disabled (role button :name "Undo") true)
  (fill (label "New task title") "First task")
  (click (role button :name "Add task"))
  (expect-visible (test-id "task-1"))
  (expect-text (test-id "board-status") "Unsaved changes")
 ))
