(test "Opening validates complete documents and preserves the current board on refusal"
 (steps
  (fill (label "Task title") "Keep this draft")
  (click (role button :name "Open…"))
  (expect-visible (test-id "board-discard"))
  (click (role button :name "Keep editing"))
  (expect-pending-task "board-open" 0)
  (click (role button :name "Open…"))
  (click (role button :name "Discard and open"))
  (expect-disabled (label "Task title") true)
  (expect-disabled (label "Task notes") true)
  (expect-disabled (label "New task title") true)
  (expect-disabled (role button :name "Undo") true)
  (expect-disabled (test-id "task-1") true)
  (stub-file-read "board-read" :path "/tmp/project.board.json" :text "not json")
  (resolve-file-choice "board-open" (chosen "/tmp/project.board.json"))
  (expect-value (label "Task title") "Keep this draft")
  (expect-disabled (label "Task title") false)
  (expect-text (test-id "board-path") "Untitled board")
  (expect-text (test-id "board-problem") "This file is not a complete board JSON document")
  (click (role button :name "Open…"))
  (click (role button :name "Discard and open"))
  (stub-file-read "board-read" :path "/tmp/project.board.json" :text "{\"version\":1,\"next\":1,\"planned\":[],\"progress\":[],\"complete\":[]}")
  (resolve-file-choice "board-open" (chosen "/tmp/project.board.json"))
  (expect-text (test-id "board-status") "Saved")
  (expect-text (test-id "board-path") "/tmp/project.board.json")
  (expect-absent (test-id "task-1"))
  (expect-disabled (role button :name "Undo") true)
  (fill (label "New task title") "First task")
  (click (role button :name "Add task"))
  (expect-visible (test-id "task-1"))
  (expect-text (test-id "board-status") "Unsaved changes")
 ))
