(test "Reorder moves a surviving card and transfer preserves edited domain state"
  (steps
    (fill (label "Task notes") "Keep this edit while moving the task.")
    (mark-metrics)
    (click (role button :name "Move to bottom"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta stream_nodes_scanned 0)
    (expect-metric-delta active_graph_records_rebuilt 0)
    (expect-metric-delta move_before 1)
    (expect-value (label "Task notes") "Keep this edit while moving the task.")
    (mark-metrics)
    (click (role button :name "Move to In progress"))
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 1)
    (expect-text (test-id "task-column") "In progress")
    (expect-value (label "Task notes") "Keep this edit while moving the task.")
    (click (role button :name "Move to Planned"))
    (click (role button :name "Move to top"))
    (expect-text (test-id "task-column") "Planned")
    (expect-value (label "Task notes") "Keep this edit while moving the task.")))
