(test "Saving retains an exact board snapshot while later edits remain dirty"
 (steps
  (stub-file-choice "board-save-path" (chosen "/tmp/project.board.json"))
  (click (role button :name "Save"))
  (expect-text (test-id "board-status") "Saved")
  (expect-text (test-id "board-path") "/tmp/project.board.json")
  (fill (label "Task title") "Edited after save")
  (expect-text (test-id "board-status") "Unsaved changes")
  (click (role button :name "Undo"))
  (expect-value (label "Task title") "Sketch the welcome screen")
  (expect-text (test-id "board-status") "Saved")
  (click (role button :name "Redo"))
  (expect-value (label "Task title") "Edited after save")
  (expect-text (test-id "board-status") "Unsaved changes")
 ))
