(test "Saving retains an exact board snapshot while later edits remain dirty"
 (steps
  (click (role button :name "Save"))
  (expect-pending-task "board-save-path" 1)
  (fill (label "Task title") "Edited after save began")
  (resolve-file-choice "board-save-path" (chosen "/tmp/project.board.json"))
  (expect-pending-task "board-write" 1)
  (resolve-file-write "board-write" :path "/tmp/project.board.json" :bytes 1)
  (expect-text (test-id "board-status") "Unsaved changes")
  (expect-text (test-id "board-path") "/tmp/project.board.json")
  (click (role button :name "Undo"))
  (expect-value (label "Task title") "Sketch the welcome screen")
  (expect-text (test-id "board-status") "Saved")
  (click (role button :name "Redo"))
  (expect-value (label "Task title") "Edited after save began")
  (expect-text (test-id "board-status") "Unsaved changes")
 ))
