(test "Document and board keyboard shortcuts use the same commands as controls"
 (steps
  (fill (label "Task title") "Shortcut edit")
  (shortcut (test-id "launch-board") "z" 1)
  (expect-value (label "Task title") "Sketch the welcome screen")
  (shortcut (test-id "launch-board") "z" 3)
  (expect-value (label "Task title") "Shortcut edit")
  (stub-file-choice "board-save-path" (chosen "/tmp/shortcuts.board.json"))
  (shortcut (test-id "launch-board") "s" 1)
  (stub-file-choice "board-save-path" (canceled))
  (shortcut (test-id "launch-board") "s" 3)
  (stub-file-choice "board-open" (canceled))
  (shortcut (test-id "launch-board") "o" 1)
  (expect-value (label "Task title") "Shortcut edit")
 ))
