(test "Undo and redo restore edits movement creation and deletion without reusing new identities"
 (steps
  (fill (label "Task title") "Renamed")
  (click (role button :name "Undo"))
  (expect-value (label "Task title") "Sketch the welcome screen")
  (click (role button :name "Redo"))
  (expect-value (label "Task title") "Renamed")
  (click (role button :name "Move to Complete"))
  (expect-text (test-id "task-column") "Complete")
  (click (role button :name "Undo"))
  (expect-text (test-id "task-column") "Planned")
  (click (role button :name "Delete task"))
  (click (role button :name "Confirm delete"))
  (expect-absent (test-id "task-1"))
  (click (role button :name "Undo"))
  (expect-value (label "Task title") "Renamed")
  (fill (label "New task title") "New task")
  (click (role button :name "Add task"))
  (expect-visible (test-id "task-7"))
  (click (role button :name "Undo"))
  (expect-absent (test-id "task-7"))
  (click (role button :name "Redo"))
  (expect-visible (test-id "task-7"))
  (click (role button :name "Undo"))
  (fill (label "New task title") "Different task")
  (click (role button :name "Add task"))
  (expect-visible (test-id "task-8"))
  (expect-disabled (role button :name "Redo") true)
 ))
