(test "Canceled navigation retains accepted content and retries the destination"
  (steps
    (click (role button :name "README.md"))
    (click (role button :name "Choose folder"))
    (resolve-file-choice "folder-choice" (chosen "/tmp/project"))
    (expect-pending-task "folder-list" 1)
    (expect-disabled (role button :name "Choose folder") true)
    (expect-text (test-id "dataset-source") "Sample workspace")
    (expect-visible (text "Size: 1536 B"))
    (click (role button :name "Cancel"))
    (expect-pending-task "folder-list" 0)
    (expect-canceled-task "folder-list" 1)
    (expect-visible (text "Canceled"))
    (expect-disabled (role button :name "Back") true)
    (click (role button :name "Retry"))
    (expect-pending-task "folder-list" 1)
    (resolve-stale-task "folder-list" "not decoded after cancellation")
    (expect-text (test-id "dataset-source") "Sample workspace")
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((directory "/tmp/project/docs" 4096) (file "/tmp/project/notes.txt" 12)))
    (expect-visible (text "Folder: /tmp/project"))
    (expect-visible (text "2 matching entries"))
    (click (role button :name "/tmp/project/docs"))
    (expect-visible (text "Folder: /tmp/project"))
    (click (role button :name "Cancel"))
    (resolve-stale-task "folder-list" "canceled child cannot replace its parent")
    (expect-visible (test-id "entry:/tmp/project/notes.txt"))
    (click (role button :name "Retry"))
    (resolve-file-directory "folder-list" :path "/tmp/project/docs" :entries ((file "/tmp/project/docs/readme.md" 5)))
    (expect-visible (text "Folder: /tmp/project/docs"))
    (expect-visible (text "1 matching entries"))
  ))
