(test "A dismissed folder choice retains accepted content and a later choice succeeds"
  (steps
    (click (role button :name "README.md"))
    (stub-file-choice "folder-choice" (canceled))
    (click (role button :name "Choose folder"))
    (expect-visible (text "Folder selection canceled."))
    (expect-text (test-id "dataset-source") "Sample workspace")
    (expect-visible (text "Size: 1536 B"))
    (expect-disabled (role button :name "Back") true)
    (stub-file-choice "folder-choice" (chosen "/tmp/project"))
    (stub-file-directory "folder-list" :path "/tmp/project" :entries ((directory "/tmp/project/docs" 4096) (file "/tmp/project/notes.txt" 12)))
    (click (role button :name "Choose folder"))
    (expect-visible (text "Folder: /tmp/project"))
    (expect-visible (text "2 matching entries"))
    (stub-file-reject "folder-list" :kind not-found :detail "/tmp/project/docs")
    (click (role button :name "/tmp/project/docs"))
    (expect-visible (text "Not found: /tmp/project/docs"))
    (expect-visible (text "Folder: /tmp/project"))
    (expect-visible (test-id "entry:/tmp/project/notes.txt"))
    (stub-file-directory "folder-list" :path "/tmp/project/docs" :entries ((file "/tmp/project/docs/readme.md" 5)))
    (click (role button :name "Retry"))
    (expect-visible (text "Folder: /tmp/project/docs"))
    (expect-visible (text "1 matching entries"))
  ))
