(test "Chooser dismissal and navigation failure keep the accepted folder and history"
  (steps
    (shortcut (test-id "explorer") "o" 1)
    (resolve-file-choice "folder-choice" (canceled))
    (expect-visible (text "Folder selection canceled."))
    (click (role button :name "Choose folder"))
    (shortcut (test-id "explorer") "Escape" 0)
    (expect-canceled-task "folder-choice" 1)
    (resolve-stale-task "folder-choice" "late chooser result is ignored")
    (click (role button :name "Choose folder"))
    (resolve-file-choice "folder-choice" (chosen "/tmp/project"))
    (reject-file "folder-list" :kind permission-denied :detail "/tmp/project")
    (expect-visible (text "Permission denied: /tmp/project"))
    (expect-text (test-id "dataset-source") "Sample workspace")
    (expect-visible (text "6 matching entries"))
    (click (role button :name "Retry"))
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((directory "/tmp/project/docs" 0)))
    (click (role button :name "/tmp/project/docs"))
    (resolve-file-directory "folder-list" :path "/tmp/project/docs" :entries ())
    (click (role button :name "Back"))
    (reject-file "folder-list" :kind not-found :detail "/tmp/project")
    (expect-visible (text "Folder: /tmp/project/docs"))
    (expect-disabled (role button :name "Forward") true)
    (click (role button :name "Retry"))
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((directory "/tmp/project/docs" 0)))
    (expect-visible (text "Folder: /tmp/project"))
    (expect-disabled (role button :name "Forward") false)
    (click (role button :name "Forward"))
    (resolve-file-directory "folder-list" :path "/tmp/project/docs" :entries ())
    (expect-visible (text "Folder: /tmp/project/docs"))
  ))
