(test "Preview and associated launch use typed cancellable tasks without losing content"
  (steps
    (click (role button :name "Choose folder"))
    (resolve-file-choice "folder-choice" (chosen "/tmp/project"))
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((file "/tmp/project/note.txt" 70000) (symbolic-link "/tmp/project/link" 4)))
    (click (role button :name "/tmp/project/note.txt"))
    (click (role button :name "Preview text"))
    (expect-pending-task "file-preview" 1)
    (expect-disabled (role button :name "Open in app") true)
    (resolve-file-preview "file-preview" :path "/tmp/project/note.txt" :text "First line\nλ" :truncated true)
    (expect-value (label "Text preview") "First line\nλ")
    (expect-visible (text "Preview: /tmp/project/note.txt · truncated"))
    (click (role button :name "Preview text"))
    (click (role button :name "Cancel"))
    (expect-value (label "Text preview") "First line\nλ")
    (resolve-stale-task "file-preview" "canceled preview is never decoded")
    (click (role button :name "Retry"))
    (reject-file "file-preview" :kind invalid-utf8 :detail "/tmp/project/note.txt")
    (expect-visible (text "Not valid UTF-8: /tmp/project/note.txt"))
    (expect-value (label "Text preview") "First line\nλ")
    (click (role button :name "Open in app"))
    (reject-file "file-open" :kind unavailable :detail "No associated application")
    (expect-value (label "Text preview") "First line\nλ")
    (click (role button :name "Retry"))
    (resolve-file-open "file-open" :path "/tmp/project/note.txt")
    (expect-visible (text "Opened /tmp/project/note.txt in its associated application."))
    (click (role button :name "/tmp/project/link"))
    (expect-disabled (role button :name "Preview text") true)
    (expect-disabled (role button :name "Open in app") true)
    (expect-visible (text "Symbolic links are shown but are not followed."))
  ))
