(test "Sample folders support breadcrumbs Up Back Forward and text previews"
  (steps
    (click (role button :name "docs"))
    (click (role button :name "docs/日本語.md"))
    (click (role button :name "Preview text"))
    (expect-value (label "Text preview") "# 日本語のメモ\n\nファイル名と本文の両方で Unicode を保持します。")
    (expect-visible (text "Sample preview. Sample files are not stored on this computer."))
    (shortcut (test-id "explorer") "ArrowUp" 4)
    (expect-visible (text "6 matching entries"))
    (shortcut (test-id "explorer") "ArrowLeft" 4)
    (expect-visible (text "Sample workspace / docs"))
    (shortcut (test-id "explorer") "ArrowRight" 4)
    (expect-visible (text "6 matching entries"))
    (click (role button :name "src"))
    (expect-visible (text "Sample workspace / src"))
    (expect-disabled (role button :name "Forward") true)
    (click (role button :name "Go to sample root"))
    (click (role button :name "release-notes.md"))
    (click (role button :name "Preview text"))
    (expect-value (label "Text preview") "")
    (expect-visible (text "Preview: release-notes.md"))
    (shortcut (test-id "explorer") "F5" 0)
    (expect-visible (text "6 matching entries"))
    (expect-visible (text "No preview loaded."))
  ))
