(test "Sample filtering and sorting keep selected metadata independent"
  (steps
    (expect-text (test-id "dataset-source") "Sample workspace")
    (expect-visible (text "6 matching entries"))
    (expect-disabled (role button :name "Back") true)
    (expect-disabled (role button :name "Up") true)
    (mark-metrics)
    (click (role button :name "README.md"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (expect-visible (text "Size: 1536 B"))
    (expect-disabled (role button :name "Open in app") true)
    (fill (role textbox :name "Filter this folder") "README")
    (expect-visible (text "1 matching entries"))
    (expect-absent (test-id "entry:docs"))
    (expect-visible (text "Size: 1536 B"))
    (click (role button :name "Largest files"))
    (fill (role textbox :name "Filter this folder") "no matches")
    (expect-visible (text "No matching entries. Clear the filter or choose another folder."))
    (expect-visible (text "Size: 1536 B"))
    (click (role button :name "Clear filter"))
    (expect-visible (text "6 matching entries"))
    (click (role button :name "docs"))
    (expect-value (label "Filter this folder") "")
    (expect-visible (text "Sample workspace / docs"))
    (expect-visible (text "3 matching entries"))
    (expect-visible (test-id "entry:docs/日本語.md"))
    (expect-absent (test-id "entry:src"))
  ))
