(test "Sample filtering and sorting keep selected metadata independent"
  (steps
    (expect-visible (text "Sample workspace"))
    (expect-visible (text "16 matching entries"))
    (mark-metrics)
    (click (role button :name "README.md"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (expect-visible (text "Size: 1536 B"))
    (fill (role textbox :name "Filter paths") "DOCS/")
    (expect-visible (text "3 matching entries"))
    (expect-visible (test-id "entry:docs/日本語.md"))
    (expect-absent (test-id "entry:README.md"))
    (expect-visible (text "Size: 1536 B"))
    (click (role button :name "Largest files"))
    (expect-visible (text "3 matching entries"))
    (fill (role textbox :name "Filter paths") "no matches")
    (expect-visible (text "No matching paths. Try a different filter."))
    (fill (role textbox :name "Filter paths") "")
    (expect-visible (text "16 matching entries"))
    (expect-visible (test-id "entry:README.md"))
  ))
