(test "Folder scans replace complete metadata and reconcile selected paths"
  (steps
    (click (role button :name "Choose folder"))
    (expect-pending-task "folder-choice" 1)
    (expect-visible (text "16 matching entries"))
    (resolve-task "folder-choice" "6:files16:chosen12:/tmp/project")
    (expect-pending-task "folder-scan" 1)
    (expect-visible (text "Sample workspace"))
    (resolve-task "folder-scan" "6:files112:/tmp/project1:417:/tmp/project/docs9:directory4:409622:/tmp/project/notes.txt4:file2:1220:/tmp/project/current13:symbolic-link1:924:/tmp/project/events.pipe5:other1:0")
    (expect-visible (text "Folder: /tmp/project"))
    (expect-visible (text "4 matching entries"))
    (expect-visible (text "1 files · 1 folders · 1 links · 1 other · 12 B"))
    (expect-visible (text "notes.txt"))
    (click (role button :name "/tmp/project/notes.txt"))
    (expect-visible (text "/tmp/project/notes.txt"))
    (expect-visible (text "Size: 12 B"))
    (click (role button :name "Rescan"))
    (expect-pending-task "folder-scan" 1)
    (expect-visible (text "Size: 12 B"))
    (resolve-task "folder-scan" "6:files112:/tmp/project1:122:/tmp/project/notes.txt4:file2:24")
    (expect-visible (text "Size: 24 B"))
    (expect-visible (text "1 matching entries"))
    (click (role button :name "Rescan"))
    (resolve-task "folder-scan" "6:files112:/tmp/project1:0")
    (expect-visible (text "0 matching entries"))
    (expect-visible (text "Select a file or folder to inspect its metadata."))
    (click (role button :name "Load sample"))
    (expect-visible (text "Sample workspace"))
    (expect-visible (text "16 matching entries"))
  ))
