(test "Direct-child navigation refresh and breadcrumbs reconcile accepted paths"
  (steps
    (click (role button :name "Choose folder"))
    (resolve-file-choice "folder-choice" (chosen "/tmp/project"))
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((directory "/tmp/project/docs" 4096) (file "/tmp/project/notes.txt" 12) (symbolic-link "/tmp/project/current" 9) (other "/tmp/project/events.pipe" 0)))
    (expect-visible (text "1 files · 1 folders · 1 links · 1 other · 12 B"))
    (expect-visible (text "notes.txt"))
    (click (role button :name "/tmp/project/notes.txt"))
    (expect-visible (text "Size: 12 B"))
    (click (role button :name "Refresh"))
    (expect-visible (text "Size: 12 B"))
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((directory "/tmp/project/docs" 0) (file "/tmp/project/notes.txt" 24)))
    (expect-visible (text "Size: 24 B"))
    (click (role button :name "/tmp/project/docs"))
    (resolve-file-directory "folder-list" :path "/tmp/project/docs" :entries ((file "/tmp/project/docs/日本語.md" 7)))
    (expect-absent (test-id "entry:/tmp/project/notes.txt"))
    (click (role button :name "Go to /tmp/project"))
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ((file "/tmp/project/notes.txt" 24)))
    (click (role button :name "/tmp/project/notes.txt"))
    (shortcut (test-id "explorer") "F5" 0)
    (resolve-file-directory "folder-list" :path "/tmp/project" :entries ())
    (expect-visible (text "0 matching entries"))
    (expect-visible (text "Select a file to inspect it. Open a folder to browse its contents."))
    (click (role button :name "Use sample"))
    (expect-visible (text "6 matching entries"))
  ))
