(test "Windows breadcrumbs name the drive root and every real parent folder"
  (steps
    (click (role button :name "Choose folder"))
    (resolve-file-choice "folder-choice" (chosen "C:\\Users\\Lee"))
    (resolve-file-directory "folder-list" :path "C:\\Users\\Lee"
      :entries ((directory "C:\\Users\\Lee\\Notes" 0) (file "C:\\Users\\Lee\\Ideas.txt" 5)))
    (expect-visible (label "Go to C:\\"))
    (expect-visible (label "Go to C:\\Users"))
    (expect-visible (label "Go to C:\\Users\\Lee"))
    (expect-text (test-id "dataset-source") "Folder: C:\\Users\\Lee")
    (expect-visible (text "Ideas.txt"))
    (expect-visible (text "Notes"))
    (click (role button :name "C:\\Users\\Lee\\Notes"))
    (resolve-file-directory "folder-list" :path "C:\\Users\\Lee\\Notes" :entries ())
    (expect-text (test-id "dataset-source") "Folder: C:\\Users\\Lee\\Notes")
    (click (role button :name "Up"))
    (resolve-file-directory "folder-list" :path "C:\\Users\\Lee" :entries ())
    (expect-text (test-id "dataset-source") "Folder: C:\\Users\\Lee")
    (click (label "Go to C:\\Users"))
    (resolve-file-directory "folder-list" :path "C:\\Users" :entries ((directory "C:\\Users\\Lee" 0)))
    (expect-text (test-id "dataset-source") "Folder: C:\\Users")
    (expect-visible (role button :name "C:\\Users\\Lee"))
    (expect-visible (text "Lee"))
  ))
