(test "Split the bill — adding a person re splits every expense"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")
    (uncheck (label "Cabin includes Chloe"))
    (check (label "Cabin includes Chloe"))
    (uncheck (label "Taxi includes Ben"))
    (uncheck (label "Taxi includes Chloe"))
    (check (label "Taxi includes Ben"))
    (check (label "Taxi includes Chloe"))

    ; adding a person re splits every expense

    (fill (label "New person name") "Ana")
    (expect-text (test-id "person-draft-note") "Ana is already on the trip.")
    (expect-disabled (role button :name "Add person") true)
    (fill (label "New person name") " Di ")
    (expect-text (test-id "person-draft-note") "Ready to add Di.")
    (expect-disabled (role button :name "Add person") false)
    (mark-metrics)
    (click (role button :name "Add person"))
    ; Adding a person creates exactly six rows: the person's balance card, the new
    ; payer option, one participation checkbox in each of the three expenses, and
    ; the extra settlement transfer. Every existing row is reused.
    (expect-metric-delta rows_created 6)
    (expect-metric-delta rows_reused 20)
    (expect-metric-delta rows_removed 0)
    (expect-value (label "New person name") "")
    (expect-visible (role region :name "Di"))
    (expect-text (test-id "trip-people-count") "4")
    (expect-text (test-id "expense-Cabin-shares") "Ana $75.00, Ben $75.00, Chloe $75.00, Di $75.00")
    (expect-text (test-id "expense-Dinner-shares") "Ana $15.63, Ben $15.63, Chloe $15.62, Di $15.62")
    (expect-text (test-id "expense-Taxi-shares") "Ben $8.00, Chloe $8.00, Di $8.00")
    (expect-checked (label "Taxi includes Di") true)
    (expect-text (test-id "person-Di-totals") "Paid $0.00 / owes $98.62")
    (expect-text (test-id "person-Di-net") "-$98.62")
    (expect-text (test-id "person-Di-removal") "Can leave the trip")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "settlement-summary") "3 transfers")
    (expect-text (test-id "transfer-Di>Ana") "Di pays Ana")
    (expect-text (test-id "transfer-Di>Ana-amount") "$98.62")
    (expect-text (test-id "transfer-Chloe>Ana") "Chloe pays Ana")
    (expect-text (test-id "transfer-Chloe>Ana-amount") "$74.62")
    (expect-text (test-id "transfer-Ben>Ana") "Ben pays Ana")
    (expect-text (test-id "transfer-Ben>Ana-amount") "$36.13")
  )
)
