(test "Split the bill — changing who shares an expense"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")

    ; changing who shares an expense

    (uncheck (label "Cabin includes Chloe"))
    (expect-checked (label "Cabin includes Chloe") false)
    (expect-text (test-id "expense-Cabin-status") "$300.00 paid by Ana, split 2 ways")
    (expect-text (test-id "expense-Cabin-shares") "Ana $150.00, Ben $150.00")
    (expect-text (test-id "person-Chloe-totals") "Paid $24.00 / owes $32.83")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "transfer-Ben>Ana") "Ben pays Ana")
    (expect-text (test-id "transfer-Ben>Ana-amount") "$120.33")
    (expect-text (test-id "transfer-Chloe>Ana") "Chloe pays Ana")
    (expect-text (test-id "transfer-Chloe>Ana-amount") "$8.83")
    (check (label "Cabin includes Chloe"))
    (expect-checked (label "Cabin includes Chloe") true)
    (expect-text (test-id "expense-Cabin-shares") "Ana $100.00, Ben $100.00, Chloe $100.00")
    ; An expense nobody shares is excluded entirely, payer included, so the plan
    ; still balances.
    (uncheck (label "Taxi includes Ben"))
    (uncheck (label "Taxi includes Chloe"))
    (expect-text (test-id "expense-Taxi-status") "Nobody is sharing this")
    (expect-text (test-id "expense-Taxi-shares") "No shares")
    (expect-text (test-id "trip-total") "$362.50")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "person-Chloe-totals") "Paid $0.00 / owes $120.83")
    ; Chloe no longer pays for anything, so Chloe may now leave the trip.
    (expect-text (test-id "person-Chloe-removal") "Can leave the trip")
    (expect-disabled (role button :name "Remove Chloe") false)
    (expect-text (test-id "transfer-Chloe>Ana") "Chloe pays Ana")
    (expect-text (test-id "transfer-Chloe>Ana-amount") "$120.83")
    (expect-text (test-id "transfer-Ben>Ana") "Ben pays Ana")
    (expect-text (test-id "transfer-Ben>Ana-amount") "$58.33")
    (check (label "Taxi includes Ben"))
    (check (label "Taxi includes Chloe"))
    (expect-text (test-id "expense-Taxi-shares") "Ben $12.00, Chloe $12.00")
    (expect-text (test-id "person-Chloe-removal") "Payer on 1 expense")
    (expect-text (test-id "trip-total") "$386.50")
  )
)
