(test "Split the bill — initial render"
  (steps
    ; initial render

    (expect-visible (role heading :name "Split the Bill"))
    (expect-visible (role region :name "People"))
    (expect-visible (role region :name "Expenses"))
    (expect-visible (role region :name "Settlement plan"))
    (expect-visible (role region :name "Trip totals"))
    (expect-visible (role form :name "Add person form"))
    (expect-value (label "New person name") "")
    (expect-text (test-id "person-draft-note") "Enter a name to add them to the trip.")
    (expect-disabled (role button :name "Add person") true)
    (expect-visible (role form :name "Add expense form"))
    (expect-value (label "New expense description") "")
    (expect-value (label "New expense amount") "")
    (expect-value (label "New expense payer") "Ana")
    (expect-text (test-id "expense-draft-note") "Describe the expense to add it.")
    (expect-disabled (role button :name "Add expense") true)
    (expect-visible (role region :name "Ana"))
    (expect-visible (role region :name "Ben"))
    (expect-visible (role region :name "Chloe"))
    (expect-text (test-id "person-Ana-totals") "Paid $300.00 / owes $120.84")
    (expect-text (test-id "person-Ana-net") "+$179.16")
    (expect-text (test-id "person-Ana-removal") "Payer on 1 expense")
    (expect-disabled (role button :name "Remove Ana") true)
    (expect-text (test-id "person-Ben-totals") "Paid $62.50 / owes $132.83")
    (expect-text (test-id "person-Ben-net") "-$70.33")
    (expect-text (test-id "person-Chloe-totals") "Paid $24.00 / owes $132.83")
    (expect-text (test-id "person-Chloe-net") "-$108.83")
    (expect-visible (role region :name "Cabin"))
    (expect-value (label "Cabin amount") "300.00")
    (expect-text (test-id "expense-Cabin-status") "$300.00 paid by Ana, split 3 ways")
    (expect-text (test-id "expense-Cabin-shares") "Ana $100.00, Ben $100.00, Chloe $100.00")
    (expect-checked (label "Cabin includes Ana") true)
    (expect-checked (label "Cabin includes Ben") true)
    (expect-checked (label "Cabin includes Chloe") true)
    ; 6250 cents over 3 people does not divide evenly: the first participant in trip
    ; order takes the leftover cent, so the shares still add back to $62.50.
    (expect-visible (role region :name "Dinner"))
    (expect-value (label "Dinner amount") "62.50")
    (expect-text (test-id "expense-Dinner-status") "$62.50 paid by Ben, split 3 ways")
    (expect-text (test-id "expense-Dinner-shares") "Ana $20.84, Ben $20.83, Chloe $20.83")
    ; An expense shared by a subset: Ana is not on the taxi.
    (expect-visible (role region :name "Taxi"))
    (expect-value (label "Taxi amount") "24.00")
    (expect-text (test-id "expense-Taxi-status") "$24.00 paid by Chloe, split 2 ways")
    (expect-text (test-id "expense-Taxi-shares") "Ben $12.00, Chloe $12.00")
    (expect-checked (label "Taxi includes Ana") false)
    (expect-checked (label "Taxi includes Ben") true)
    (expect-checked (label "Taxi includes Chloe") true)
    (expect-text (test-id "settlement-summary") "2 transfers")
    (expect-text (test-id "transfer-Chloe>Ana") "Chloe pays Ana")
    (expect-text (test-id "transfer-Chloe>Ana-amount") "$108.83")
    (expect-text (test-id "transfer-Ben>Ana") "Ben pays Ana")
    (expect-text (test-id "transfer-Ben>Ana-amount") "$70.33")
    (expect-text (test-id "trip-people-count") "3")
    (expect-text (test-id "trip-expense-count") "3")
    (expect-text (test-id "trip-total") "$386.50")
    ; The per-person figure is the bill total over the roster size, derived from the
    ; same two sources as the total itself.
    (expect-text (test-id "trip-person-share") "$128.83")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "trip-summary") "3 people, 3 expenses, $386.50 recorded, balances check $0.00")
  )
)
