(test "Split the bill — one person, then none"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")
    (uncheck (label "Cabin includes Chloe"))
    (check (label "Cabin includes Chloe"))
    (uncheck (label "Taxi includes Ben"))
    (uncheck (label "Taxi includes Chloe"))
    (check (label "Taxi includes Ben"))
    (check (label "Taxi includes Chloe"))
    (fill (label "New person name") "Ana")
    (fill (label "New person name") " Di ")
    (mark-metrics)
    (click (role button :name "Add person"))
    (click (role button :name "Remove Di"))
    (fill (label "New expense description") "Coffee")
    (fill (label "New expense amount") "5.00")
    (select-option (label "New expense payer") "Ben")
    (select-option (label "New expense payer") "Ana")
    (click (role button :name "Add expense"))
    (fill (label "New expense description") "Coffee")
    (fill (label "New expense description") "Snacks")
    (fill (label "New expense amount") "1.00")
    (submit (role form :name "Add expense form"))
    (click (role button :name "Remove Snacks"))
    (click (role button :name "Remove Coffee"))
    (click (role button :name "Remove Cabin"))
    (click (role button :name "Remove Dinner"))
    (click (role button :name "Remove Taxi"))

    ; one person, then none

    (click (role button :name "Remove Ben"))
    (click (role button :name "Remove Chloe"))
    (expect-absent (role region :name "Ben"))
    (expect-text (test-id "trip-people-count") "1")
    (expect-text (test-id "person-Ana-net") "$0.00")
    (expect-text (test-id "settlement-summary") "Settled up")
    (click (role button :name "Remove Ana"))
    (expect-absent (role region :name "Ana"))
    (expect-visible (text "Nobody on the trip yet. Add someone to start."))
    (expect-text (test-id "trip-people-count") "0")
    (expect-text (test-id "trip-total") "$0.00")
    ; An empty roster has no divisor, so the per-person share falls back to zero.
    (expect-text (test-id "trip-person-share") "$0.00")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "settlement-summary") "Settled up")
    (expect-text (test-id "trip-summary") "0 people, 0 expenses, $0.00 recorded, balances check $0.00")
    ; With nobody on the trip there is no valid payer, so the draft cannot be added.
    (fill (label "New expense description") "Ferry")
    (fill (label "New expense amount") "9.00")
    (expect-text (test-id "expense-draft-note") "Choose who paid.")
    (expect-disabled (role button :name "Add expense") true)
    (fill (label "New person name") "Zed")
    (click (role button :name "Add person"))
    (expect-text (test-id "trip-people-count") "1")
    (expect-text (test-id "expense-draft-note") "Choose who paid.")
    (expect-disabled (role button :name "Add expense") true)
    (select-option (label "New expense payer") "Zed")
    (expect-text (test-id "expense-draft-note") "Ready to add Ferry for $9.00.")
    (expect-disabled (role button :name "Add expense") false)
    (click (role button :name "Add expense"))
    (expect-visible (role region :name "Ferry"))
    (expect-text (test-id "expense-Ferry-status") "$9.00 paid by Zed, split 1 way")
    (expect-text (test-id "expense-Ferry-shares") "Zed $9.00")
    (expect-text (test-id "person-Zed-net") "$0.00")
    (expect-text (test-id "person-Zed-removal") "Payer on 1 expense")
    (expect-text (test-id "trip-total") "$9.00")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "settlement-summary") "Settled up")
    (uncheck (label "Ferry includes Zed"))
    (expect-text (test-id "expense-Ferry-status") "Nobody is sharing this")
    (expect-text (test-id "expense-Ferry-shares") "No shares")
    (expect-text (test-id "trip-total") "$0.00")
    (expect-text (test-id "person-Zed-removal") "Can leave the trip")
    (expect-text (test-id "trip-balances-check") "$0.00")
  )
)
