(test "Form builder — deleting a field that holds invalid input"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))
    (click (role button :name "Add number field"))
    (fill (label "Answer f3") "abc")
    (fill (label "Answer f3") "42")
    (fill (label "Maximum f3") "10")
    (fill (label "Minimum f3") "20")
    (fill (label "Minimum f3") "2x")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (fill (label "Answer f3") "5")
    (fill (label "Answer f3") "25")
    (click (role button :name "Add select field"))
    (fill (label "Options f4") "Small, Medium, Large")
    (select-option (label "Answer f4") "Medium")
    (fill (label "Options f4") "Small, Large")
    (select-option (label "Answer f4") "Large")
    (click (role button :name "Add checkbox field"))
    (check (label "Required f5"))
    (check (label "Answer f5"))
    (click (role button :name "Add text field"))
    (click (role button :name "Add email field"))
    (mark-metrics)
    (click (role button :name "Move up f2"))
    (click (role button :name "Move down f2"))
    (click (role button :name "Move up f1"))
    (click (role button :name "Move up f1"))
    (click (role button :name "Move down f7"))

    ; deleting a field that holds invalid input
    (check (label "Required f6"))
    (expect-text (test-id "preview-f6-verdict") "This field is required")
    (expect-text (test-id "preview-status") "1")
    (expect-text (test-id "submittable-state") "Not ready")
    (mark-metrics)
    (click (role button :name "Delete f6"))
    (expect-metric-delta rows_removed 2)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 12)
    (expect-absent (role region :name "Field f6"))
    (expect-absent (role region :name "Preview field f6"))
    (expect-text (test-id "designer-status") "6")
    (expect-text (test-id "preview-status") "0")
    (expect-text (test-id "submittable-state") "Ready to submit")
    (expect-disabled (role button :name "Submit form") false)
  )
)
