(test "Split the bill — adding an expense"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")
    (uncheck (label "Cabin includes Cy"))
    (check (label "Cabin includes Cy"))
    (uncheck (label "Taxi includes Bo"))
    (uncheck (label "Taxi includes Cy"))
    (check (label "Taxi includes Bo"))
    (check (label "Taxi includes Cy"))
    (fill (label "New person name") "Ana")
    (fill (label "New person name") " Di ")
    (mark-metrics)
    (click (role button :name "Add person"))
    (click (role button :name "Remove Di"))

    ; adding an expense

    (fill (label "New expense description") "Coffee")
    (expect-text (test-id "expense-draft-note") "Expense form: enter an amount such as 12.50")
    (expect-disabled (role button :name "Add expense") true)
    (fill (label "New expense amount") "5.00")
    (expect-text (test-id "expense-draft-note") "Expense form: ready to add Coffee for $5.00")
    (expect-disabled (role button :name "Add expense") false)
    (select-option (label "New expense payer") "Bo")
    (expect-value (label "New expense payer") "Bo")
    (select-option (label "New expense payer") "Ana")
    (expect-value (label "New expense payer") "Ana")
    (click (role button :name "Add expense"))
    (expect-value (label "New expense description") "")
    (expect-value (label "New expense amount") "")
    (expect-visible (role region :name "Coffee"))
    (expect-text (test-id "trip-expense-count") "Expenses recorded: 4")
    (expect-text (test-id "expense-Coffee-status") "Status: $5.00 paid by Ana, split 3 ways")
    (expect-text (test-id "expense-Coffee-shares") "Shares: Ana $1.67, Bo $1.67, Cy $1.66")
    (expect-text (test-id "person-Ana-removal") "Removal: blocked, payer on 2 expenses")
    (expect-text (test-id "trip-total") "Trip total: $391.50")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
    (expect-text (test-id "transfer-Cy>Ana") "Cy owes Ana $110.49")
    (expect-text (test-id "transfer-Bo>Ana") "Bo owes Ana $72.00")
    (fill (label "New expense description") "Coffee")
    (expect-text (test-id "expense-draft-note") "Expense form: Coffee is already recorded")
    (expect-disabled (role button :name "Add expense") true)
    (fill (label "New expense description") "Snacks")
    (fill (label "New expense amount") "1.00")
    (submit (role form :name "Add expense form"))
    (expect-visible (role region :name "Snacks"))
    (expect-text (test-id "trip-expense-count") "Expenses recorded: 5")
    (expect-text (test-id "expense-Snacks-shares") "Shares: Ana $0.34, Bo $0.33, Cy $0.33")
    (expect-text (test-id "person-Ana-removal") "Removal: blocked, payer on 3 expenses")
    (expect-text (test-id "trip-total") "Trip total: $392.50")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
  )
)
