(test "Split the bill — adding an expense"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")
    (uncheck (label "Cabin includes Chloe"))
    (check (label "Cabin includes Chloe"))
    (uncheck (label "Taxi includes Ben"))
    (uncheck (label "Taxi includes Chloe"))
    (check (label "Taxi includes Ben"))
    (check (label "Taxi includes Chloe"))
    (fill (label "New person name") "Ana")
    (fill (label "New person name") " Di ")
    (mark-metrics)
    (click (role button :name "Add person"))
    (click (role button :name "Remove Di"))

    ; adding an expense

    (fill (label "New expense description") "Coffee")
    (expect-text (test-id "expense-draft-note") "Enter an amount such as 12.50.")
    (expect-disabled (role button :name "Add expense") true)
    (fill (label "New expense amount") "5.00")
    (expect-text (test-id "expense-draft-note") "Ready to add Coffee for $5.00.")
    (expect-disabled (role button :name "Add expense") false)
    (select-option (label "New expense payer") "Ben")
    (expect-value (label "New expense payer") "Ben")
    (select-option (label "New expense payer") "Ana")
    (expect-value (label "New expense payer") "Ana")
    (click (role button :name "Add expense"))
    (expect-value (label "New expense description") "")
    (expect-value (label "New expense amount") "")
    (expect-visible (role region :name "Coffee"))
    (expect-text (test-id "trip-expense-count") "4")
    (expect-text (test-id "expense-Coffee-status") "$5.00 paid by Ana, split 3 ways")
    (expect-text (test-id "expense-Coffee-shares") "Ana $1.67, Ben $1.67, Chloe $1.66")
    (expect-text (test-id "person-Ana-removal") "Payer on 2 expenses")
    (expect-text (test-id "trip-total") "$391.50")
    (expect-text (test-id "trip-balances-check") "$0.00")
    (expect-text (test-id "transfer-Chloe>Ana") "Chloe pays Ana")
    (expect-text (test-id "transfer-Chloe>Ana-amount") "$110.49")
    (expect-text (test-id "transfer-Ben>Ana") "Ben pays Ana")
    (expect-text (test-id "transfer-Ben>Ana-amount") "$72.00")
    (fill (label "New expense description") "Coffee")
    (expect-text (test-id "expense-draft-note") "Coffee is already recorded.")
    (expect-disabled (role button :name "Add expense") true)
    (fill (label "New expense description") "Snacks")
    (fill (label "New expense amount") "1.00")
    (submit (role form :name "Add expense form"))
    (expect-visible (role region :name "Snacks"))
    (expect-text (test-id "trip-expense-count") "5")
    (expect-text (test-id "expense-Snacks-shares") "Ana $0.34, Ben $0.33, Chloe $0.33")
    (expect-text (test-id "person-Ana-removal") "Payer on 3 expenses")
    (expect-text (test-id "trip-total") "$392.50")
    (expect-text (test-id "trip-balances-check") "$0.00")
  )
)
