(test "Split the bill — initial render"
  (steps
    ; initial render

    (expect-visible (role heading :name "Split the Bill"))
    (expect-visible (role region :name "People"))
    (expect-visible (role region :name "Expenses"))
    (expect-visible (role region :name "Settlement plan"))
    (expect-visible (role region :name "Trip totals"))
    (expect-visible (role form :name "Add person form"))
    (expect-value (label "New person name") "")
    (expect-text (test-id "person-draft-note") "Person form: enter a name")
    (expect-disabled (role button :name "Add person") true)
    (expect-visible (role form :name "Add expense form"))
    (expect-value (label "New expense description") "")
    (expect-value (label "New expense amount") "")
    (expect-value (label "New expense payer") "Ana")
    (expect-text (test-id "expense-draft-note") "Expense form: enter a description")
    (expect-disabled (role button :name "Add expense") true)
    (expect-visible (role region :name "Ana"))
    (expect-visible (role region :name "Bo"))
    (expect-visible (role region :name "Cy"))
    (expect-text (test-id "person-Ana-totals") "Totals: paid $300.00, owes $120.84")
    (expect-text (test-id "person-Ana-net") "Net: is owed $179.16")
    (expect-text (test-id "person-Ana-removal") "Removal: blocked, payer on 1 expense")
    (expect-disabled (role button :name "Remove Ana") true)
    (expect-text (test-id "person-Bo-totals") "Totals: paid $62.50, owes $132.83")
    (expect-text (test-id "person-Bo-net") "Net: owes $70.33")
    (expect-text (test-id "person-Cy-totals") "Totals: paid $24.00, owes $132.83")
    (expect-text (test-id "person-Cy-net") "Net: owes $108.83")
    (expect-visible (role region :name "Cabin"))
    (expect-value (label "Cabin amount") "300.00")
    (expect-text (test-id "expense-Cabin-status") "Status: $300.00 paid by Ana, split 3 ways")
    (expect-text (test-id "expense-Cabin-shares") "Shares: Ana $100.00, Bo $100.00, Cy $100.00")
    (expect-checked (label "Cabin includes Ana") true)
    (expect-checked (label "Cabin includes Bo") true)
    (expect-checked (label "Cabin includes Cy") true)
    ; 6250 cents over 3 people does not divide evenly: the first participant in trip
    ; order takes the leftover cent, so the shares still add back to $62.50.
    (expect-visible (role region :name "Dinner"))
    (expect-value (label "Dinner amount") "62.50")
    (expect-text (test-id "expense-Dinner-status") "Status: $62.50 paid by Bo, split 3 ways")
    (expect-text (test-id "expense-Dinner-shares") "Shares: Ana $20.84, Bo $20.83, Cy $20.83")
    ; An expense shared by a subset: Ana is not on the taxi.
    (expect-visible (role region :name "Taxi"))
    (expect-value (label "Taxi amount") "24.00")
    (expect-text (test-id "expense-Taxi-status") "Status: $24.00 paid by Cy, split 2 ways")
    (expect-text (test-id "expense-Taxi-shares") "Shares: Bo $12.00, Cy $12.00")
    (expect-checked (label "Taxi includes Ana") false)
    (expect-checked (label "Taxi includes Bo") true)
    (expect-checked (label "Taxi includes Cy") true)
    (expect-text (test-id "settlement-summary") "Settlement: 2 transfers")
    (expect-text (test-id "transfer-Cy>Ana") "Cy owes Ana $108.83")
    (expect-text (test-id "transfer-Bo>Ana") "Bo owes Ana $70.33")
    (expect-text (test-id "trip-people-count") "People on the trip: 3")
    (expect-text (test-id "trip-expense-count") "Expenses recorded: 3")
    (expect-text (test-id "trip-total") "Trip total: $386.50")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
    (expect-text (test-id "trip-summary") "People on the trip: 3 / Expenses recorded: 3 / Trip total: $386.50 / Balances check: $0.00")
  )
)
