(test "Split the bill — one person, then none"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")
    (uncheck (label "Cabin includes Cy"))
    (check (label "Cabin includes Cy"))
    (uncheck (label "Taxi includes Bo"))
    (uncheck (label "Taxi includes Cy"))
    (check (label "Taxi includes Bo"))
    (check (label "Taxi includes Cy"))
    (fill (label "New person name") "Ana")
    (fill (label "New person name") " Di ")
    (mark-metrics)
    (click (role button :name "Add person"))
    (click (role button :name "Remove Di"))
    (fill (label "New expense description") "Coffee")
    (fill (label "New expense amount") "5.00")
    (select-option (label "New expense payer") "Bo")
    (select-option (label "New expense payer") "Ana")
    (click (role button :name "Add expense"))
    (fill (label "New expense description") "Coffee")
    (fill (label "New expense description") "Snacks")
    (fill (label "New expense amount") "1.00")
    (submit (role form :name "Add expense form"))
    (click (role button :name "Remove Snacks"))
    (click (role button :name "Remove Coffee"))
    (click (role button :name "Remove Cabin"))
    (click (role button :name "Remove Dinner"))
    (click (role button :name "Remove Taxi"))

    ; one person, then none

    (click (role button :name "Remove Bo"))
    (click (role button :name "Remove Cy"))
    (expect-absent (role region :name "Bo"))
    (expect-text (test-id "trip-people-count") "People on the trip: 1")
    (expect-text (test-id "person-Ana-net") "Net: settled up")
    (expect-text (test-id "settlement-summary") "Settlement: everyone is settled up")
    (click (role button :name "Remove Ana"))
    (expect-absent (role region :name "Ana"))
    (expect-visible (text "No people yet, add someone to start."))
    (expect-text (test-id "trip-people-count") "People on the trip: 0")
    (expect-text (test-id "trip-total") "Trip total: $0.00")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
    (expect-text (test-id "settlement-summary") "Settlement: everyone is settled up")
    (expect-text (test-id "trip-summary") "People on the trip: 0 / Expenses recorded: 0 / Trip total: $0.00 / Balances check: $0.00")
    ; With nobody on the trip there is no valid payer, so the draft cannot be added.
    (fill (label "New expense description") "Ferry")
    (fill (label "New expense amount") "9.00")
    (expect-text (test-id "expense-draft-note") "Expense form: choose who paid")
    (expect-disabled (role button :name "Add expense") true)
    (fill (label "New person name") "Zed")
    (click (role button :name "Add person"))
    (expect-text (test-id "trip-people-count") "People on the trip: 1")
    (expect-text (test-id "expense-draft-note") "Expense form: choose who paid")
    (expect-disabled (role button :name "Add expense") true)
    (select-option (label "New expense payer") "Zed")
    (expect-text (test-id "expense-draft-note") "Expense form: ready to add Ferry for $9.00")
    (expect-disabled (role button :name "Add expense") false)
    (click (role button :name "Add expense"))
    (expect-visible (role region :name "Ferry"))
    (expect-text (test-id "expense-Ferry-status") "Status: $9.00 paid by Zed, split 1 way")
    (expect-text (test-id "expense-Ferry-shares") "Shares: Zed $9.00")
    (expect-text (test-id "person-Zed-net") "Net: settled up")
    (expect-text (test-id "person-Zed-removal") "Removal: blocked, payer on 1 expense")
    (expect-text (test-id "trip-total") "Trip total: $9.00")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
    (expect-text (test-id "settlement-summary") "Settlement: everyone is settled up")
    (uncheck (label "Ferry includes Zed"))
    (expect-text (test-id "expense-Ferry-status") "Status: nobody is sharing it, excluded")
    (expect-text (test-id "expense-Ferry-shares") "Shares: none")
    (expect-text (test-id "trip-total") "Trip total: $0.00")
    (expect-text (test-id "person-Zed-removal") "Removal: allowed")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
  )
)
