(test "Split the bill — removing expenses"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (fill (label "Dinner amount") "90.00")
    (fill (label "Dinner amount") "0.10")
    (fill (label "Dinner amount") "12.345")
    (fill (label "Dinner amount") "-5")
    (fill (label "Dinner amount") "")
    (fill (label "Dinner amount") "0")
    (fill (label "Dinner amount") "62.50")
    (uncheck (label "Cabin includes Cy"))
    (check (label "Cabin includes Cy"))
    (uncheck (label "Taxi includes Bo"))
    (uncheck (label "Taxi includes Cy"))
    (check (label "Taxi includes Bo"))
    (check (label "Taxi includes Cy"))
    (fill (label "New person name") "Ana")
    (fill (label "New person name") " Di ")
    (mark-metrics)
    (click (role button :name "Add person"))
    (click (role button :name "Remove Di"))
    (fill (label "New expense description") "Coffee")
    (fill (label "New expense amount") "5.00")
    (select-option (label "New expense payer") "Bo")
    (select-option (label "New expense payer") "Ana")
    (click (role button :name "Add expense"))
    (fill (label "New expense description") "Coffee")
    (fill (label "New expense description") "Snacks")
    (fill (label "New expense amount") "1.00")
    (submit (role form :name "Add expense form"))

    ; removing expenses

    (click (role button :name "Remove Snacks"))
    (expect-absent (role region :name "Snacks"))
    (click (role button :name "Remove Coffee"))
    (expect-absent (role region :name "Coffee"))
    (expect-text (test-id "trip-expense-count") "Expenses recorded: 3")
    (expect-text (test-id "trip-total") "Trip total: $386.50")
    (expect-text (test-id "transfer-Cy>Ana") "Cy owes Ana $108.83")
    (expect-text (test-id "transfer-Bo>Ana") "Bo owes Ana $70.33")
    (click (role button :name "Remove Cabin"))
    (click (role button :name "Remove Dinner"))
    (click (role button :name "Remove Taxi"))
    (expect-absent (role region :name "Cabin"))
    (expect-visible (text "No expenses yet, record what someone paid for."))
    (expect-text (test-id "trip-expense-count") "Expenses recorded: 0")
    (expect-text (test-id "trip-total") "Trip total: $0.00")
    (expect-text (test-id "trip-balances-check") "Balances check: $0.00")
    (expect-text (test-id "settlement-summary") "Settlement: everyone is settled up")
    (expect-text (test-id "person-Ana-totals") "Totals: paid $0.00, owes $0.00")
    (expect-text (test-id "person-Ana-net") "Net: settled up")
    (expect-text (test-id "person-Ana-removal") "Removal: allowed")
    (expect-disabled (role button :name "Remove Ana") false)
  )
)
