(test "Recipe scaler — Initial mount"
  (steps
    ; Initial mount

    (expect-visible (role heading :name "Recipe Scaler"))
    (expect-visible (role region :name "Scaling controls"))
    (expect-visible (role region :name "Scale summary"))
    (expect-visible (role region :name "Ingredients"))
    (expect-visible (role region :name "Shopping list"))
    (expect-value (label "Recipe") "pancakes")
    (expect-value (label "Target servings") "4")
    (expect-value (label "Pan size") "recipe")
    (expect-checked (label "Scale by servings") true)
    (expect-checked (label "Scale by pan size") false)
    (expect-checked (label "Metric units") true)
    (expect-checked (label "Imperial units") false)
    (expect-checked (label "Include Buttermilk Pancakes") false)
    (expect-checked (label "Include Roasted Tomato Soup") false)
    (expect-checked (label "Include Seeded Bread Loaf") false)
    (expect-text (test-id "effective-servings") "Effective servings: 4")
    (expect-text (test-id "scale-note") "Unscaled: this is the recipe as printed.")
    (expect-text (test-id "unit-system") "Units: metric (tsp and pinch are unchanged)")
    (expect-text (test-id "controls-summary") "Controls: pancakes / servings / recipe / metric")
    (expect-text (test-id "recipe-title") "Buttermilk Pancakes")
    (expect-text (test-id "ing-name-flour") "Plain flour")
    (expect-text (test-id "ing-qty-flour") "200 g")
    (expect-text (test-id "ing-name-buttermilk") "Buttermilk")
    (expect-text (test-id "ing-qty-buttermilk") "300 ml")
    (expect-text (test-id "ing-name-butter") "Butter")
    (expect-text (test-id "ing-qty-butter") "50 g")
    (expect-text (test-id "ing-name-baking-powder") "Baking powder")
    (expect-text (test-id "ing-qty-baking-powder") "2 tsp")
    (expect-text (test-id "ing-name-salt") "Salt")
    (expect-text (test-id "ing-qty-salt") "1 pinch")
    ; Empty shopping list.
    (expect-text (test-id "shopping-count") "Shopping list: 0 lines from 0 recipes")
    (expect-visible (test-id "shopping-empty"))
    (expect-absent (test-id "shopping-rows"))
  )
)
