(test "Field notes — filtering hides synced rows without touching the others"
  (setup
    (manual-effects)
    (initial-online online)
    ; Three queued notes will settle; the fourth remains an unsynced draft.
    (local-storage "field-notes:notes" "n0|0|1|r7|Generator hours 128;n1|1|1|r7|Fence line check;n2|2|1|r7|Pump pressure log;n3|3|0|r7|Unsynced draft")
  )
  (steps
    (stub-http "first note synced" :url "/api/notes/sync" :status 200 :body "n0#r7")
    (run-effect 1)
    (stub-http "second note synced" :url "/api/notes/sync" :status 200 :body "n1#r7")
    (run-effect 2)
    (stub-http "third note synced" :url "/api/notes/sync" :status 200 :body "n2#r7")
    (run-effect 3)
    (expect-pending-effects 0)

    (mark-metrics)
    (check (label "Hide synced notes"))
    (expect-metric-delta rows_removed 3)
    (expect-metric-delta rows_created 0)
    (expect-absent (role region :name "Note n0"))
    (expect-absent (role region :name "Note n1"))
    (expect-absent (role region :name "Note n2"))
    (expect-text (test-id "synced-count") "3")
    (expect-visible (role region :name "Note n3"))
    (expect-value (label "Body n3") "Unsynced draft")
    (uncheck (label "Hide synced notes"))
    (expect-visible (role region :name "Note n0"))
    (expect-visible (role region :name "Note n1"))
    (expect-visible (role region :name "Note n2"))
    (expect-value (label "Body n0") "Generator hours 128")
  )
)
