(test "Field notes — pausing auto sync, then deleting a queued note"
  (setup
    (manual-effects)
    (initial-online online)
    ; Drain three notes, leaving room for one new note while sync is paused.
    (local-storage "field-notes:notes" "n0|0|1|r7|Generator hours;n1|1|1|r7|Fence line check;n2|2|1|r7|Pump pressure log")
  )
  (steps
    (stub-http "first note synced" :url "/api/notes/sync" :status 200 :body "n0#r7")
    (run-effect 1)
    (stub-http "second note synced" :url "/api/notes/sync" :status 200 :body "n1#r7")
    (run-effect 2)
    (stub-http "third note synced" :url "/api/notes/sync" :status 200 :body "n2#r7")
    (run-effect 3)

    (uncheck (label "Sync automatically"))
    (expect-checked (label "Sync automatically") false)
    (expect-text (test-id "auto-sync") "Auto sync paused")
    (expect-text (test-id "capacity") "3 of 4")
    (expect-text (test-id "synced-count") "3")
    (fill (label "Note body") "Radio check")
    (click (role button :name "Save note"))
    (expect-visible (role region :name "Note s1"))
    (expect-value (label "Body s1") "Radio check")
    (expect-text (test-id "capacity") "Full")
    (click (role button :name "Queue note s1"))
    (expect-text (test-id "status-s1") "Queued")
    (expect-text (test-id "outbox-count") "1")
    (expect-text (test-id "syncing") "None")
    (expect-pending-effects 0)
    (click (role button :name "Delete note s1"))
    (expect-absent (role region :name "Note s1"))
    (expect-text (test-id "outbox-count") "0")
    (expect-visible (text "Outbox is empty"))
    (expect-text (test-id "capacity") "3 of 4")
    (expect-pending-effects 0)
    (check (label "Sync automatically"))
    (expect-text (test-id "auto-sync") "Auto sync on")
    (expect-pending-effects 0)
  )
)
