(test "Reusable state updaters read the latest value and survive producer disposal"
  (steps
    (click (role button :name "Append event"))
    (click (role button :name "Append event"))
    (expect-text (test-id "history") "event;event;")
    (mark-metrics)
    (click (role button :name "Unchanged history"))
    (expect-metric-delta derived_calls_into_roc 0)
    (expect-metric-delta set_text 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (click (role button :name "Toggle history clock"))
    (tick-interval 250)
    (tick-interval 250)
    (expect-text (test-id "history") "event;event;event;event;")
    (click (role button :name "Toggle history clock"))
    (expect-text (test-id "history") "event;event;event;event;")
    (click (role button :name "Toggle history clock"))
    (tick-interval 250)
    (expect-text (test-id "history") "event;event;event;event;event;")
    (click (role button :name "Append event"))
    (expect-text (test-id "history") "event;event;event;event;event;event;")))
