(test "Dependency scheduler — filtering the list to the critical path"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Delay Write spec"))
    (click (role button :name "Pull in Write spec"))
    (mark-metrics)
    (click (role button :name "Delay Write docs"))
    (click (role button :name "Pull in Write docs"))
    (mark-metrics)
    (click (role button :name "Pull in Write docs"))
    (select-option (label "Focus task") "ui")
    (click (role button :name "Extend Build UI"))
    (click (role button :name "Extend Build UI"))
    (click (role button :name "Shorten Build UI"))
    (click (role button :name "Shorten Build UI"))
    (click (role button :name "Extend Launch"))
    (click (role button :name "Shorten Launch"))
    (click (role button :name "Shorten Launch"))
    (mark-metrics)
    (check (label "QA pass after Write docs"))
    (uncheck (label "QA pass after Write docs"))
    (mark-metrics)
    (check (label "Write spec after Launch"))
    (uncheck (label "Write spec after Launch"))

    ; filtering the list to the critical path

    (mark-metrics)
    (check (label "Only critical path"))
    (expect-metric-delta rows_removed 2)
    (expect-metric-delta rows_reused 5)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta scopes_disposed 2)
    (expect-metric-delta create_element 0)
    (expect-text (test-id "filter-state") "Showing critical-path tasks only, 5 rows, plan order")
    (expect-absent (role region :name "Task Build UI"))
    (expect-absent (role region :name "Task Write docs"))
    (expect-visible (role region :name "Task Write spec"))
    (expect-visible (role region :name "Task Launch"))
    (mark-metrics)
    (uncheck (label "Only critical path"))
    (expect-metric-delta rows_created 2)
    (expect-metric-delta rows_reused 5)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 2)
    (expect-metric-delta scopes_disposed 0)
    (expect-text (test-id "filter-state") "Showing all tasks, 7 rows, plan order")
    (expect-visible (role region :name "Task Build UI"))
    (expect-visible (role region :name "Task Write docs"))
    (expect-text (test-id "line-ui") "Build UI: day 2 to 5, 3 days, after spec, slack 1 day")
  )
)
