(test "Dependency scheduler — initial render"
  (steps
    ; initial render

    (expect-visible (role heading :name "Dependency Scheduler"))
    (expect-visible (role region :name "Project summary"))
    (expect-visible (role region :name "Schedule"))
    (expect-visible (role region :name "Plan health"))
    (expect-absent (role region :name "Cycle report"))
    (expect-visible (role heading :name "Schedule"))
    (expect-visible (role heading :name "Project summary"))
    (expect-text (test-id "project-summary") "Project finishes on day 10 across 7 tasks")
    (expect-text (test-id "critical-path") "Critical path: Write spec -> Build API -> Integrate -> QA pass -> Launch")
    (expect-text (test-id "focus-detail") "Focus Build UI: earliest start day 2, latest start day 3, slack 1 day, moved 0 days")
    (expect-text (test-id "filter-state") "Showing all tasks, 7 rows, plan order")
    (expect-value (label "Focus task") "ui")
    (expect-checked (label "Only critical path") false)
    (expect-checked (label "Sort by slack") false)
    (expect-visible (role region :name "Task Write spec"))
    (expect-visible (role region :name "Task Build API"))
    (expect-visible (role region :name "Task Build UI"))
    (expect-visible (role region :name "Task Write docs"))
    (expect-visible (role region :name "Task Integrate"))
    (expect-visible (role region :name "Task QA pass"))
    (expect-visible (role region :name "Task Launch"))
    (expect-text (test-id "line-spec") "Write spec: day 0 to 2, 2 days, after none, critical")
    (expect-text (test-id "line-api") "Build API: day 2 to 6, 4 days, after spec, critical")
    (expect-text (test-id "line-ui") "Build UI: day 2 to 5, 3 days, after spec, slack 1 day")
    (expect-text (test-id "line-docs") "Write docs: day 2 to 3, 1 day, after spec, slack 7 days")
    (expect-text (test-id "line-sync") "Integrate: day 6 to 8, 2 days, after api+ui, critical")
    (expect-text (test-id "line-qa") "QA pass: day 8 to 10, 2 days, after sync, critical")
    (expect-text (test-id "line-launch") "Launch: day 10 to 10, milestone, after qa, critical")
    (expect-attr (test-id "row-spec") data-tone "critical")
    (expect-attr (test-id "row-ui") data-tone "slack")
    (expect-attr (test-id "row-docs") data-tone "slack")
    (expect-attr (test-id "row-launch") data-tone "critical")
    ; The dependency matrix reflects the stored edges.
    (expect-checked (label "Build API after Write spec") true)
    (expect-checked (label "Build API after Build UI") false)
    (expect-checked (label "Integrate after Build API") true)
    (expect-checked (label "Integrate after Build UI") true)
    (expect-checked (label "Write spec after Launch") false)
  )
)
