(test "Dependency scheduler — the empty list"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Delay Write spec"))
    (click (role button :name "Pull in Write spec"))
    (mark-metrics)
    (click (role button :name "Delay Write docs"))
    (click (role button :name "Pull in Write docs"))
    (mark-metrics)
    (click (role button :name "Pull in Write docs"))
    (select-option (label "Focus task") "ui")
    (click (role button :name "Extend Build UI"))
    (click (role button :name "Extend Build UI"))
    (click (role button :name "Shorten Build UI"))
    (click (role button :name "Shorten Build UI"))
    (click (role button :name "Extend Launch"))
    (click (role button :name "Shorten Launch"))
    (click (role button :name "Shorten Launch"))
    (mark-metrics)
    (check (label "QA pass after Write docs"))
    (uncheck (label "QA pass after Write docs"))
    (mark-metrics)
    (check (label "Write spec after Launch"))
    (uncheck (label "Write spec after Launch"))
    (mark-metrics)
    (check (label "Only critical path"))
    (mark-metrics)
    (uncheck (label "Only critical path"))
    (select-option (label "Focus task") "launch")
    (select-option (label "Focus task") "docs")
    (mark-metrics)
    (check (label "Sort by slack"))
    (uncheck (label "Sort by slack"))

    ; the empty list
    ;
    ; While the plan is cyclic nothing is critical, so filtering to the critical
    ; path leaves an empty keyed list.

    (check (label "Write spec after Launch"))
    (expect-visible (role region :name "Cycle report"))
    (mark-metrics)
    (check (label "Only critical path"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 0)
    (expect-metric-delta rows_removed 7)
    (expect-metric-delta scopes_disposed 7)
    (expect-text (test-id "filter-state") "Showing critical-path tasks only, 0 rows, plan order")
    (expect-absent (role region :name "Task Write spec"))
    (expect-absent (role region :name "Task Launch"))
    (expect-text (test-id "critical-path") "Critical path: none")
    ; Widening the filter repopulates the list from an empty starting point.
    (mark-metrics)
    (uncheck (label "Only critical path"))
    (expect-metric-delta rows_created 7)
    (expect-metric-delta rows_reused 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 7)
    (expect-text (test-id "filter-state") "Showing all tasks, 7 rows, plan order")
    (expect-visible (role region :name "Task Write spec"))
    (expect-visible (role region :name "Task Build UI"))
    (expect-text (test-id "line-spec") "Write spec: unscheduled while the plan is cyclic, 2 days, after launch")
    (uncheck (label "Write spec after Launch"))
    (expect-absent (role region :name "Cycle report"))
    (expect-text (test-id "line-ui") "Build UI: day 2 to 5, 3 days, after spec, slack 1 day")
    (expect-text (test-id "project-summary") "Project finishes on day 10 across 7 tasks")
  )
)
