(test "Dependency scheduler — the focus readout is an independent source feeding the same solve"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Delay Write spec"))
    (click (role button :name "Pull in Write spec"))
    (mark-metrics)
    (click (role button :name "Delay Write docs"))
    (click (role button :name "Pull in Write docs"))
    (mark-metrics)
    (click (role button :name "Pull in Write docs"))
    (select-option (label "Focus task") "ui")
    (click (role button :name "Extend Build UI"))
    (click (role button :name "Extend Build UI"))
    (click (role button :name "Shorten Build UI"))
    (click (role button :name "Shorten Build UI"))
    (click (role button :name "Extend Launch"))
    (click (role button :name "Shorten Launch"))
    (click (role button :name "Shorten Launch"))
    (mark-metrics)
    (check (label "QA pass after Write docs"))
    (uncheck (label "QA pass after Write docs"))
    (mark-metrics)
    (check (label "Write spec after Launch"))
    (uncheck (label "Write spec after Launch"))
    (mark-metrics)
    (check (label "Only critical path"))
    (mark-metrics)
    (uncheck (label "Only critical path"))

    ; the focus readout is an independent source feeding the same solve

    (select-option (label "Focus task") "launch")
    (expect-value (label "Focus task") "launch")
    (expect-text (test-id "focus-detail") "Earliest day 10 · latest day 10 · slack 0 days · moved 0 days")
    (expect-text (test-id "project-summary") "10 days")
    (select-option (label "Focus task") "docs")
    (expect-text (test-id "focus-detail") "Earliest day 2 · latest day 9 · slack 7 days · moved 0 days")
  )
)
