(test "Package explorer — G. Back and Forward"
  (setup
    ; A. deep link

    (initial-location "/packages/roc-json")
  )
  (steps
    ; Given the state established by earlier scenarios
    (click (role link :name "Back to search"))
    (resolve-task "search" "roc-json|JSON codec for Roc;roc-http|HTTP client for Roc;roc-parser|Parser combinators for Roc")
    (fill (label "Search packages") "js")
    (fill (label "Search packages") "json")
    (mark-metrics)
    (resolve-stale-task "search" "stale-package|This superseded payload must never render")
    (resolve-task "search" "roc-json|JSON codec for Roc")
    (fill (label "Search packages") "zzzz")
    (resolve-task "search" "")
    (fill (label "Search packages") "boom")
    (reject-task "search" "registry unreachable")
    (fill (label "Search packages") "roc")
    (resolve-task "search" "roc-json|JSON codec for Roc;roc-http|HTTP client for Roc;roc-parser|Parser combinators for Roc")
    (mark-metrics)
    (check (label "Reverse order"))
    (mark-metrics)
    (click (role button :name "Watch roc-http"))
    (click (role button :name "Watch roc-parser"))
    (uncheck (label "Reverse order"))
    (fill (label "Search packages") "roc core")
    (resolve-task "search" "roc-json|JSON codec for Roc;roc-parser|Parser combinators for Roc;roc-bytes|Byte helpers for Roc")
    (fill (label "Search packages") "roc core ")
    (resolve-task "search" "roc-json|JSON codec for Roc, revised;roc-parser|Parser combinators for Roc;roc-bytes|Byte helpers for Roc")
    (click (role link :name "Open roc-json"))
    (resolve-task "versions" "1.2.0|2026-05-02;1.1.0|2026-03-14;1.0.0|2026-01-09")
    (mark-metrics)
    (resolve-task "deps" "roc-parser|0.4.0;roc-bytes|1.1.0")
    (reject-task "detail" "overview service unavailable")

    ; G. Back and Forward

    (history-back)
    (expect-current-location "/")
    (expect-document-title "Package Explorer")
    (expect-visible (role region :name "Package search"))
    (expect-absent (role region :name "Package detail"))
    (expect-text (test-id "search-status") "Search status: 3 packages")
    (expect-text (test-id "context") "Context: search results (3 matches)")
    (expect-cleanup "package detail panels" 2)
    (expect-canceled-task "detail" 1)
    (history-forward)
    (expect-current-location "/packages/roc-json")
    (expect-document-title "roc-json - Package Explorer")
    (expect-visible (role region :name "Package detail"))
    (expect-text (test-id "package-id") "Package: roc-json")
    (expect-text (test-id "panel-summary") "Panels: 0 ready, 3 loading, 0 failed")
    (expect-pending-task "detail" 1)
    (expect-pending-task "versions" 1)
    (expect-pending-task "deps" 1)
    ; The overview succeeds this time; every field is derived from one payload.
    (resolve-task "detail" "roc-json|JSON codec for Roc|Apache-2.0|18422")
    (expect-text (test-id "overview-status") "Overview: ready")
    (expect-text (test-id "overview-summary") "Summary: JSON codec for Roc")
    (expect-text (test-id "overview-license") "License: Apache-2.0")
    (expect-text (test-id "overview-downloads") "Downloads: 18422")
    (expect-absent (test-id "overview-empty"))
    (expect-text (test-id "panel-summary") "Panels: 1 ready, 2 loading, 0 failed")
    ; A package with nothing published and nothing depended on: both empty branches.
    (resolve-task "versions" "")
    (resolve-task "deps" "")
    (expect-text (test-id "versions-status") "Versions: none published")
    (expect-text (test-id "versions-empty") "No versions published yet.")
    (expect-text (test-id "deps-status") "Dependencies: none")
    (expect-text (test-id "deps-empty") "This package has no dependencies.")
    (expect-text (test-id "panel-summary") "Panels: 3 ready, 0 loading, 0 failed")
    (expect-visible (text "All panels settled."))
    (history-back)
    (expect-current-location "/")
    (expect-visible (role region :name "Package search"))
    (expect-cleanup "package detail panels" 3)
  )
)
