(test "Signal select 128"
  (steps
    ; Generated by examples/_fixtures/generate_signal_select.py --rows 128
    ; Only the old and new selector members may be dirtied at this size.
    (expect-checked (label "Selected row-000") true)
    (expect-checked (label "Selected row-127") false)
    (mark-metrics)
    (click (role button :name "Select row-127"))
    (expect-checked (label "Selected row-000") false)
    (expect-checked (label "Selected row-127") true)
    (expect-metric-delta selector_members_dirtied 2)
    (expect-metric-delta derived_calls_into_roc 0)
    ; Removing and recreating scopes must update the selector index without
    ; retaining stale member records.
    (click (role button :name "Show one row"))
    (expect-absent (label "Selected row-127"))
    (click (role button :name "Show all rows"))
    (expect-checked (label "Selected row-127") true)
    (click (role button :name "Select row-000"))
    (expect-checked (label "Selected row-000") true)
    (expect-checked (label "Selected row-127") false)
  )
)
