(test "Status page — First incident arrives, with three updates in publish order"
  (setup (manual-effects))
  (steps
    ; Given the state established by earlier scenarios
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 1)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 2)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 3)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 4)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 5)
    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "degraded|97.40")
    (run-effect 6)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 7)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 8)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 9)

    ; First incident arrives, with three updates in publish order

    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (run-effect 10)
    (expect-text (test-id "open-incident-count") "1")
    (expect-absent (text "No incidents reported in the last 90 days."))
    (expect-visible (role region :name "Incident inc-42"))
    (expect-text (test-id "incident-inc-42-severity") "Major")
    (expect-text (test-id "incident-inc-42-title") "Elevated API error rate")
    (expect-text (test-id "incident-inc-42-latest") "10:45 - Monitoring after rollback")
    (expect-visible (role region :name "inc-42#1"))
    (expect-visible (role region :name "inc-42#2"))
    (expect-visible (role region :name "inc-42#3"))
    ; The update row shows the timestamp in its own column beside the body.
    (expect-visible (text "10:02"))
    (expect-text (test-id "update-inc-42#1") "Investigating elevated 5xx responses")
    (expect-text (test-id "update-inc-42#2") "Identified a bad deploy")
    (expect-text (test-id "update-inc-42#3") "Monitoring after rollback")
  )
)
