(test "Status page — Hiding the page stops polling"
  (steps
    ; Given the state established by earlier scenarios
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "")
    (tick-interval 5000)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (tick-interval 5000)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "degraded|98.10")
    (resolve-task "check:database" "degraded|96.00")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~minor~Delayed notification delivery~11:10@Investigating a backlog")
    (tick-interval 5000)
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "outage|82.50")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation")
    (tick-interval 5000)
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation#inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (tick-interval 5000)
    (reject-task "check:notifications" "gateway timeout")
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (mark-metrics)
    (resolve-task "incidents" "")
    (tick-interval 5000)
    (tick-interval 5000)
    (mark-metrics)
    (resolve-stale-task "check:api" "outage|10.00")
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "")

    ; Hiding the page stops polling

    (tick-interval 5000)
    (expect-pending-task "check:api" 1)
    (set-visibility hidden)
    (expect-text (test-id "refresh-mode") "Auto refresh paused while the page is hidden")
    (expect-interval 5000 0)
    (expect-pending-task "check:api" 0)
    (expect-pending-task "check:web" 0)
    (expect-pending-task "check:database" 0)
    (expect-pending-task "check:notifications" 0)
    (expect-pending-task "incidents" 0)
    (tick-interval-if-active 5000)
    (expect-pending-task "check:api" 0)
    (expect-text (test-id "overall-rollup") "All systems operational")
    ; Manual refresh still works while hidden; it is not gated on visibility.
    (click (role button :name "Refresh now"))
    (expect-text (test-id "refresh-count") "Refreshes requested: 1")
    (expect-pending-task "check:api" 1)
    (expect-pending-task "incidents" 1)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "")
    (expect-text (test-id "overall-rollup") "Degraded performance")
    (expect-interval 5000 0)
  )
)
