(test "Status page — Initial mount"
  (steps
    ; Initial mount

    (expect-visible (role heading :name "Acme Cloud Status"))
    (expect-visible (role region :name "Overall status"))
    (expect-visible (role region :name "Services"))
    (expect-visible (role region :name "API"))
    (expect-visible (role region :name "Web app"))
    (expect-visible (role region :name "Database"))
    (expect-visible (role region :name "Notifications"))
    (expect-visible (role region :name "Incidents"))
    (expect-visible (role region :name "Incident timeline"))
    (expect-text (test-id "overall-rollup") "Checking services")
    ; `status-breakdown` is the metric grid itself; the four counts it used to
    ; spell out as one sentence are the four metrics inside it.
    (expect-visible (test-id "status-breakdown"))
    (expect-text (test-id "count-operational") "0")
    (expect-text (test-id "count-degraded") "0")
    (expect-text (test-id "count-outage") "0")
    (expect-text (test-id "count-awaiting") "4")
    (expect-text (test-id "overall-uptime") "not reported")
    (expect-text (test-id "refresh-mode") "Auto refresh every 5s")
    (expect-text (test-id "refresh-count") "Refreshes requested: 0")
    (expect-text (test-id "service-api-status") "Awaiting first check")
    (expect-text (test-id "service-api-uptime") "not reported")
    (expect-text (test-id "service-web-status") "Awaiting first check")
    (expect-text (test-id "service-database-status") "Awaiting first check")
    (expect-text (test-id "service-notifications-status") "Awaiting first check")
    (expect-text (test-id "incident-feed-status") "Incident feed: loading")
    (expect-text (test-id "open-incident-count") "0")
    (expect-visible (text "No incidents reported in the last 90 days."))
    (expect-interval 5000 1)
    (expect-pending-task "check:api" 1)
    (expect-pending-task "check:web" 1)
    (expect-pending-task "check:database" 1)
    (expect-pending-task "check:notifications" 1)
    (expect-pending-task "incidents" 1)
    (expect-cleanup "status page cleanup" 0)
  )
)
