(test "Status page — One service degrades; the rollup follows"
  (setup (manual-effects))
  (steps
    ; Given the state established by earlier scenarios
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 1)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 2)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 3)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 4)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 5)

    ; One service degrades; the rollup follows

    (tick-interval 5000)
    (expect-pending-effects 5)
    (stub-http "api" :url "/api/status/api" :status 200 :body "degraded|97.40")
    (run-effect 6)
    (expect-text (test-id "service-api-status") "Degraded")
    (expect-text (test-id "service-api-uptime") "97.40%")
    (expect-text (test-id "overall-rollup") "Degraded performance")
    (expect-text (test-id "count-operational") "3")
    (expect-text (test-id "count-degraded") "1")
    (expect-text (test-id "count-outage") "0")
    (expect-text (test-id "count-awaiting") "0")
    (expect-text (test-id "service-web-status") "Operational")
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 7)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 8)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 9)
    (expect-text (test-id "overall-rollup") "Degraded performance")
    (expect-text (test-id "overall-uptime") "99.31%")
  )
)
