(test "Status page — Recovery, and reordering the timeline"
  (setup (manual-effects))
  (steps
    ; Given the state established by earlier scenarios
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 1)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 2)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 3)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 4)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 5)
    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "degraded|97.40")
    (run-effect 6)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 7)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 8)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 9)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (run-effect 10)
    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "degraded|97.40")
    (run-effect 11)
    (stub-http "web" :url "/api/status/web" :status 200 :body "degraded|98.10")
    (run-effect 12)
    (stub-http "database" :url "/api/status/database" :status 200 :body "degraded|96.00")
    (run-effect 13)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 14)
    (mark-metrics)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~minor~Delayed notification delivery~11:10@Investigating a backlog")
    (run-effect 15)
    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 16)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 17)
    (stub-http "database" :url "/api/status/database" :status 200 :body "outage|82.50")
    (run-effect 18)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 19)
    (mark-metrics)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation")
    (run-effect 20)

    ; Recovery, and reordering the timeline

    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 21)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 22)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 23)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 24)
    (expect-text (test-id "overall-rollup") "All systems operational")
    (expect-text (test-id "count-operational") "4")
    (expect-text (test-id "count-degraded") "0")
    (expect-text (test-id "count-outage") "0")
    (expect-text (test-id "count-awaiting") "0")
    (expect-text (test-id "overall-uptime") "99.95%")
    (expect-text (test-id "service-database-status") "Operational")
    (mark-metrics)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation#inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (run-effect 25)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 2)
    (expect-metric-delta rows_removed 0)
    (expect-text (test-id "open-incident-count") "2")
    (expect-visible (role region :name "Incident inc-42"))
    (expect-visible (role region :name "Incident inc-51"))
  )
)
