(test "Status page — Returning to visible resumes polling"
  (setup (manual-effects))
  (steps
    ; Establish a healthy board; mount effects 1–5 each answer once.
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 1)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 2)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 3)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 4)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 5)
    ; Queue the first timed refresh (effects 6–10), then hide before it runs.
    (tick-interval 5000)
    (set-visibility hidden)
    (expect-interval 5000 0)
    (expect-pending-effects 5)


    ; Returning to visible resumes polling

    ; Becoming visible admits a fresh refresh (effects 11–15).
    (set-visibility visible)
    (expect-text (test-id "refresh-mode") "Auto refresh every 5s")
    (expect-interval 5000 1)
    (expect-pending-effects 10)
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 11)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 12)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 13)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 14)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 15)
    (expect-text (test-id "overall-rollup") "All systems operational")
    (expect-text (test-id "overall-uptime") "99.95%")
    ; The pre-hide occurrence survives, but cannot overwrite the newer result.
    (mark-metrics)
    (stub-http "late pre-hide api" :url "/api/status/api" :status 200 :body "outage|10.00")
    (run-effect 6)
    (expect-metric-delta patches_emitted 0)
    (expect-text (test-id "service-api-status") "Operational")
    (expect-text (test-id "service-api-uptime") "99.98%")
    (expect-pending-effects 4)
    (tick-interval 5000)
    (expect-pending-effects 9)
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 16)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 17)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 18)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 19)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 20)
    ; A service degrading patches only its own card: no rows, no new scopes.
    (mark-metrics)
    (tick-interval 5000)
    (stub-http "database" :url "/api/status/database" :status 200 :body "degraded|96.00")
    (run-effect 23)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta scopes_created 0)
    (expect-text (test-id "service-database-status") "Degraded")
    (expect-text (test-id "overall-rollup") "Degraded performance")
    (expect-text (test-id "service-api-status") "Operational")
    (expect-text (test-id "service-web-status") "Operational")
  )
)
