(test "Status page — Several services degrade: the rollup escalates to a major outage"
  (setup (manual-effects))
  (steps
    ; Given the state established by earlier scenarios
    (stub-http "api" :url "/api/status/api" :status 200 :body "operational|99.98")
    (run-effect 1)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 2)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 3)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 4)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "")
    (run-effect 5)
    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "degraded|97.40")
    (run-effect 6)
    (stub-http "web" :url "/api/status/web" :status 200 :body "operational|99.99")
    (run-effect 7)
    (stub-http "database" :url "/api/status/database" :status 200 :body "operational|99.90")
    (run-effect 8)
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 9)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (run-effect 10)

    ; Several services degrade: the rollup escalates to a major outage

    (tick-interval 5000)
    (stub-http "api" :url "/api/status/api" :status 200 :body "degraded|97.40")
    (run-effect 11)
    (stub-http "web" :url "/api/status/web" :status 200 :body "degraded|98.10")
    (run-effect 12)
    (expect-text (test-id "overall-rollup") "Degraded performance")
    (stub-http "database" :url "/api/status/database" :status 200 :body "degraded|96.00")
    (run-effect 13)
    (expect-text (test-id "overall-rollup") "Major outage")
    (expect-text (test-id "count-operational") "1")
    (expect-text (test-id "count-degraded") "3")
    (expect-text (test-id "count-outage") "0")
    (expect-text (test-id "count-awaiting") "0")
    (stub-http "notifications" :url "/api/status/notifications" :status 200 :body "operational|99.95")
    (run-effect 14)
    (expect-text (test-id "overall-rollup") "Major outage")
    (expect-text (test-id "overall-uptime") "97.86%")
    ; Adding a second incident creates its incident row plus its single update row.
    ; The untouched incident is reused and its three update rows are never revisited.
    (mark-metrics)
    (stub-http "incidents" :url "/api/status/incidents" :status 200 :body "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~minor~Delayed notification delivery~11:10@Investigating a backlog")
    (run-effect 15)
    (expect-metric-delta rows_created 2)
    (expect-metric-delta rows_reused 1)
    (expect-metric-delta rows_removed 0)
    (expect-text (test-id "open-incident-count") "2")
    (expect-visible (role region :name "Incident inc-51"))
    (expect-text (test-id "incident-inc-51-severity") "Minor")
    (expect-text (test-id "incident-inc-51-latest") "11:10 - Investigating a backlog")
  )
)
