(test "Location source"
  (setup
    (initial-location "/services/api?tab=logs#tail")
  )
  (steps
    (expect-visible (text "Location Source"))
    (expect-text (text "Path: /services/api") "Path: /services/api")
    (expect-text (text "Query: tab=logs") "Query: tab=logs")
    (expect-text (text "Hash: tail") "Hash: tail")
    (expect-current-location "/services/api?tab=logs#tail")
    (navigate "/services/web?tab=deploys#events")
    (expect-text (text "Path: /services/web") "Path: /services/web")
    (expect-text (text "Query: tab=deploys") "Query: tab=deploys")
    (expect-text (text "Hash: events") "Hash: events")
    (expect-current-location "/services/web?tab=deploys#events")
    (history-back)
    (expect-text (text "Path: /services/api") "Path: /services/api")
    (expect-text (text "Query: tab=logs") "Query: tab=logs")
    (expect-text (text "Hash: tail") "Hash: tail")
    (expect-current-location "/services/api?tab=logs#tail")
    (history-forward)
    (expect-text (text "Path: /services/web") "Path: /services/web")
    (expect-text (text "Query: tab=deploys") "Query: tab=deploys")
    (expect-text (text "Hash: events") "Hash: events")
    (expect-current-location "/services/web?tab=deploys#events")
  )
)
