(test "Status page — Initial mount"
  (steps
    ; Initial mount

    (expect-visible (role heading :name "Status Page"))
    (expect-visible (role region :name "Overall status"))
    (expect-visible (role region :name "Services"))
    (expect-visible (role region :name "API"))
    (expect-visible (role region :name "Web app"))
    (expect-visible (role region :name "Database"))
    (expect-visible (role region :name "Notifications"))
    (expect-visible (role region :name "Incidents"))
    (expect-visible (role region :name "Incident timeline"))
    (expect-text (test-id "overall-rollup") "Checking services")
    (expect-text (test-id "status-breakdown") "Operational 0, degraded 0, outage 0, awaiting 4")
    (expect-text (test-id "overall-uptime") "Overall uptime: not reported")
    (expect-text (test-id "refresh-mode") "Auto refresh every 5s")
    (expect-text (test-id "refresh-count") "Refreshes requested: 0")
    (expect-text (test-id "service-api-status") "API status: awaiting first check")
    (expect-text (test-id "service-api-uptime") "API uptime: not reported")
    (expect-text (test-id "service-web-status") "Web app status: awaiting first check")
    (expect-text (test-id "service-database-status") "Database status: awaiting first check")
    (expect-text (test-id "service-notifications-status") "Notifications status: awaiting first check")
    (expect-text (test-id "incident-feed-status") "Incident feed: loading")
    (expect-text (test-id "open-incident-count") "Open incidents: 0")
    (expect-visible (text "No incidents reported"))
    (expect-interval 5000 1)
    (expect-pending-task "check:api" 1)
    (expect-pending-task "check:web" 1)
    (expect-pending-task "check:database" 1)
    (expect-pending-task "check:notifications" 1)
    (expect-pending-task "incidents" 1)
    (expect-cleanup "status page cleanup" 0)
  )
)
