(test "Status page — One refresh fails while the others succeed"
  (steps
    ; Given the state established by earlier scenarios
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "")
    (tick-interval 5000)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (tick-interval 5000)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "degraded|98.10")
    (resolve-task "check:database" "degraded|96.00")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~minor~Delayed notification delivery~11:10@Investigating a backlog")
    (tick-interval 5000)
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "outage|82.50")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation")
    (tick-interval 5000)
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation#inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")

    ; One refresh fails while the others succeed

    (tick-interval 5000)
    (reject-task "check:notifications" "gateway timeout")
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (expect-text (test-id "service-notifications-status") "Notifications status: check failed (gateway timeout)")
    (expect-text (test-id "service-notifications-uptime") "Notifications uptime: not reported")
    (expect-text (test-id "overall-rollup") "Degraded performance")
    (expect-text (test-id "status-breakdown") "Operational 3, degraded 1, outage 0, awaiting 0")
    (expect-text (test-id "overall-uptime") "Overall uptime: 99.95%")
    (expect-text (test-id "service-api-status") "API status: operational")
    ; An empty incident payload clears the timeline back to the empty state. The
    ; `Ui.when` arm flips, so the whole keyed list scope is disposed rather than the
    ; rows being removed one at a time.
    (mark-metrics)
    (resolve-task "incidents" "")
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta scopes_disposed 8)
    (expect-text (test-id "open-incident-count") "Open incidents: 0")
    (expect-visible (text "No incidents reported"))
    (expect-absent (role region :name "Incident inc-42"))
    (expect-absent (role region :name "Incident inc-51"))
  )
)
