(test "Status page — Recovery, and reordering the timeline"
  (steps
    ; Given the state established by earlier scenarios
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "")
    (tick-interval 5000)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (tick-interval 5000)
    (resolve-task "check:api" "degraded|97.40")
    (resolve-task "check:web" "degraded|98.10")
    (resolve-task "check:database" "degraded|96.00")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~minor~Delayed notification delivery~11:10@Investigating a backlog")
    (tick-interval 5000)
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "outage|82.50")
    (resolve-task "check:notifications" "operational|99.95")
    (mark-metrics)
    (resolve-task "incidents" "inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback#inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation")

    ; Recovery, and reordering the timeline

    (tick-interval 5000)
    (resolve-task "check:api" "operational|99.98")
    (resolve-task "check:web" "operational|99.99")
    (resolve-task "check:database" "operational|99.90")
    (resolve-task "check:notifications" "operational|99.95")
    (expect-text (test-id "overall-rollup") "All systems operational")
    (expect-text (test-id "count-operational") "4")
    (expect-text (test-id "count-degraded") "0")
    (expect-text (test-id "count-outage") "0")
    (expect-text (test-id "count-awaiting") "0")
    (expect-text (test-id "overall-uptime") "99.95%")
    (expect-text (test-id "service-database-status") "Operational")
    (mark-metrics)
    (resolve-task "incidents" "inc-51~major~Delayed notification delivery~11:10@Investigating a backlog^11:40@Identified queue saturation#inc-42~major~Elevated API error rate~10:02@Investigating elevated 5xx responses^10:20@Identified a bad deploy^10:45@Monitoring after rollback")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 2)
    (expect-metric-delta rows_removed 0)
    (expect-text (test-id "open-incident-count") "2")
    (expect-visible (role region :name "Incident inc-42"))
    (expect-visible (role region :name "Incident inc-51"))
  )
)
