#!/usr/bin/env python3
import argparse
import pathlib


def row_id(index):
    return f"row-{index:03d}"


def render_roc(row_count):
    rows = ",\n\t".join(f'"{row_id(index)}"' for index in range(row_count))
    return f'''# Generated by examples/_fixtures/generate_signal_select.py --rows {row_count}
app [main] {{ pf: platform "../../../platform/main.roc" }}

import pf.Elem exposing [Elem]
import pf.Html
import pf.Signal
import pf.Ui

rows : List(Str)
rows = [
\t{rows},
]

main : () -> Elem
main = ||
\tUi.state(
\t\t"{row_id(0)}",
\t\t|selected| {{
\t\t\tselected_signal = selected.signal()
\t\t\trender_row = |key, _item| {{
\t\t\t\tis_selected = Signal.select(selected_signal, key)
\t\t\t\tHtml.section(
\t\t\t\t\t"Selector row ${{key}}",
\t\t\t\t\t[Html.test_id(key)],
\t\t\t\t\t[
\t\t\t\t\t\tHtml.checkbox("Selected ${{key}}", is_selected, selected.on_bool(|current, _| current)),
\t\t\t\t\t\tHtml.button("Select ${{key}}", selected.on_unit(|_| key)),
\t\t\t\t\t],
\t\t\t\t)
\t\t\t}}
\t\t\tUi.state(
\t\t\t\tTrue,
\t\t\t\t|show_all| {{
\t\t\t\t\titems = show_all.signal().map(|visible| if visible rows else ["{row_id(0)}"])
\t\t\t\t\tHtml.div(
\t\t\t\t\t\t[],
\t\t\t\t\t\t[
\t\t\t\t\t\t\tHtml.heading("Signal select {row_count}"),
\t\t\t\t\t\t\tHtml.button("Show one row", show_all.on_unit(|_| False)),
\t\t\t\t\t\t\tHtml.button("Show all rows", show_all.on_unit(|_| True)),
\t\t\t\t\t\t\tUi.each_str(items, |key| key, render_row),
\t\t\t\t\t\t],
\t\t\t\t\t)
\t\t\t\t}},
\t\t\t)
\t\t}},
\t)
'''


def render_spec(row_count):
    last = row_id(row_count - 1)
    return f'''(test "Signal select {row_count}"
  (steps
    ; Generated by examples/_fixtures/generate_signal_select.py --rows {row_count}
    ; Only the old and new selector members may be dirtied at this size.
    (expect-checked (label "Selected {row_id(0)}") true)
    (expect-checked (label "Selected {last}") false)
    (mark-metrics)
    (click (role button :name "Select {last}"))
    (expect-checked (label "Selected {row_id(0)}") false)
    (expect-checked (label "Selected {last}") true)
    (expect-metric-delta selector_members_dirtied 2)
    (expect-metric-delta derived_calls_into_roc 0)
    ; Removing and recreating scopes must update the selector index without
    ; retaining stale member records.
    (click (role button :name "Show one row"))
    (expect-absent (label "Selected {last}"))
    (click (role button :name "Show all rows"))
    (expect-checked (label "Selected {last}") true)
    (click (role button :name "Select {row_id(0)}"))
    (expect-checked (label "Selected {row_id(0)}") true)
    (expect-checked (label "Selected {last}") false)
  )
)
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rows", type=int, required=True)
    parser.add_argument("--roc-out", type=pathlib.Path, required=True)
    parser.add_argument("--spec-out", type=pathlib.Path, required=True)
    args = parser.parse_args()
    if args.rows < 2:
        raise ValueError("--rows must be at least 2")
    args.roc_out.parent.mkdir(parents=True, exist_ok=True)
    args.spec_out.parent.mkdir(parents=True, exist_ok=True)
    args.roc_out.write_text(render_roc(args.rows), encoding="utf-8")
    args.spec_out.write_text(render_spec(args.rows), encoding="utf-8")


if __name__ == "__main__":
    main()
