(test "Typed actions preserve payloads and each accepted occurrence"
  (steps
    (fill (label "Source") "café")
    (expect-text (test-id "result") "waiting")
    (fill (label "Action text") "hello 🌱")
    (expect-text (test-id "result") "waiting|text:café:hello 🌱")
    (fill (label "Action text") "hello 🌱")
    (expect-text (test-id "result") "waiting|text:café:hello 🌱|text:café:hello 🌱")
    (check (label "Action check"))
    (expect-text (test-id "result") "waiting|text:café:hello 🌱|text:café:hello 🌱|checked:True")
    (uncheck (label "Action check"))
    (expect-text (test-id "result") "waiting|text:café:hello 🌱|text:café:hello 🌱|checked:True|checked:False")
    (key-down (label "Action key") "Enter" true)
    (expect-text (test-id "result") "waiting|text:café:hello 🌱|text:café:hello 🌱|checked:True|checked:False|key:Enter:True")
    (custom-event (test-id "action-detail") "demo-detail" "package ready")
    (custom-event (test-id "action-detail") "demo-detail" "package ready")
    (expect-text (test-id "result") "waiting|text:café:hello 🌱|text:café:hello 🌱|checked:True|checked:False|key:Enter:True|detail:package ready|detail:package ready")
    (expect-pending-task "action-ping" 0)
  )
)
