(test "Field notes — pausing auto sync, then deleting a queued note"
  (setup
    ; Field Notes: offline capture, outbox drain, rollback, and restore.
    ;
    ; Storage format is "id|slot|queued|rev|body" per note, notes joined by ";".
    ; Notes captured in this session get session ids ("s<n>"). Every operation is
    ; idempotent, so replaying the log over the value it just persisted is stable.

    (initial-online offline)
    (local-storage "field-notes:notes" "n0|0|1|r7|Generator hours;n1|1|0|r7|Fence line check")
  )
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Note body") "Pump pressure log")
    (click (role button :name "Save note"))
    (fill (label "Note body") "   ")
    (fill (label "Note body") "Tank level 42")
    (click (role button :name "Save note"))
    (fill (label "Note body") "Overflow note")
    (fill (label "Note body") "")
    (click (role button :name "Queue note s1"))
    (click (role button :name "Queue note s2"))
    (mark-metrics)
    (click (role button :name "Promote note s2"))
    (click (role button :name "Promote note n0"))
    (set-online online)
    (resolve-task "note-sync" "n0#r7")
    (reject-task "note-sync" "s2#r0")
    (resolve-task "note-sync" "s1#r0")
    (click (role button :name "Retry note s2"))
    (resolve-task "note-sync" "s2#s2:1")
    (mark-metrics)
    (fill (label "Body n0") "Generator hours 128")
    (resolve-task "note-sync" "n0#n0:1")
    (click (role button :name "Queue note n1"))
    (set-online offline)
    (set-online online)
    (mark-metrics)
    (resolve-stale-task "note-sync" "n1#r7")
    (resolve-task "note-sync" "n1#r7")

    ; pausing auto sync, then deleting a queued note

    (uncheck (label "Sync automatically"))
    (expect-checked (label "Sync automatically") false)
    (expect-text (test-id "auto-sync") "Auto sync paused")
    (click (role button :name "Delete note s2"))
    (expect-absent (role region :name "Note s2"))
    (expect-text (test-id "capacity") "3 of 4")
    (expect-text (test-id "synced-count") "3")
    (fill (label "Note body") "Radio check")
    (click (role button :name "Save note"))
    (expect-visible (role region :name "Note s3"))
    (expect-value (label "Body s3") "Radio check")
    (expect-text (test-id "capacity") "Full")
    (click (role button :name "Queue note s3"))
    (expect-text (test-id "status-s3") "Queued")
    (expect-text (test-id "outbox-count") "1")
    (expect-text (test-id "syncing") "None")
    (expect-pending-task "note-sync" 0)
    (click (role button :name "Delete note s3"))
    (expect-absent (role region :name "Note s3"))
    (expect-text (test-id "outbox-count") "0")
    (expect-visible (text "Outbox is empty"))
    (expect-text (test-id "capacity") "3 of 4")
    (expect-pending-task "note-sync" 0)
    (check (label "Sync automatically"))
    (expect-text (test-id "auto-sync") "Auto sync on")
    (expect-pending-task "note-sync" 0)
  )
)
