(test "Query builder — AND / OR on a group"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (check (label "Negate n3"))
    (uncheck (label "Negate n3"))
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n4") "A")

    ; AND / OR on a group
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n5") "o")
    (expect-text (test-id "summary-n5") "name ~ 'o'")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' AND name ~ 'o'))")
    (expect-text (test-id "match-summary") "0 of 5")
    (click (role button :name "Set OR for n3"))
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' OR name ~ 'o'))")
    (expect-text (test-id "match-summary") "2 of 5")
    (expect-visible (test-id "match-Ada"))
    (expect-visible (test-id "match-Bo"))
    ; The sibling leaves kept their own values across the mode switch.
    (expect-value (label "Value n4") "A")
    (expect-value (label "Value n5") "o")
  )
)
