(test "Query builder — back to a single condition"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (check (label "Negate n3"))
    (uncheck (label "Negate n3"))
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n4") "A")
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n5") "o")
    (select-option (label "Mode n3") "OR")
    (click (role button :name "Add group to n3"))
    (click (role button :name "Add condition to n6"))
    (select-option (label "Field n7") "level")
    (select-option (label "Operator n7") "gt")
    (fill (label "Value n7") "4")
    (select-option (label "Mode n3") "AND")
    (select-option (label "Mode n3") "OR")
    (mark-metrics)
    (fill (label "Value n7") "3")
    (mark-metrics)
    (click (role button :name "Delete n6"))
    (click (role button :name "Delete n5"))
    (check (label "Negate n1"))
    (uncheck (label "Negate n1"))

    ; back to a single condition
    (click (role button :name "Delete n3"))
    (expect-absent (role region :name "Group n3"))
    (expect-absent (role region :name "Condition n4"))
    (expect-visible (role region :name "Condition n2"))
    (expect-text (test-id "query-text") "(dept = 'Platform')")
    (expect-text (test-id "shape-stats") "Conditions 1 / Groups 1 / Depth 1")
    (expect-text (test-id "match-summary") "Matching rows: 2 of 5")
  )
)
