(test "Query builder — deleting a nested group"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (check (label "Negate n3"))
    (uncheck (label "Negate n3"))
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n4") "A")
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n5") "o")
    (click (role button :name "Set OR for n3"))
    (click (role button :name "Add group to n3"))
    (click (role button :name "Add condition to n6"))
    (select-option (label "Field n7") "level")
    (select-option (label "Operator n7") "gt")
    (fill (label "Value n7") "4")
    (click (role button :name "Set AND for n3"))
    (click (role button :name "Set OR for n3"))
    (mark-metrics)
    (fill (label "Value n7") "3")

    ; deleting a nested group
    (mark-metrics)
    (click (role button :name "Delete n6"))
    (expect-absent (role region :name "Group n6"))
    (expect-absent (role region :name "Condition n7"))
    (expect-visible (role region :name "Condition n4"))
    (expect-visible (role region :name "Condition n5"))
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' OR name ~ 'o'))")
    (expect-text (test-id "shape-stats") "3")
    (expect-text (test-id "group-count") "2")
    (expect-text (test-id "tree-depth") "2")
    (expect-text (test-id "match-summary") "2 of 5")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 1)
    ; The group scope and its child condition scope are disposed; the surviving
    ; sibling rows at both levels are reused.
    (expect-metric-delta scopes_disposed 2)
    (expect-metric-delta rows_reused 4)
  )
)
