(test "Query builder — editing a leaf three levels deep does not recreate its siblings"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (check (label "Negate n3"))
    (uncheck (label "Negate n3"))
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n4") "A")
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n5") "o")
    (click (role button :name "Set OR for n3"))
    (click (role button :name "Add group to n3"))
    (click (role button :name "Add condition to n6"))
    (select-option (label "Field n7") "level")
    (select-option (label "Operator n7") "gt")
    (fill (label "Value n7") "4")
    (click (role button :name "Set AND for n3"))
    (click (role button :name "Set OR for n3"))

    ; editing a leaf three levels deep does not recreate its siblings
    (mark-metrics)
    (fill (label "Value n7") "3")
    (expect-text (test-id "summary-n7") "level > '3'")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' OR name ~ 'o' OR (level > '3')))")
    (expect-text (test-id "match-summary") "2 of 5")
    ; Sibling branches are untouched: no row is created, removed, or re-scoped.
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    ; Every sibling row in all three each_str levels is re-keyed and reused.
    (expect-metric-delta rows_reused 6)
    (expect-metric-delta-at-most patches_emitted 8)
    (expect-metric-delta-at-most dirty_source_roots 4)
    ; The siblings still hold their own values.
    (expect-value (label "Value n4") "A")
    (expect-value (label "Value n5") "o")
    (expect-value (label "Value n2") "Platform")
  )
)
