(test "Query builder — empty root group"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (check (label "Negate n3"))
    (uncheck (label "Negate n3"))
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n4") "A")
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n5") "o")
    (select-option (label "Mode n3") "OR")
    (click (role button :name "Add group to n3"))
    (click (role button :name "Add condition to n6"))
    (select-option (label "Field n7") "level")
    (select-option (label "Operator n7") "gt")
    (fill (label "Value n7") "4")
    (select-option (label "Mode n3") "AND")
    (select-option (label "Mode n3") "OR")
    (mark-metrics)
    (fill (label "Value n7") "3")
    (mark-metrics)
    (click (role button :name "Delete n6"))
    (click (role button :name "Delete n5"))
    (check (label "Negate n1"))
    (uncheck (label "Negate n1"))
    (click (role button :name "Delete n3"))

    ; empty root group
    (click (role button :name "Delete n2"))
    (expect-absent (role region :name "Condition n2"))
    (expect-text (test-id "query-text") "(ALL)")
    (expect-text (test-id "summary-n1") "(ALL)")
    (expect-text (test-id "shape-stats") "Conditions 0 / Groups 1 / Depth 1")
    (expect-text (test-id "match-summary") "Matching rows: 5 of 5")
    (expect-visible (test-id "match-Ada"))
    (expect-visible (test-id "match-Eli"))
    (check (label "Negate n1"))
    (expect-text (test-id "query-text") "NOT (ALL)")
    (expect-text (test-id "match-summary") "Matching rows: 0 of 5")
    (expect-absent (test-id "match-Ada"))
    (uncheck (label "Negate n1"))
    (expect-text (test-id "match-summary") "Matching rows: 5 of 5")
    ; The tree can be rebuilt from empty.
    (click (role button :name "Add condition to n1"))
    (expect-visible (role region :name "Condition n2"))
    (expect-text (test-id "query-text") "(ANY)")
    (expect-text (test-id "match-summary") "Matching rows: 5 of 5")
    (select-option (label "Field n2") "dept")
    (fill (label "Value n2") "Design")
    (expect-text (test-id "query-text") "(dept ~ 'Design')")
    (expect-text (test-id "match-summary") "Matching rows: 2 of 5")
    (expect-visible (test-id "match-Cy"))
    (expect-visible (test-id "match-Eli"))
  )
)
