(test "Query builder — initial state"
  (steps
    ; initial state
    (expect-visible (role heading :name "Query Builder"))
    (expect-visible (role region :name "Dataset"))
    (expect-visible (role region :name "Generated query"))
    (expect-visible (role region :name "Matches"))
    (expect-visible (role region :name "Filter tree"))
    (expect-visible (role region :name "Group n1"))
    (expect-visible (role region :name "Condition n2"))
    (expect-checked (label "Include archived rows") false)
    (expect-text (test-id "dataset-summary") "Dataset rows: 5")
    (expect-text (test-id "query-text") "(dept = 'Platform')")
    (expect-text (test-id "shape-stats") "Conditions 1 / Groups 1 / Depth 1")
    (expect-text (test-id "match-summary") "Matching rows: 2 of 5")
    (expect-text (test-id "summary-n1") "(dept = 'Platform')")
    (expect-text (test-id "summary-n2") "dept = 'Platform'")
    (expect-value (label "Mode n1") "AND")
    (expect-checked (label "Negate n1") false)
    (expect-value (label "Field n2") "dept")
    (expect-value (label "Operator n2") "eq")
    (expect-value (label "Value n2") "Platform")
    (expect-visible (test-id "match-Ada"))
    (expect-visible (test-id "match-Bo"))
    (expect-absent (test-id "match-Cy"))
    (expect-absent (test-id "match-Dee"))
    (expect-absent (test-id "match-Eli"))
    ; The root group is not deletable.
    (expect-absent (role button :name "Delete n1"))
    (expect-visible (text "Root group cannot be deleted"))
  )
)
