(test "Query builder — nesting: a group inside a group"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))

    ; nesting: a group inside a group
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (expect-visible (role region :name "Group n3"))
    (expect-attr (role button :name "Set AND for n3") aria-pressed "true")
    (expect-checked (label "Negate n3") false)
    (expect-text (test-id "summary-n3") "(ALL)")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (ALL))")
    (expect-text (test-id "shape-stats") "1")
    (expect-text (test-id "group-count") "2")
    (expect-text (test-id "tree-depth") "2")
    ; An empty group imposes no constraint.
    (expect-text (test-id "match-summary") "2 of 5")
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta rows_reused 1)
    ; A negated empty group matches nothing.
    (check (label "Negate n3"))
    (expect-text (test-id "summary-n3") "NOT (ALL)")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND NOT (ALL))")
    (expect-text (test-id "match-summary") "0 of 5")
    (uncheck (label "Negate n3"))
    (expect-text (test-id "match-summary") "2 of 5")
    (click (role button :name "Add condition to n3"))
    (expect-visible (role region :name "Condition n4"))
    (expect-value (label "Field n4") "name")
    (expect-value (label "Operator n4") "contains")
    (expect-value (label "Value n4") "")
    (expect-text (test-id "summary-n4") "ANY")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (ANY))")
    (expect-text (test-id "shape-stats") "2")
    (expect-text (test-id "group-count") "2")
    (expect-text (test-id "tree-depth") "2")
    (expect-text (test-id "match-summary") "2 of 5")
    (fill (label "Value n4") "A")
    (expect-text (test-id "summary-n4") "name ~ 'A'")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A'))")
    (expect-text (test-id "match-summary") "1 of 5")
    (expect-visible (test-id "match-Ada"))
    (expect-absent (test-id "match-Bo"))
  )
)
