(test "Query builder — three levels of nesting"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Value n2") "")
    (fill (label "Value n2") "Platform")
    (select-option (label "Operator n2") "ne")
    (select-option (label "Operator n2") "contains")
    (fill (label "Value n2") "esi")
    (select-option (label "Field n2") "name")
    (select-option (label "Operator n2") "gt")
    (fill (label "Value n2") "3")
    (select-option (label "Field n2") "level")
    (select-option (label "Operator n2") "lt")
    (fill (label "Value n2") "three")
    (select-option (label "Field n2") "dept")
    (select-option (label "Operator n2") "eq")
    (fill (label "Value n2") "Platform")
    (mark-metrics)
    (check (label "Include archived rows"))
    (uncheck (label "Include archived rows"))
    (mark-metrics)
    (click (role button :name "Add group to n1"))
    (check (label "Negate n3"))
    (uncheck (label "Negate n3"))
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n4") "A")
    (click (role button :name "Add condition to n3"))
    (fill (label "Value n5") "o")
    (select-option (label "Mode n3") "OR")

    ; three levels of nesting
    (click (role button :name "Add group to n3"))
    (expect-visible (role region :name "Group n6"))
    (expect-text (test-id "summary-n6") "(ALL)")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' OR name ~ 'o' OR (ALL)))")
    (expect-text (test-id "shape-stats") "Conditions 3 / Groups 3 / Depth 3")
    (click (role button :name "Add condition to n6"))
    (expect-visible (role region :name "Condition n7"))
    (expect-text (test-id "shape-stats") "Conditions 4 / Groups 3 / Depth 3")
    (select-option (label "Field n7") "level")
    (select-option (label "Operator n7") "gt")
    (fill (label "Value n7") "4")
    (expect-text (test-id "summary-n7") "level > '4'")
    (expect-text (test-id "summary-n6") "(level > '4')")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' OR name ~ 'o' OR (level > '4')))")
    (expect-text (test-id "match-summary") "Matching rows: 2 of 5")
    ; Switching the middle group to AND changes the match count.
    (select-option (label "Mode n3") "AND")
    (expect-text (test-id "query-text") "(dept = 'Platform' AND (name ~ 'A' AND name ~ 'o' AND (level > '4')))")
    (expect-text (test-id "match-summary") "Matching rows: 0 of 5")
    (select-option (label "Mode n3") "OR")
    (expect-text (test-id "match-summary") "Matching rows: 2 of 5")
  )
)
