(test "Form validation pattern"
  (steps
    ; Form validation pattern scenario

    (expect-visible (role heading :name "Form Validation Pattern"))
    (expect-attr (role region :name "Form Validation Pattern") data-fixture "form-validation-pattern")
    (expect-attr (role form :name "Validation form") id "validation-form")
    (expect-value (label "Invite email") "")
    (expect-attr (label "Invite email") id "invite-email")
    (expect-attr (label "Invite email") type "email")
    (expect-attr (label "Invite email") aria-describedby "invite-email-message")
    (expect-no-attr (label "Invite email") aria-invalid)
    (expect-attr (label "Accept terms") aria-describedby "terms-message")
    (expect-no-attr (label "Accept terms") aria-invalid)
    (expect-text (text "Email validation: ready.") "Email validation: ready.")
    (expect-text (text "Terms validation: ready.") "Terms validation: ready.")
    (expect-text (text "Submit status: idle") "Submit status: idle")
    (expect-disabled (role button :name "Send invite") true)
    (expect-pending-task "form-submit" 0)
    (submit (role form :name "Validation form"))
    (expect-attr (label "Invite email") aria-invalid "")
    (expect-attr (label "Accept terms") aria-invalid "")
    (expect-text (text "Email validation: enter an email address.") "Email validation: enter an email address.")
    (expect-text (text "Terms validation: accept terms to continue.") "Terms validation: accept terms to continue.")
    (expect-disabled (role button :name "Send invite") true)
    (expect-pending-task "form-submit" 0)
    (fill (label "Invite email") "ops@example.com")
    (expect-value (label "Invite email") "ops@example.com")
    (expect-no-attr (label "Invite email") aria-invalid)
    (expect-attr (label "Accept terms") aria-invalid "")
    (expect-text (text "Email validation: ready.") "Email validation: ready.")
    (expect-disabled (role button :name "Send invite") true)
    (check (label "Accept terms"))
    (expect-checked (label "Accept terms") true)
    (expect-no-attr (label "Accept terms") aria-invalid)
    (expect-text (text "Terms validation: ready.") "Terms validation: ready.")
    (expect-disabled (role button :name "Send invite") false)
    (click (role button :name "Send invite"))
    (expect-pending-task "form-submit" 1)
    (expect-text (text "Submit status: sending") "Submit status: sending")
    (expect-disabled (role button :name "Send invite") true)
    (resolve-task "form-submit" "queued")
    (expect-pending-task "form-submit" 0)
    (expect-text (text "Submit result: queued") "Submit result: queued")
    (expect-disabled (role button :name "Send invite") false)
  )
)
