(test "Controlled input contract"
  (steps
    ; Controlled input reconciliation contract

    (expect-visible (role heading :name "Controlled Input Contract"))
    (expect-attr (role region :name "Controlled Input Contract") data-fixture "controlled-input-contract")
    (expect-value (label "Normalized draft") "")
    (expect-value (label "Echo draft") "")
    (expect-text (text "Canonical normalized: ") "Canonical normalized: ")
    (focus (label "Normalized draft"))
    (expect-text (text "Focus events: 1") "Focus events: 1")
    (fill (label "Normalized draft") "one")
    (expect-value (label "Normalized draft") "one")
    (expect-text (text "Canonical normalized: canonical:one") "Canonical normalized: canonical:one")
    (fill (label "Normalized draft") "two")
    (expect-value (label "Normalized draft") "two")
    (expect-text (text "Canonical normalized: canonical:two") "Canonical normalized: canonical:two")
    (blur (label "Normalized draft"))
    (expect-value (label "Normalized draft") "canonical:two")
    (expect-text (text "Blur events: 1") "Blur events: 1")
    (focus (label "Normalized draft"))
    (composition-start (label "Normalized draft"))
    (fill (label "Normalized draft") "ime")
    (expect-value (label "Normalized draft") "ime")
    (expect-text (text "Canonical normalized: canonical:ime") "Canonical normalized: canonical:ime")
    (composition-end (label "Normalized draft"))
    (expect-value (label "Normalized draft") "ime")
    (blur (label "Normalized draft"))
    (expect-value (label "Normalized draft") "canonical:ime")
    (focus (label "Echo draft"))
    (fill (label "Echo draft") "same")
    (expect-value (label "Echo draft") "same")
    (expect-updates (label "Echo draft") 2)
    (blur (label "Echo draft"))
  )
)
