(test "File replacement and truncation retire old records and partial lines"
  (steps
    (click (role button :name "Open log…"))
    (resolve-file-choice "activity-open" (chosen "/tmp/events.log"))
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "old\nunfinished" :device 1 :inode 2 :offset 14 :change initial :state at-end)
    (click (role button :name "Inspect 1"))
    (tick-interval 500)
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "new\n" :device 1 :inode 3 :offset 4 :change rotated :state at-end)
    (expect-absent (test-id "event-1"))
    (expect-visible (test-id "event-2"))
    (expect-visible (text "This event is no longer in retained history."))
    (expect-text (test-id "activity-status") "File replaced: retained history restarted from the new file.")
    (click (role button :name "Inspect 2"))
    (expect-visible (text "Event 2 · TEXT · Log · new"))
    (tick-interval 500)
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "x\n" :device 1 :inode 3 :offset 2 :change truncated :state at-end)
    (expect-absent (test-id "event-2"))
    (expect-visible (test-id "event-3"))
    (expect-text (test-id "activity-status") "File truncated: retained history restarted from the beginning.")))
