(test "Canceling and retrying log reads preserves accepted history"
  (steps
    (click (role button :name "Open log…"))
    (resolve-file-choice "activity-open" (chosen "/tmp/events.log"))
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "first\n" :device 1 :inode 2 :offset 6 :change initial :state at-end)
    (tick-interval 500)
    (click (role button :name "Pause following"))
    (expect-canceled-task "activity-read" 1)
    (expect-interval 500 0)
    (resolve-stale-task "activity-read" "canceled payload must not be decoded")
    (expect-visible (text "Retained: 1 / 1000"))
    (click (role button :name "Resume following"))
    (reject-file "activity-read" :kind permission-denied :detail "/tmp/events.log")
    (expect-visible (test-id "event-1"))
    (expect-disabled (role button :name "Retry read") false)
    (click (role button :name "Retry read"))
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "second\n" :device 1 :inode 2 :offset 13 :change continued :state at-end)
    (expect-visible (test-id "event-2"))
    (expect-visible (text "Retained: 2 / 1000"))
    (click (role button :name "Pause following"))
    (click (role button :name "Use simulated replay"))
    (expect-visible (text "Retained: 0 / 1000"))
    (click (role button :name "Step replay"))
    (expect-visible (test-id "event-3"))))
