(test "File replacement and truncation retire old records and partial lines"
  (steps
    (stub-file-choice "activity-open" (chosen "/tmp/events.log"))
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 14 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "old\nunfinished" :size 14)
    (click (role button :name "Open log…"))
    (click (role button :name "Inspect 1"))
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 4 :device 1 :inode 3)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "new\n" :size 4)
    (tick-interval 500)
    (expect-absent (test-id "event-1"))
    (expect-visible (test-id "event-2"))
    (expect-visible (text "This event is no longer in retained history."))
    (expect-text (test-id "activity-status") "File replaced: retained history restarted from the new file.")
    (click (role button :name "Inspect 2"))
    (expect-visible (text "Event 2 · TEXT · Log · new"))
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 2 :device 1 :inode 3)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "x\n" :size 2)
    (tick-interval 500)
    (expect-absent (test-id "event-2"))
    (expect-visible (test-id "event-3"))
    (expect-text (test-id "activity-status") "File truncated: retained history restarted from the beginning.")))
