(test "A real log drains chunks and assembles records before polling"
  (steps
    (click (role button :name "Step replay"))
    (stub-file-choice "activity-open" (chosen "/tmp/events.log"))
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 14 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "first\npar" :size 14)
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 14 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "tial\n" :offset 9 :size 14)
    (click (role button :name "Open log…"))
    (expect-absent (test-id "event-1"))
    (expect-visible (test-id "event-2"))
    (expect-visible (test-id "event-3"))
    (expect-absent (text "Replay paused"))
    (expect-interval 500 1)
    (click (role button :name "Inspect 3"))
    (expect-visible (text "Event 3 · TEXT · Log · partial"))
    (expect-disabled (role checkbox :name "Errors only") true)
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 14 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "" :offset 14 :size 14)
    (mark-metrics)
    (tick-interval 500)
    (expect-interval 500 1)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-visible (text "Retained: 2 / 1000"))
    (click (role button :name "Pause following"))
    (expect-interval 500 0)))
