(test "Pausing, failing, and retrying log reads preserves accepted history"
  (steps
    (stub-file-choice "activity-open" (chosen "/tmp/events.log"))
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 6 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "first\n" :size 6)
    (click (role button :name "Open log…"))
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 6 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "" :offset 6 :size 6)
    (tick-interval 500)
    (click (role button :name "Pause following"))
    (expect-interval 500 0)
    (expect-visible (text "Retained: 1 / 1000"))
    (stub-file-reject "activity-read" :kind permission-denied :detail "/tmp/events.log")
    (click (role button :name "Resume following"))
    (expect-visible (test-id "event-1"))
    (expect-disabled (role button :name "Retry read") false)
    (stub-file-stat "activity-read" :path "/tmp/events.log" :kind file :bytes 13 :device 1 :inode 2)
    (stub-file-read "activity-read" :path "/tmp/events.log" :text "second\n" :offset 6 :size 13)
    (click (role button :name "Retry read"))
    (expect-visible (test-id "event-2"))
    (expect-visible (text "Retained: 2 / 1000"))
    (click (role button :name "Pause following"))
    (click (role button :name "Use simulated replay"))
    (expect-visible (text "Retained: 0 / 1000"))
    (click (role button :name "Step replay"))
    (expect-visible (test-id "event-3"))))
