(test "A real log drains chunks and assembles records before polling"
  (steps
    (click (role button :name "Step replay"))
    (click (role button :name "Open log…"))
    (resolve-file-choice "activity-open" (chosen "/tmp/events.log"))
    (expect-pending-task "activity-read" 1)
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "first\npar" :device 1 :inode 2 :offset 9 :change initial :state more)
    (expect-absent (test-id "event-1"))
    (expect-visible (test-id "event-2"))
    (expect-interval 500 0)
    (expect-pending-task "activity-read" 1)
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "tial\n" :device 1 :inode 2 :offset 14 :change continued :state at-end)
    (expect-visible (test-id "event-3"))
    (expect-interval 500 1)
    (expect-pending-task "activity-read" 0)
    (click (role button :name "Inspect 3"))
    (expect-visible (text "Event 3 · TEXT · Log · partial"))
    (expect-disabled (role checkbox :name "Errors only") true)
    (tick-interval 500)
    (expect-interval 500 0)
    (mark-metrics)
    (resolve-file-log "activity-read" :path "/tmp/events.log" :text "" :device 1 :inode 2 :offset 14 :change continued :state at-end)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-visible (text "Retained: 2 / 1000"))
    (click (role button :name "Pause following"))
    (expect-interval 500 0)))
