(test "Filtering retains the selected event and reveals new matching events"
  (steps
    (click (role button :name "Start replay"))
    (tick-interval 500)
    (tick-interval 500)
    (tick-interval 500)
    (tick-interval 500)
    (tick-interval 500)
    (tick-interval 500)
    (click (role button :name "Pause replay"))
    (click (role button :name "Inspect 2"))
    (fill (role textbox :name "Filter activity") "Indexer")
    (expect-visible (test-id "event-2"))
    (expect-visible (test-id "event-6"))
    (expect-absent (test-id "event-1"))
    (check (role checkbox :name "Errors only"))
    (expect-absent (test-id "event-2"))
    (expect-visible (test-id "event-6"))
    (expect-visible (text "Event 2 · INFO · Indexer · Search index updated"))
    (fill (role textbox :name "Filter activity") "no matches")
    (expect-absent (test-id "event-6"))
    (expect-visible (text "Retained: 6 / 1000"))))
