(test "Replay history survives pause and resumes with fresh identities"
  (steps
    (expect-visible (text "Retained: 0 / 1000"))
    (click (role button :name "Step replay"))
    (expect-visible (test-id "event-1"))
    (mark-metrics)
    (click (role button :name "Step replay"))
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta rows_render_roots_moved 0)
    (click (role button :name "Start replay"))
    (tick-interval 500)
    (tick-interval 500)
    (click (role button :name "Pause replay"))
    (expect-visible (text "Retained: 4 / 1000"))
    (click (role button :name "Inspect 2"))
    (expect-visible (text "Event 2 · INFO · Indexer · Search index updated"))
    (click (role button :name "Start replay"))
    (tick-interval 500)
    (click (role button :name "Pause replay"))
    (expect-visible (test-id "event-5"))
    (click (role button :name "Clear history"))
    (expect-visible (text "This event is no longer in retained history."))
    (expect-absent (test-id "event-2"))
    (click (role button :name "Step replay"))
    (expect-visible (test-id "event-6"))
    (expect-visible (text "Retained: 1 / 1000"))))
