(test "Native directory preview log and associated-open routes keep typed results"
  (steps
    (click (role button :name "List"))
    (expect-pending-task "fixture-list" 1)
    (resolve-task "fixture-list" "6:files14:/tmp1:113:/tmp/file.txt4:file1:7")
    (expect-text (text "Listed 1 direct entries") "Listed 1 direct entries")
    (click (role button :name "Preview"))
    (resolve-task "fixture-preview" "6:files113:/tmp/file.txt8:hello λ4:true")
    (expect-text (text "Preview: hello λ") "Preview: hello λ")
    (click (role button :name "Log"))
    (resolve-task "fixture-log" "6:files113:/tmp/file.txt7:next λ1:11:21:79:continued6:at-end")
    (expect-text (text "Log: next λ") "Log: next λ")
    (click (role button :name "Open associated"))
    (resolve-task "fixture-open" "6:files113:/tmp/file.txt")
    (expect-text (text "Opened: /tmp/file.txt") "Opened: /tmp/file.txt")
    (click (role button :name "Log"))
    (click (role button :name "Cancel log"))
    (expect-canceled-task "fixture-log" 1)
    (expect-text (text "Canceled") "Canceled")
    (resolve-stale-task "fixture-log" "not decoded after cancellation")
    (expect-text (text "Canceled") "Canceled")
  )
)
