(test "Native directory preview log and associated-open routes keep typed results"
  (steps
    (click (role button :name "List"))
    (expect-pending-task "fixture-list" 1)
    (resolve-file-directory "fixture-list" :path "/tmp" :entries ((file "/tmp/file.txt" 7)))
    (expect-text (text "Listed 1 direct entries") "Listed 1 direct entries")
    (click (role button :name "Preview"))
    (resolve-file-preview "fixture-preview" :path "/tmp/file.txt" :text "hello λ" :truncated true)
    (expect-text (text "Preview: hello λ") "Preview: hello λ")
    (click (role button :name "Log"))
    (resolve-file-log "fixture-log" :path "/tmp/file.txt" :text "next λ" :device 1 :inode 2 :offset 7 :change continued :state at-end)
    (expect-text (text "Log: next λ") "Log: next λ")
    (click (role button :name "Open associated"))
    (resolve-file-open "fixture-open" :path "/tmp/file.txt")
    (expect-text (text "Opened: /tmp/file.txt") "Opened: /tmp/file.txt")
    (click (role button :name "Log"))
    (click (role button :name "Cancel log"))
    (expect-canceled-task "fixture-log" 1)
    (expect-text (text "Canceled") "Canceled")
    (resolve-stale-task "fixture-log" "not decoded after cancellation")
    (expect-text (text "Canceled") "Canceled")
  )
)
