(test "Native Files results and cancellation share task propagation"
  (steps
    (expect-pending-task "fixture-read" 1)
    (resolve-task "fixture-read" "6:files110:/tmp/a.txt5:hello")
    (expect-text (text "Loaded 5 bytes") "Loaded 5 bytes")
    (click (role button :name "Read"))
    (expect-pending-task "fixture-read" 1)
    (expect-text (text "Loading") "Loading")
    (click (role button :name "Cancel"))
    (expect-pending-task "fixture-read" 0)
    (expect-canceled-task "fixture-read" 1)
    (expect-text (text "Canceled") "Canceled")
    (resolve-stale-task "fixture-read" "not decoded after cancellation")
    (expect-text (text "Canceled") "Canceled")
  )
)
