(test "Synchronous Files primitives decode stubbed results and report typed errors"
  (setup
    (stub-file-read "mount" :path "/tmp/roc-signals-files-fixture.txt" :text "hello"))
  (steps
    (expect-text (text "Loaded 5 bytes") "Loaded 5 bytes")
    (stub-file-write "write" :path "/tmp/roc-signals-files-fixture.txt" :bytes 5)
    (click (role button :name "Write"))
    (expect-text (text "Wrote 5 bytes") "Wrote 5 bytes")
    (stub-file-directory "list" :path "/tmp/roc-signals-files-depth" :entries ((file "/tmp/roc-signals-files-depth/file.txt" 7)))
    (click (role button :name "List"))
    (expect-text (text "Listed 1 direct entries") "Listed 1 direct entries")
    (stub-file-preview "preview" :path "/tmp/roc-signals-files-fixture.txt" :text "hello λ" :truncated true)
    (click (role button :name "Preview"))
    (expect-text (text "Preview: hello λ") "Preview: hello λ")
    (stub-file-log "log" :path "/tmp/roc-signals-files-fixture.txt" :text "next λ" :device 1 :inode 2 :offset 7 :change continued :state at-end)
    (click (role button :name "Log"))
    (expect-text (text "Log: next λ") "Log: next λ")
    (stub-file-open "open" :path "/tmp/roc-signals-files-fixture.txt")
    (click (role button :name "Open associated"))
    (expect-text (text "Opened: /tmp/roc-signals-files-fixture.txt") "Opened: /tmp/roc-signals-files-fixture.txt")
    (stub-file-assets "assets" :entries ((ok "avatars/maya.png")))
    (click (role button :name "Verify assets"))
    (expect-text (text "Verified 1 assets") "Verified 1 assets")
    (click (role button :name "Read"))
    (expect-text (text "Native service unavailable: no spec stub for read_text /tmp/roc-signals-files-fixture.txt") "Native service unavailable: no spec stub for read_text /tmp/roc-signals-files-fixture.txt")
  )
)
