(test "Files primitives and conveniences decode stubbed results and report typed errors"
  (setup
    (stub-file-read "mount" :path "/tmp/roc-signals-files-fixture.txt" :text "hello"))
  (steps
    (expect-text (text "Loaded 5 bytes") "Loaded 5 bytes")
    (click (role button :name "Write"))
    (expect-text (text "Wrote 5 bytes") "Wrote 5 bytes")
    (stub-file-reject "write" :kind permission-denied :detail "/tmp/roc-signals-files-fixture.txt")
    (click (role button :name "Write"))
    (expect-text (text "Permission denied: /tmp/roc-signals-files-fixture.txt") "Permission denied: /tmp/roc-signals-files-fixture.txt")
    (stub-file-stat "stat" :path "/tmp/roc-signals-files-fixture.txt" :kind file :bytes 5 :inode 42)
    (click (role button :name "Stat"))
    (expect-text (text "Size 5 inode 42") "Size 5 inode 42")
    (stub-file-read "bytes" :path "/tmp/roc-signals-files-fixture.txt" :text "hello")
    (click (role button :name "Read bytes"))
    (expect-text (text "Bytes 3 of 5") "Bytes 3 of 5")
    (stub-file-directory "list" :path "/tmp/roc-signals-files-depth" :entries ((file "/tmp/roc-signals-files-depth/file.txt" 7)))
    (click (role button :name "List"))
    (expect-text (text "Listed 1 direct entries") "Listed 1 direct entries")
    (stub-file-directory "scan" :path "/tmp/roc-signals-files-depth" :entries ((directory "/tmp/roc-signals-files-depth/sub" 0) (file "/tmp/roc-signals-files-depth/file.txt" 7)))
    (stub-file-directory "scan-sub" :path "/tmp/roc-signals-files-depth/sub" :entries ((file "/tmp/roc-signals-files-depth/sub/inner.txt" 1)))
    (click (role button :name "Scan"))
    (expect-text (text "Scanned 3 entries") "Scanned 3 entries")
    (stub-file-read "preview" :path "/tmp/roc-signals-files-fixture.txt" :text "hello λ" :size 70000)
    (click (role button :name "Preview"))
    (expect-text (text "Preview: hello λ (truncated)") "Preview: hello λ (truncated)")
    (stub-file-open "open" :path "/tmp/roc-signals-files-fixture.txt")
    (click (role button :name "Open associated"))
    (expect-text (text "Opened: /tmp/roc-signals-files-fixture.txt") "Opened: /tmp/roc-signals-files-fixture.txt")
    (stub-file-read "asset" :path "/assets/avatars/maya.png" :text "abc")
    (click (role button :name "Verify assets"))
    (expect-text (text "Verified 1 assets: ok") "Verified 1 assets: ok")
    (click (role button :name "Read"))
    (expect-text (text "Native service unavailable: no spec stub for read_bytes /tmp/roc-signals-files-fixture.txt") "Native service unavailable: no spec stub for read_bytes /tmp/roc-signals-files-fixture.txt")
  ))
