(test "Support inbox — a send fails and rolls back"
  (steps
    ; Given the state established by earlier scenarios
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|new|-")
    (click (test-id "open-c1"))
    (mark-metrics)
    (click (test-id "open-c3"))
    (resolve-stale-task "inbox" "c9|Stale conversation|Nobody|me#")
    (click (test-id "open-c2"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (change (label "Assigned to me") "mine")
    (change (label "Unread") "unread")
    (change (label "All") "all")
    (click (test-id "open-c1"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (fill (label "Message") "Refund issued")
    (mark-metrics)
    (click (role button :name "Send message"))
    (tick-interval 4000)
    (mark-metrics)
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (resolve-task "send" "p1")
    (click (test-id "open-c3"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1")

    ; a send fails and rolls back

    (click (test-id "open-c1"))
    (expect-pending-task "inbox" 1)
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1")
    (expect-text (test-id "thread-count") "Messages: 3")
    (expect-text (test-id "body-p1") "agent: Refund issued")
    (fill (label "Message") "Second reply")
    (expect-disabled (role button :name "Send message") false)
    (mark-metrics)
    (click (role button :name "Send message"))
    (expect-pending-task "send" 1)
    (expect-metric-delta rows_created 1)
    (expect-text (test-id "thread-count") "Messages: 4")
    (expect-visible (role region :name "Message p2"))
    (expect-text (test-id "body-p2") "you: Second reply")
    (expect-text (test-id "mstate-p2") "sending")
    (expect-text (test-id "send-state") "Send state: sending")
    (expect-text (test-id "inbox-summary") "3 conversations, 0 unread, 1 sending")
    (mark-metrics)
    (reject-task "send" "p2")
    (expect-pending-task "send" 0)
    (expect-absent (role region :name "Message p2"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (expect-text (test-id "thread-count") "Messages: 3")
    (expect-text (test-id "send-state") "Send state: failed")
    (expect-text (test-id "send-error") "Send failed: Second reply")
    (expect-text (test-id "inbox-summary") "3 conversations, 0 unread, 0 sending")
    ; the composer stays locked until the failure is dealt with
    (expect-disabled (role button :name "Send message") true)
    ; the rollback must not disturb its siblings
    (expect-visible (role region :name "Message p1"))
    (expect-text (test-id "body-p1") "agent: Refund issued")
    (expect-text (test-id "mstate-p1") "delivered")
    (expect-text (test-id "body-m1") "customer: My card was declined")
    (click (role button :name "Discard failed message"))
    (expect-text (test-id "send-state") "Send state: discarded")
    (expect-text (test-id "send-error") "No send errors")
    (expect-absent (role region :name "Message p2"))
    (expect-visible (role region :name "Message p1"))
  )
)
