(test "Support inbox — initial mount"
  (steps
    ; initial mount

    (expect-visible (role heading :name "Support Inbox"))
    (expect-visible (role region :name "Inbox summary"))
    (expect-visible (role region :name "Conversations"))
    (expect-visible (role region :name "Thread"))
    (expect-visible (role region :name "Poll loop"))
    (expect-visible (role form :name "Composer"))
    (expect-text (test-id "inbox-summary") "0 conversations, 0 unread, 0 sending")
    (expect-text (test-id "sync-status") "Sync: loading")
    (expect-text (test-id "filter-state") "Filter: all")
    (expect-text (test-id "poll-state") "Polling: every 4s")
    (expect-text (test-id "poll-count") "Polls issued: 0")
    (expect-text (test-id "filter-notice") "All open conversations are listed.")
    (expect-text (test-id "conv-empty") "No conversations to show.")
    (expect-text (test-id "thread-title") "Thread: no conversation selected")
    (expect-text (test-id "thread-empty") "No messages yet.")
    (expect-text (test-id "send-state") "Send state: idle")
    (expect-text (test-id "send-error") "No send errors")
    (expect-value (label "Message") "")
    (expect-checked (label "All") true)
    (expect-checked (label "Unread") false)
    (expect-checked (label "Assigned to me") false)
    (expect-checked (label "Poll for updates") true)
    (expect-disabled (role button :name "Send message") true)
    (expect-interval 4000 1)
    (expect-pending-task "inbox" 1)
    (expect-pending-task "send" 0)
    (expect-cleanup "inbox polling cleanup" 0)
  )
)
