(test "Support inbox — optimistic sending"
  (steps
    ; Given the state established by earlier scenarios
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|new|-")
    (click (test-id "open-c1"))
    (mark-metrics)
    (click (test-id "open-c3"))
    (resolve-stale-task "inbox" "c9|Stale conversation|Nobody|me#")
    (click (test-id "open-c2"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (change (label "Assigned to me") "mine")
    (change (label "Unread") "unread")
    (change (label "All") "all")

    ; optimistic sending

    (click (test-id "open-c1"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (expect-text (test-id "thread-title") "Card declined")
    (expect-disabled (role button :name "Send message") true)
    (fill (label "Message") "Refund issued")
    (expect-value (label "Message") "Refund issued")
    (expect-disabled (role button :name "Send message") false)
    (mark-metrics)
    (click (role button :name "Send message"))
    (expect-value (label "Message") "")
    (expect-pending-task "send" 1)
    (expect-text (test-id "send-state") "Sending…")
    (expect-text (test-id "inbox-summary") "Conversations3Unread0Sending1")
    (expect-visible (role region :name "Message p1"))
    (expect-text (test-id "body-p1") "Refund issued")
    (expect-text (test-id "mstate-p1") "sending")
    (expect-disabled (role button :name "Send message") true)
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    ; A poll lands while the send is still in flight. The snapshot does not carry
    ; the client id yet, so the optimistic row must survive untouched - not dropped
    ; by the newer server truth, and not duplicated by it either.
    (tick-interval 4000)
    (expect-text (test-id "poll-count") "Polls issued: 1")
    (expect-pending-task "inbox" 1)
    (mark-metrics)
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-visible (role region :name "Message p1"))
    (expect-text (test-id "body-p1") "Refund issued")
    (expect-text (test-id "mstate-p1") "sending")
    (expect-text (test-id "inbox-summary") "Conversations3Unread0Sending1")
    (expect-pending-task "send" 1)
    (resolve-task "send" "p1")
    (expect-pending-task "send" 0)
    (expect-text (test-id "send-state") "Sent")
    (expect-text (test-id "mstate-p1") "sent")
    (expect-text (test-id "inbox-summary") "Conversations3Unread0Sending0")
  )
)
