(test "Conduit — Article writes: editor create/edit, comments, and delete"
  (setup
    (manual-effects)
    (local-storage "conduit.jwt" "jwt.conduit.kim")
    (local-storage "conduit.username" "kim")
    (initial-location "/roc-signals/examples-web/conduit/#/editor/keyed-lists-without-tears")
  )
  (steps
    ; Article writes: editor create/edit, comments, and delete
    (expect-document-title "Edit article - Conduit")
    (expect-visible (role heading :name "Edit article"))
    (expect-pending-effects 1)
    (stub-http "editor-load response" :url "/api/articles/keyed-lists-without-tears" :status 200 :body "{\"article\":{\"slug\":\"keyed-lists-without-tears\",\"title\":\"Keyed lists without tears\",\"description\":\"Field notes on stable row identity.\",\"body\":\"Rows stay attached to their signals.\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}}")
    (run-effect 1)
    (expect-visible (text "Current title: Keyed lists without tears"))
    (expect-visible (text "Current tags: signals, webdev"))
    (click (role button :name "Update Article"))
    (expect-pending-effects 1)
    (stub-http "editor response" :url "/api/articles/keyed-lists-without-tears" :status 422 :body "{\"errors\":{\"body\":[\"must change at least one field\"]}}")
    (run-effect 2)
    (expect-visible (text "body must change at least one field"))
    (fill (label "Title") "Edited conduit article")
    (click (role button :name "Update Article"))
    (expect-pending-effects 1)
    (stub-http "editor response" :url "/api/articles/keyed-lists-without-tears" :status 200 :body "{\"article\":{\"slug\":\"edited-conduit-article\",\"title\":\"Edited conduit article\",\"description\":\"Field notes on stable row identity.\",\"body\":\"Rows stay attached to their signals.\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}}")
    (run-effect 3)
    (expect-current-location "/roc-signals/examples-web/conduit/#/article/edited-conduit-article")
    (expect-pending-effects 2)
    (stub-http "article response" :url "/api/articles/edited-conduit-article" :status 200 :body "{\"article\":{\"slug\":\"edited-conduit-article\",\"title\":\"Edited conduit article\",\"description\":\"Field notes on stable row identity.\",\"body\":\"Rows stay attached to their signals.\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}}")
    (run-effect 4)
    (expect-pending-effects 1)
    (stub-http "article-comments response" :url "/api/articles/edited-conduit-article/comments" :status 200 :body "{\"comments\":[]}")
    (run-effect 5)
    (navigate "/roc-signals/examples-web/conduit/#/editor")
    (expect-document-title "New article - Conduit")
    (expect-visible (role heading :name "New article"))
    (click (role button :name "Publish Article"))
    (expect-pending-effects 1)
    (stub-http "editor response" :url "/api/articles" :status 422 :body "{\"errors\":{\"title\":[\"can't be blank\"],\"description\":[\"can't be blank\"],\"body\":[\"can't be blank\"]}}")
    (run-effect 6)
    (expect-visible (text "title can't be blank"))
    (expect-visible (text "description can't be blank"))
    (expect-visible (text "body can't be blank"))
    (fill (label "Title") "Conduit write path")
    (fill (label "Description") "Server-confirmed mutation")
    (fill (label "Body") "Published only after the task resolves.")
    (fill (label "Tags") "signals, realworld")
    (click (role button :name "Publish Article"))
    (expect-pending-effects 1)
    (stub-http "editor response" :url "/api/articles" :status 201 :body "{\"article\":{\"slug\":\"conduit-write-path\",\"title\":\"Conduit write path\",\"description\":\"Server-confirmed mutation\",\"body\":\"Published only after the task resolves.\",\"tagList\":[\"signals\",\"realworld\"],\"createdAt\":\"2026-07-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":0,\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 7)
    (expect-current-location "/roc-signals/examples-web/conduit/#/article/conduit-write-path")
    (expect-document-title "conduit-write-path - Conduit")
    (expect-pending-effects 2)
    (stub-http "article response" :url "/api/articles/conduit-write-path" :status 200 :body "{\"article\":{\"slug\":\"conduit-write-path\",\"title\":\"Conduit write path\",\"description\":\"Server-confirmed mutation\",\"body\":\"Published only after the task resolves.\",\"tagList\":[\"signals\",\"realworld\"],\"createdAt\":\"2026-07-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":0,\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 8)
    (expect-visible (text "Conduit write path"))
    (expect-visible (text "Published only after the task resolves."))
    (expect-pending-effects 1)
    (stub-http "article-comments response" :url "/api/articles/conduit-write-path/comments" :status 200 :body "{\"comments\":[]}")
    (run-effect 9)
    (expect-visible (role button :name "Favorite Article (0)"))
    (click (role button :name "Favorite Article (0)"))
    (expect-pending-effects 1)
    (stub-http "article-favorite response" :url "/api/articles/conduit-write-path/favorite" :status 200 :body "{\"article\":{\"slug\":\"conduit-write-path\",\"title\":\"Conduit write path\",\"description\":\"Server-confirmed mutation\",\"body\":\"Published only after the task resolves.\",\"tagList\":[\"signals\",\"realworld\"],\"createdAt\":\"2026-07-01T08:00:00.000Z\",\"favorited\":true,\"favoritesCount\":1,\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 10)
    (expect-pending-effects 1)
    (stub-http "article response" :url "/api/articles/conduit-write-path" :status 200 :body "{\"article\":{\"slug\":\"conduit-write-path\",\"title\":\"Conduit write path\",\"description\":\"Server-confirmed mutation\",\"body\":\"Published only after the task resolves.\",\"tagList\":[\"signals\",\"realworld\"],\"createdAt\":\"2026-07-01T08:00:00.000Z\",\"favorited\":true,\"favoritesCount\":1,\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 11)
    (expect-visible (role button :name "Unfavorite Article (1)"))
    (expect-pending-effects 0)
    (click (role button :name "Unfavorite Article (1)"))
    (expect-pending-effects 1)
    (stub-http "article-favorite response" :url "/api/articles/conduit-write-path/favorite" :status 200 :body "{\"article\":{\"slug\":\"conduit-write-path\",\"title\":\"Conduit write path\",\"description\":\"Server-confirmed mutation\",\"body\":\"Published only after the task resolves.\",\"tagList\":[\"signals\",\"realworld\"],\"createdAt\":\"2026-07-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":0,\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 12)
    (expect-pending-effects 1)
    (stub-http "article response" :url "/api/articles/conduit-write-path" :status 200 :body "{\"article\":{\"slug\":\"conduit-write-path\",\"title\":\"Conduit write path\",\"description\":\"Server-confirmed mutation\",\"body\":\"Published only after the task resolves.\",\"tagList\":[\"signals\",\"realworld\"],\"createdAt\":\"2026-07-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":0,\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 13)
    (expect-visible (role button :name "Favorite Article (0)"))
    (expect-visible (role heading :name "Comments"))
    (expect-pending-effects 0)
    (click (role button :name "Post Comment"))
    (expect-pending-effects 1)
    (stub-http "comment-create response" :url "/api/articles/conduit-write-path/comments" :status 422 :body "{\"errors\":{\"body\":[\"can't be blank\"]}}")
    (run-effect 14)
    (expect-visible (text "body can't be blank"))
    (fill (label "Comment") "Server-confirmed comment.")
    (click (role button :name "Post Comment"))
    (expect-pending-effects 1)
    (stub-http "comment-create response" :url "/api/articles/conduit-write-path/comments" :status 201 :body "{\"comment\":{\"id\":7,\"createdAt\":\"2026-07-01T09:00:00.000Z\",\"updatedAt\":\"2026-07-01T09:00:00.000Z\",\"body\":\"Server-confirmed comment.\",\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}}")
    (run-effect 15)
    (expect-pending-effects 1)
    (stub-http "article-comments response" :url "/api/articles/conduit-write-path/comments" :status 200 :body "{\"comments\":[{\"id\":7,\"createdAt\":\"2026-07-01T09:00:00.000Z\",\"updatedAt\":\"2026-07-01T09:00:00.000Z\",\"body\":\"Server-confirmed comment.\",\"author\":{\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\",\"following\":false}}]}")
    (run-effect 16)
    (expect-visible (text "Server-confirmed comment."))
    (expect-visible (role button :name "Delete Comment"))
    (click (role button :name "Delete Comment"))
    (expect-pending-effects 1)
    (stub-http "comment-delete response" :url "/api/articles/conduit-write-path/comments/7" :status 204 :body "")
    (run-effect 17)
    (expect-pending-effects 1)
    (stub-http "article-comments response" :url "/api/articles/conduit-write-path/comments" :status 200 :body "{\"comments\":[]}")
    (run-effect 18)
    (expect-absent (text "Server-confirmed comment."))
    (expect-visible (role button :name "Delete Article"))
    (click (role button :name "Delete Article"))
    (expect-pending-effects 1)
    (stub-http "article-delete response" :url "/api/articles/conduit-write-path" :status 204 :body "")
    (run-effect 19)
    (expect-current-location "/roc-signals/examples-web/conduit/#/")
    (expect-document-title "Conduit")
    (expect-pending-effects 2)
    (navigate "/roc-signals/examples-web/conduit/#/definitely/not/a/route")
    (expect-current-location "/roc-signals/examples-web/conduit/#/definitely/not/a/route")
    (expect-document-title "Page not found - Conduit")
    (expect-visible (role heading :name "Page not found"))
    (click (role link :name "Take me home"))
    (expect-current-location "/roc-signals/examples-web/conduit/#/")
    (expect-document-title "Conduit")
    (expect-pending-effects 4)
    (expect-visible (role link :name "Your Feed"))
  )
)
