(test "Conduit — back and forward restore the profile tab and its requests"
  (setup
    (manual-effects)
    (initial-location "/roc-signals/examples-web/conduit/#/profile/anna")
  )
  (steps
    (stub-http "profile" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 1)
    (stub-http "author articles" :url "/api/articles?limit=20&offset=0&author=anna" :status 200 :body "{\"articles\":[],\"articlesCount\":0}")
    (run-effect 2)
    (click (role link :name "Favorited Articles"))
    (stub-http "favorites profile" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 3)
    (stub-http "favorites" :url "/api/articles?limit=20&offset=0&favorited=anna" :status 200 :body "{\"articles\":[],\"articlesCount\":0}")
    (run-effect 4)

    (history-back)
    (expect-current-location "/roc-signals/examples-web/conduit/#/profile/anna")
    (expect-document-title "@anna - Conduit")
    (expect-pending-effects 2)
    (stub-http "restored profile" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 5)
    (stub-http "restored author articles" :url "/api/articles?limit=20&offset=0&author=anna" :status 200 :body "{\"articles\":[{\"slug\":\"keyed-lists-without-tears\",\"title\":\"Keyed lists without tears\",\"description\":\"Field notes on stable row identity.\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}},{\"slug\":\"latest-wins-requests\",\"title\":\"Latest-wins request replacement\",\"description\":\"Only the newest request may land.\",\"tagList\":[\"performance\"],\"createdAt\":\"2026-06-03T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":1,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}],\"articlesCount\":2}")
    (run-effect 6)
    (expect-visible (text "Keyed lists without tears"))
    (history-forward)
    (expect-current-location "/roc-signals/examples-web/conduit/#/profile/anna/favorites")
    (expect-document-title "@anna favorites - Conduit")
    (expect-pending-effects 2)
  )
)
