(test "Conduit — Deep link cold mounts the article page: loading, then content"
  (setup
    (manual-effects)
    ; Seeded session restores before first render (namespaced keys)
    (local-storage "conduit.jwt" "jwt.conduit.kim")
    (local-storage "conduit.username" "kim")
    ; Deep link cold mounts the article page: loading, then content
    (initial-location "/roc-signals/examples-web/conduit/#/article/keyed-lists-without-tears")
  )
  (steps
    (expect-current-location "/roc-signals/examples-web/conduit/#/article/keyed-lists-without-tears")
    (expect-document-title "keyed-lists-without-tears - Conduit")
    (expect-pending-effects 2)
    (expect-visible (text "Loading article..."))
    (stub-http "article" :url "/api/articles/keyed-lists-without-tears" :status 200 :body "{\"article\":{\"slug\":\"keyed-lists-without-tears\",\"title\":\"Keyed lists without tears\",\"description\":\"Field notes on stable row identity.\",\"body\":\"# Keyed lists\\n\\nStable keys keep row state.\\n\\n- first point\\n  - nested point\\n\\n```\\nsignals check --keys\\n```\\n\\n**bold move** and `inline code` and [docs](https://example.test/docs)\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}}")
    (run-effect 1)
    (expect-pending-effects 1)
    (expect-visible (text "Keyed lists without tears"))
    (expect-visible (text "Keyed lists"))
    (expect-visible (text "Stable keys keep row state."))
    (expect-visible (text "first point"))
    (expect-visible (text "nested point"))
    (expect-visible (text "signals check --keys"))
    (expect-visible (text "bold move"))
    (expect-visible (text "inline code"))
    (expect-visible (text "docs"))
    (expect-visible (role link :name "anna"))
    (expect-visible (text "June 1, 2026 | 2 favorites"))
    (expect-document-title "Keyed lists without tears - Conduit")
    (expect-visible (role link :name "kim"))
    (expect-visible (role link :name "Settings"))
    (expect-absent (role link :name "Sign in"))
    ; Comments were admitted with the article and can finish independently.
    (stub-http "empty comments" :url "/api/articles/keyed-lists-without-tears/comments" :status 200 :body "{\"comments\":[]}")
    (run-effect 2)
    (expect-pending-effects 0)
    (expect-visible (role heading :name "Comments"))
  )
)
