(test "Conduit — Home: both fetches pending, then tags and feed render"
  (setup
    (manual-effects)
    ; Seeded session restores before first render (namespaced keys)
    (local-storage "conduit.jwt" "jwt.conduit.kim")
    (local-storage "conduit.username" "kim")
    (initial-location "/roc-signals/examples-web/conduit/#/")
  )
  (steps

    ; Home: both fetches pending, then tags and feed render
    (expect-current-location "/roc-signals/examples-web/conduit/#/")
    (expect-document-title "Conduit")
    (expect-pending-effects 2)
    (expect-visible (text "Loading articles..."))
    (expect-visible (text "Loading tags..."))
    (stub-http "tags" :url "/api/tags" :status 200 :body "{\"tags\":[\"signals\",\"roc\",\"webdev\"]}")
    (run-effect 2)
    (expect-visible (role link :name "webdev"))
    (stub-http "feed" :url "/api/articles?limit=20&offset=0" :status 200 :body "{\"articles\":[{\"slug\":\"keyed-lists-without-tears\",\"title\":\"Keyed lists without tears\",\"description\":\"Field notes on stable row identity.\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}},{\"slug\":\"budgeting-patches\",\"title\":\"Budgeting patches per interaction\",\"description\":\"Counting the work each click does.\",\"tagList\":[\"roc\"],\"createdAt\":\"2026-06-02T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":0,\"author\":{\"username\":\"max\",\"bio\":\"Queues and latency.\",\"image\":\"https://example.test/avatars/max.png\",\"following\":false}},{\"slug\":\"latest-wins-requests\",\"title\":\"Latest-wins request replacement\",\"description\":\"Only the newest request may land.\",\"tagList\":[\"performance\"],\"createdAt\":\"2026-06-03T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":1,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}],\"articlesCount\":23}")
    (run-effect 1)
    (expect-visible (role link :name "Your Feed"))
    (expect-visible (text "Keyed lists without tears"))
    (expect-visible (text "Budgeting patches per interaction"))
    (expect-visible (text "Latest-wins request replacement"))
    (expect-visible (text "June 1, 2026"))
    (expect-visible (role button :name "Favorite Keyed lists without tears (2)"))
    (expect-pending-effects 0)
  )
)
