(test "Conduit — Login: 422 envelope renders, success persists the session"
  (setup
    (manual-effects)
    (initial-location "/roc-signals/examples-web/conduit/#/login")
  )
  (steps
    ; Login: 422 envelope renders, success persists the session
    (fill (label "Email") "kim@conduit.test")
    (fill (label "Password") "wrong")
    (click (role button :name "Sign in"))
    (expect-pending-effects 1)
    (stub-http "login response" :url "/api/users/login" :status 422 :body "{\"errors\":{\"email or password\":[\"is invalid\"]}}")
    (run-effect 1)
    (expect-visible (text "email or password is invalid"))
    (fill (label "Password") "secret-kim")
    (click (role button :name "Sign in"))
    (expect-pending-effects 1)
    (stub-http "login response" :url "/api/users/login" :status 200 :body "{\"user\":{\"email\":\"kim@conduit.test\",\"token\":\"jwt.conduit.kim\",\"username\":\"kim\",\"bio\":\"Reader.\",\"image\":\"\"}}")
    (run-effect 2)
    (expect-local-storage "conduit.jwt" "jwt.conduit.kim")
    (expect-local-storage "conduit.username" "kim")
    (expect-current-location "/roc-signals/examples-web/conduit/#/")
    (expect-visible (role link :name "kim"))
    (expect-visible (role link :name "Your Feed"))
    ; Login currently admits two feed generations and the tags request.
    (expect-pending-effects 3)
    (expect-visible (text "Loading articles..."))
    (expect-visible (text "Loading tags..."))
    (stub-http "feed after login" :url "/api/articles?limit=20&offset=0" :status 200 :body "{\"articles\":[],\"articlesCount\":0}")
    (run-effect 3)
    (stub-http "tags after login" :url "/api/tags" :status 200 :body "{\"tags\":[]}")
    (run-effect 4)
    (stub-http "current feed after login" :url "/api/articles?limit=20&offset=0" :status 200 :body "{\"articles\":[],\"articlesCount\":0}")
    (run-effect 5)
    (expect-pending-effects 0)
  )
)
