(test "Conduit — Profile page: profile card plus author articles, then favorites tab"
  (setup
    (manual-effects)
    (local-storage "conduit.jwt" "jwt.conduit.kim")
    (local-storage "conduit.username" "kim")
    (initial-location "/roc-signals/examples-web/conduit/#/profile/anna")
  )
  (steps
    ; Profile page: profile card plus author articles, then favorites tab

    (expect-document-title "@anna - Conduit")
    (expect-pending-effects 2)
    (expect-pending-effects 2)
    (expect-visible (text "Loading profile..."))
    (stub-http "profile response" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 1)
    (expect-visible (text "@anna"))
    (expect-visible (text "Signals platform notes."))
    (expect-visible (role button :name "Follow anna"))
    (click (role button :name "Follow anna"))
    (expect-pending-effects 2)
    (stub-http "profile-follow response" :url "/api/profiles/anna/follow" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":true}}")
    (run-effect 3)
    (expect-pending-effects 2)
    (stub-http "profile response" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":true}}")
    (run-effect 4)
    (expect-visible (role button :name "Unfollow anna"))
    (click (role button :name "Unfollow anna"))
    (expect-pending-effects 2)
    (stub-http "profile-follow response" :url "/api/profiles/anna/follow" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 5)
    (expect-pending-effects 2)
    (stub-http "profile response" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 6)
    (expect-visible (role button :name "Follow anna"))
    (stub-http "profile-articles response" :url "/api/articles?limit=20&offset=0&author=anna" :status 200 :body "{\"articles\":[{\"slug\":\"keyed-lists-without-tears\",\"title\":\"Keyed lists without tears\",\"description\":\"Field notes on stable row identity.\",\"tagList\":[\"signals\",\"webdev\"],\"createdAt\":\"2026-06-01T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":2,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}},{\"slug\":\"latest-wins-requests\",\"title\":\"Latest-wins request replacement\",\"description\":\"Only the newest request may land.\",\"tagList\":[\"performance\"],\"createdAt\":\"2026-06-03T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":1,\"author\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}],\"articlesCount\":2}")
    (run-effect 2)
    (expect-visible (text "Keyed lists without tears"))
    (expect-visible (text "Latest-wins request replacement"))
    (click (role link :name "Favorited Articles"))
    (expect-current-location "/roc-signals/examples-web/conduit/#/profile/anna/favorites")
    (expect-document-title "@anna favorites - Conduit")
    (expect-pending-effects 2)
    (expect-pending-effects 2)
    (stub-http "profile response" :url "/api/profiles/anna" :status 200 :body "{\"profile\":{\"username\":\"anna\",\"bio\":\"Signals platform notes.\",\"image\":\"https://example.test/avatars/anna.png\",\"following\":false}}")
    (run-effect 7)
    (stub-http "profile-articles response" :url "/api/articles?limit=20&offset=0&favorited=anna" :status 200 :body "{\"articles\":[{\"slug\":\"deep-links-that-survive\",\"title\":\"Deep links that survive reloads\",\"description\":\"Routing that owns its URLs.\",\"tagList\":[\"release\"],\"createdAt\":\"2026-06-04T08:00:00.000Z\",\"favorited\":false,\"favoritesCount\":3,\"author\":{\"username\":\"max\",\"bio\":\"Queues and latency.\",\"image\":\"https://example.test/avatars/max.png\",\"following\":false}}],\"articlesCount\":1}")
    (run-effect 8)
    (expect-visible (text "Deep links that survive reloads"))
  )
)
