(test "Number input control"
  (steps
    ; Number input draft/commit scenario

    (expect-visible (role heading :name "Number Input Control"))
    (expect-attr (role region :name "Number Input Control") data-fixture "number-input-control")
    (expect-attr (label "Seats") type "number")
    (expect-attr (label "Seats") id "seat-count")
    (expect-attr (label "Seats") min "0")
    (expect-attr (label "Seats") step "1")
    (expect-value (label "Seats") "3")
    (expect-text (text "Draft seats: 3") "Draft seats: 3")
    (expect-text (text "Committed seats: 3") "Committed seats: 3")
    (expect-text (text "Commits: 0") "Commits: 0")
    (expect-text (text "Commit errors: 0") "Commit errors: 0")
    (focus (label "Seats"))
    (fill (label "Seats") "12")
    (expect-value (label "Seats") "12")
    (expect-text (text "Draft seats: 12") "Draft seats: 12")
    (expect-text (text "Committed seats: 3") "Committed seats: 3")
    (expect-text (text "Commits: 0") "Commits: 0")
    (blur (label "Seats"))
    (expect-value (label "Seats") "12")
    (expect-text (text "Committed seats: 12") "Committed seats: 12")
    (expect-text (text "Commits: 1") "Commits: 1")
    (focus (label "Seats"))
    (fill (label "Seats") "")
    (expect-value (label "Seats") "")
    (expect-text (text "Draft seats: ") "Draft seats: ")
    (expect-text (text "Committed seats: 12") "Committed seats: 12")
    (blur (label "Seats"))
    (expect-value (label "Seats") "")
    (expect-text (text "Committed seats: 12") "Committed seats: 12")
    (expect-text (text "Commit errors: 1") "Commit errors: 1")
  )
)
