(test "Form builder — a single field form"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))
    (click (role button :name "Add number field"))
    (fill (label "Answer f3") "abc")
    (fill (label "Answer f3") "42")
    (fill (label "Maximum f3") "10")
    (fill (label "Minimum f3") "20")
    (fill (label "Minimum f3") "2x")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (fill (label "Answer f3") "5")
    (fill (label "Answer f3") "25")
    (click (role button :name "Add select field"))
    (fill (label "Options f4") "Small, Medium, Large")
    (select-option (label "Answer f4") "Medium")
    (fill (label "Options f4") "Small, Large")
    (select-option (label "Answer f4") "Large")
    (click (role button :name "Add checkbox field"))
    (check (label "Required f5"))
    (check (label "Answer f5"))
    (click (role button :name "Add text field"))
    (click (role button :name "Add email field"))
    (mark-metrics)
    (click (role button :name "Move up f2"))
    (click (role button :name "Move down f2"))
    (click (role button :name "Move up f1"))
    (click (role button :name "Move up f1"))
    (click (role button :name "Move down f7"))
    (check (label "Required f6"))
    (mark-metrics)
    (click (role button :name "Delete f6"))
    (click (role button :name "Clear preview answers"))
    (click (role button :name "Delete f1"))
    (click (role button :name "Delete f2"))
    (click (role button :name "Delete f3"))
    (click (role button :name "Delete f4"))
    (click (role button :name "Delete f5"))
    (click (role button :name "Delete f7"))

    ; a single field form
    (click (role button :name "Add text field"))
    (expect-text (test-id "designer-status") "Designer status: 1 field")
    (expect-text (test-id "preview-status") "Preview status: 1 field, 0 problems")
    (expect-absent (text "No fields yet. Add a field to start designing."))
    (expect-text (test-id "submittable-state") "Form is submittable")
    (expect-disabled (role button :name "Submit form") false)
    (click (role button :name "Submit form"))
    (expect-text (test-id "submissions-count") "Submissions: 2")
  )
)
