(test "Form builder — adding a select field"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))
    (click (role button :name "Add number field"))
    (fill (label "Answer f3") "abc")
    (fill (label "Answer f3") "42")
    (fill (label "Maximum f3") "10")
    (fill (label "Minimum f3") "20")
    (fill (label "Minimum f3") "2x")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (fill (label "Answer f3") "5")
    (fill (label "Answer f3") "25")

    ; adding a select field
    (click (role button :name "Add select field"))
    (expect-visible (role region :name "Field f4"))
    (expect-visible (label "Options f4"))
    (expect-absent (label "Minimum f4"))
    (expect-absent (label "Maximum f4"))
    ; a select with zero options can never be answered, so it blocks submission
    (expect-text (test-id "field-f4-summary") "Select 4 field: Select - optional - Rule error: select has no options")
    (expect-text (test-id "preview-f4-verdict") "Rule error: select has no options")
    (expect-text (test-id "submittable-state") "Form is not submittable")
    (fill (label "Options f4") "Small, Medium, Large")
    (expect-text (test-id "preview-f4-verdict") "Valid")
    (expect-text (test-id "submittable-state") "Form is submittable")
    (select-option (label "Answer f4") "Medium")
    (expect-value (label "Answer f4") "Medium")
    (expect-text (test-id "preview-f4-verdict") "Valid")
    ; removing the option the preview already holds invalidates the answer
    (fill (label "Options f4") "Small, Large")
    (expect-text (test-id "preview-f4-verdict") "Choose one of the configured options")
    (expect-text (test-id "submittable-state") "Form is not submittable")
    (select-option (label "Answer f4") "Large")
    (expect-value (label "Answer f4") "Large")
    (expect-text (test-id "preview-f4-verdict") "Valid")
    (expect-text (test-id "submittable-state") "Form is submittable")
  )
)
