(test "Form builder — adding a number field"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))

    ; adding a number field
    (click (role button :name "Add number field"))
    (expect-text (test-id "designer-status") "Designer status: 3 fields")
    (expect-visible (role region :name "Field f3"))
    (expect-visible (role region :name "Preview field f3"))
    (expect-text (test-id "field-f3-summary") "Number 3 field: Number - optional")
    (expect-text (test-id "preview-f3-label") "Number 3")
    (expect-text (test-id "preview-f3-verdict") "Valid")
    (expect-text (test-id "submittable-state") "Form is submittable")
    (fill (label "Answer f3") "abc")
    (expect-text (test-id "preview-f3-verdict") "Enter a whole number")
    (fill (label "Answer f3") "42")
    (expect-text (test-id "preview-f3-verdict") "Valid")
    (fill (label "Maximum f3") "10")
    (expect-text (test-id "preview-f3-verdict") "Must be at most 10")
    (expect-text (test-id "submittable-state") "Form is not submittable")
    ; contradictory rule: minimum greater than maximum
    (fill (label "Minimum f3") "20")
    (expect-text (test-id "field-f3-summary") "Number 3 field: Number - optional - Rule error: minimum is greater than maximum")
    (expect-text (test-id "preview-f3-verdict") "Rule error: minimum is greater than maximum")
    (expect-attr (label "Minimum f3") aria-invalid "")
    (expect-attr (label "Maximum f3") aria-invalid "")
    (expect-text (test-id "submittable-state") "Form is not submittable")
    ; a non-numeric bound is its own rule error
    (fill (label "Minimum f3") "2x")
    (expect-text (test-id "preview-f3-verdict") "Rule error: minimum is not a number")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (expect-no-attr (label "Minimum f3") aria-invalid)
    (expect-text (test-id "preview-f3-verdict") "Valid")
    (fill (label "Answer f3") "5")
    (expect-text (test-id "preview-f3-verdict") "Must be at least 20")
    (fill (label "Answer f3") "25")
    (expect-text (test-id "preview-f3-verdict") "Valid")
    (expect-text (test-id "submittable-state") "Form is submittable")
  )
)
