(test "Form builder — adding the remaining field types"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))
    (click (role button :name "Add number field"))
    (fill (label "Answer f3") "abc")
    (fill (label "Answer f3") "42")
    (fill (label "Maximum f3") "10")
    (fill (label "Minimum f3") "20")
    (fill (label "Minimum f3") "2x")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (fill (label "Answer f3") "5")
    (fill (label "Answer f3") "25")
    (click (role button :name "Add select field"))
    (fill (label "Options f4") "Small, Medium, Large")
    (select-option (label "Answer f4") "Medium")
    (fill (label "Options f4") "Small, Large")
    (select-option (label "Answer f4") "Large")
    (click (role button :name "Add checkbox field"))
    (check (label "Required f5"))
    (check (label "Answer f5"))

    ; adding the remaining field types
    (click (role button :name "Add text field"))
    (click (role button :name "Add email field"))
    (expect-text (test-id "designer-status") "Designer status: 7 fields")
    (expect-visible (role region :name "Field f6"))
    (expect-visible (role region :name "Field f7"))
    (expect-text (test-id "field-f6-summary") "Text 6 field: Text - optional")
    (expect-text (test-id "field-f7-summary") "Email 7 field: Email - optional")
    (expect-text (test-id "preview-status") "Preview status: 7 fields, 0 problems")
  )
)
