(test "Form builder — adding a checkbox field"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))
    (click (role button :name "Add number field"))
    (fill (label "Answer f3") "abc")
    (fill (label "Answer f3") "42")
    (fill (label "Maximum f3") "10")
    (fill (label "Minimum f3") "20")
    (fill (label "Minimum f3") "2x")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (fill (label "Answer f3") "5")
    (fill (label "Answer f3") "25")
    (click (role button :name "Add select field"))
    (fill (label "Options f4") "Small, Medium, Large")
    (select-option (label "Answer f4") "Medium")
    (fill (label "Options f4") "Small, Large")
    (select-option (label "Answer f4") "Large")

    ; adding a checkbox field
    (click (role button :name "Add checkbox field"))
    (expect-visible (role region :name "Field f5"))
    (expect-checked (label "Answer f5") false)
    (expect-text (test-id "preview-f5-verdict") "Valid")
    (check (label "Required f5"))
    (expect-text (test-id "preview-f5-verdict") "Must be checked")
    (expect-text (test-id "submittable-state") "Not ready")
    (check (label "Answer f5"))
    (expect-checked (label "Answer f5") true)
    (expect-text (test-id "preview-f5-verdict") "Valid")
    (expect-text (test-id "submittable-state") "Ready to submit")
  )
)
