(test "Form builder — initial mount"
  (steps
    ; initial mount
    (expect-visible (role heading :name "Form Builder"))
    (expect-visible (role region :name "Form Builder"))
    (expect-visible (role region :name "Field toolbar"))
    (expect-visible (role heading :name "Add a field"))
    (expect-visible (role region :name "Field designer"))
    (expect-visible (role heading :name "Field designer"))
    (expect-visible (role region :name "Live preview"))
    (expect-visible (role heading :name "Live preview"))
    (expect-visible (role form :name "Preview form"))
    (expect-visible (role button :name "Add text field"))
    (expect-visible (role button :name "Add number field"))
    (expect-visible (role button :name "Add email field"))
    (expect-visible (role button :name "Add select field"))
    (expect-visible (role button :name "Add checkbox field"))
    (expect-visible (role button :name "Clear preview answers"))
    (expect-text (test-id "designer-status") "Designer status: 2 fields")
    (expect-visible (role region :name "Field f1"))
    (expect-visible (role region :name "Field f2"))
    (expect-text (test-id "field-f1-summary") "Full name field: Text - required")
    (expect-text (test-id "field-f2-summary") "Work email field: Email - required")
    (expect-value (label "Label f1") "Full name")
    (expect-checked (label "Required f1") true)
    (expect-value (label "Minimum f1") "2")
    (expect-value (label "Maximum f1") "")
    (expect-absent (label "Options f1"))
    (expect-value (label "Label f2") "Work email")
    (expect-checked (label "Required f2") true)
    (expect-visible (role button :name "Move up f1"))
    (expect-visible (role button :name "Move down f1"))
    (expect-visible (role button :name "Delete f1"))
    (expect-visible (role region :name "Preview field f1"))
    (expect-visible (role region :name "Preview field f2"))
    (expect-text (test-id "preview-f1-label") "Full name (required)")
    (expect-text (test-id "preview-f2-label") "Work email (required)")
    (expect-value (label "Answer f1") "")
    (expect-value (label "Answer f2") "")
    (expect-attr (label "Answer f1") aria-invalid "")
    (expect-text (test-id "preview-f1-verdict") "This field is required")
    (expect-text (test-id "preview-f2-verdict") "This field is required")
    (expect-text (test-id "preview-status") "Preview status: 2 fields, 2 problems")
    (expect-text (test-id "submittable-state") "Form is not submittable")
    (expect-text (test-id "submissions-count") "Submissions: 0")
    (expect-disabled (role button :name "Submit form") true)
  )
)
