(test "Form builder — reordering"
  (steps
    ; Given the state established by earlier scenarios
    (fill (label "Answer f1") "Ada")
    (fill (label "Answer f2") "ada@example")
    (fill (label "Answer f2") "ada@example.com")
    (click (role button :name "Submit form"))
    (fill (label "Minimum f1") "5")
    (fill (label "Minimum f1") "2")
    (mark-metrics)
    (fill (label "Label f1") "Given name")
    (uncheck (label "Required f2"))
    (check (label "Required f2"))
    (click (role button :name "Add number field"))
    (fill (label "Answer f3") "abc")
    (fill (label "Answer f3") "42")
    (fill (label "Maximum f3") "10")
    (fill (label "Minimum f3") "20")
    (fill (label "Minimum f3") "2x")
    (fill (label "Maximum f3") "50")
    (fill (label "Minimum f3") "20")
    (fill (label "Answer f3") "5")
    (fill (label "Answer f3") "25")
    (click (role button :name "Add select field"))
    (fill (label "Options f4") "Small, Medium, Large")
    (select-option (label "Answer f4") "Medium")
    (fill (label "Options f4") "Small, Large")
    (select-option (label "Answer f4") "Large")
    (click (role button :name "Add checkbox field"))
    (check (label "Required f5"))
    (check (label "Answer f5"))
    (click (role button :name "Add text field"))
    (click (role button :name "Add email field"))

    ; reordering
    ; Reordering is a list permutation, not a rebuild: rows keep their identity and
    ; every answer travels with its field.
    (mark-metrics)
    (click (role button :name "Move up f2"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta rows_reused 14)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (expect-value (label "Answer f2") "ada@example.com")
    (expect-value (label "Answer f4") "Large")
    (expect-checked (label "Answer f5") true)
    (expect-value (label "Label f1") "Given name")
    (expect-text (test-id "preview-status") "0")
    (click (role button :name "Move down f2"))
    (expect-value (label "Answer f2") "ada@example.com")
    (expect-value (label "Answer f1") "Ada")
    ; moving the first field up is a no-op
    (click (role button :name "Move up f1"))
    (click (role button :name "Move up f1"))
    (expect-text (test-id "designer-status") "7")
    (expect-value (label "Answer f1") "Ada")
    ; moving the last field down is a no-op
    (click (role button :name "Move down f7"))
    (expect-text (test-id "designer-status") "7")
  )
)
