(test "Sparse append followed by compound disposal can be repeated"
  (steps
    (click (role button :name "Add"))
    (expect-text (test-id "rows") "abc")
    (mark-metrics)
    (click (role button :name "Delete"))
    (expect-text (test-id "rows") "ab")
    (expect-visible (text "Closed"))
    (expect-absent (text "Confirm"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta stream_nodes_scanned 0)
    (expect-metric-delta active_graph_records_rebuilt 0)
    (click (role button :name "Add"))
    (expect-text (test-id "rows") "abc")
    (expect-visible (text "Confirm"))
    (click (role button :name "Delete"))
    (expect-text (test-id "rows") "ab")
    (expect-visible (text "Closed"))))
