(test "Availability picker — adding a slot: one new row, and the draft clears via State.set_cmd"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Mark review available"))
    (click (role button :name "Mark review busy"))
    (mark-metrics)
    (select-option (label "Timezone") "auckland")
    (click (role button :name "Mark review available"))
    (select-option (label "Timezone") "kolkata")
    (select-option (label "Timezone") "nyc")
    (fill (label "Slot name") "Client call")
    (fill (label "Start time") "25:00")
    (fill (label "Start time") "0830")
    (fill (label "Start time") "08:60")
    (fill (label "Start time") "08:30")
    (fill (label "Length") "0")
    (fill (label "Length") "abc")
    (fill (label "Length") "45")
    (select-option (label "Day") "Fri")

    ; adding a slot: one new row, and the draft clears via State.set_cmd
    (mark-metrics)
    (click (role button :name "Add slot"))
    (expect-visible (role region :name "Slot s6"))
    (expect-text (test-id "title-s6") "Client call")
    (expect-text (test-id "when-s6") "Fri 08:30-09:15")
    (expect-text (test-id "status-s6") "Unmarked")
    (expect-text (test-id "summary") "4h 0m")
    (expect-text (test-id "stat-slots") "6")
    (expect-text (test-id "stat-conflicts") "0")
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-value (label "Slot name") "")
    (expect-value (label "Day") "Mon")
    (expect-value (label "Start time") "09:00")
    (expect-value (label "Length") "30")
    (expect-text (test-id "draft-status") "Enter a name for the new slot")
    (expect-disabled (role button :name "Add slot") true)
    ; the typed time was a New York wall clock, so it stores a real instant
    (select-option (label "Timezone") "utc")
    (expect-text (test-id "when-s6") "Fri 13:30-14:15")
    (select-option (label "Timezone") "nyc")
    (expect-text (test-id "when-s6") "Fri 08:30-09:15")
  )
)
