(test "Availability picker — initial mount"
  (steps
    ; initial mount
    (expect-visible (role heading :name "Availability Picker"))
    (expect-visible (role region :name "Summary"))
    (expect-visible (role region :name "Week"))
    (expect-visible (role region :name "Add slot"))
    (expect-value (label "Timezone") "utc")
    (expect-text (test-id "zone-label") "Timezone: UTC+00:00")
    (expect-text (test-id "summary") "Available 3h 0m across 5 slots, 0 conflicts")
    (expect-text (test-id "free-days") "Tue, Thu, Fri, Sat, Sun")
    (expect-visible (role region :name "Slot sunrise"))
    (expect-text (test-id "title-sunrise") "Sunrise block")
    (expect-text (test-id "when-sunrise") "Mon 00:00-01:00")
    (expect-text (test-id "status-sunrise") "Available")
    (expect-text (test-id "conflict-sunrise") "Clear")
    (expect-text (test-id "title-standup") "Standup")
    (expect-text (test-id "when-standup") "Mon 09:00-09:30")
    (expect-text (test-id "status-standup") "Busy")
    (expect-text (test-id "conflict-standup") "Clear")
    (expect-text (test-id "title-review") "Design review")
    (expect-text (test-id "when-review") "Mon 09:15-10:15")
    (expect-text (test-id "status-review") "Unmarked")
    (expect-text (test-id "conflict-review") "Clear")
    (expect-text (test-id "title-midnight") "Late shift")
    (expect-text (test-id "when-midnight") "Mon 23:30-00:00")
    (expect-text (test-id "status-midnight") "Unmarked")
    (expect-text (test-id "title-focus") "Wednesday focus")
    (expect-text (test-id "when-focus") "Wed 12:00-14:00")
    (expect-text (test-id "status-focus") "Available")
    (expect-text (test-id "conflict-focus") "Clear")
    (expect-value (label "Slot name") "")
    (expect-value (label "Day") "Mon")
    (expect-value (label "Start time") "09:00")
    (expect-value (label "Length") "30")
    (expect-text (test-id "draft-status") "Enter a name for the new slot")
    (expect-disabled (role button :name "Add slot") true)
  )
)
