(test "Availability picker — removal, down to a day with no availability at all"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Mark review available"))
    (click (role button :name "Mark review busy"))
    (mark-metrics)
    (select-option (label "Timezone") "auckland")
    (click (role button :name "Mark review available"))
    (select-option (label "Timezone") "kolkata")
    (select-option (label "Timezone") "nyc")
    (fill (label "Slot name") "Client call")
    (fill (label "Start time") "25:00")
    (fill (label "Start time") "0830")
    (fill (label "Start time") "08:60")
    (fill (label "Start time") "08:30")
    (fill (label "Length") "0")
    (fill (label "Length") "abc")
    (fill (label "Length") "45")
    (select-option (label "Day") "Fri")
    (mark-metrics)
    (click (role button :name "Add slot"))
    (select-option (label "Timezone") "utc")
    (select-option (label "Timezone") "nyc")
    (click (role button :name "Mark s6 available"))
    (mark-metrics)
    (click (role button :name "Move s6 earlier"))

    ; removal, down to a day with no availability at all
    (mark-metrics)
    (click (role button :name "Remove sunrise"))
    (expect-absent (role region :name "Slot sunrise"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 1)
    (click (role button :name "Remove review"))
    (click (role button :name "Remove focus"))
    (click (role button :name "Remove s6"))
    (expect-text (test-id "summary") "Available 0h 0m across 2 slots, 0 conflicts")
    (expect-text (test-id "free-days") "Mon, Tue, Wed, Thu, Fri, Sat, Sun")
  )
)
