(test "Availability picker — reorder keeps every row scope"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Mark review available"))
    (click (role button :name "Mark review busy"))
    (mark-metrics)
    (select-option (label "Timezone") "auckland")
    (click (role button :name "Mark review available"))
    (select-option (label "Timezone") "kolkata")
    (select-option (label "Timezone") "nyc")
    (fill (label "Slot name") "Client call")
    (fill (label "Start time") "25:00")
    (fill (label "Start time") "0830")
    (fill (label "Start time") "08:60")
    (fill (label "Start time") "08:30")
    (fill (label "Length") "0")
    (fill (label "Length") "abc")
    (fill (label "Length") "45")
    (select-option (label "Day") "Fri")
    (mark-metrics)
    (click (role button :name "Add slot"))
    (select-option (label "Timezone") "utc")
    (select-option (label "Timezone") "nyc")
    (click (role button :name "Mark s6 available"))

    ; reorder keeps every row scope
    (mark-metrics)
    (click (role button :name "Move s6 earlier"))
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-text (test-id "when-s6") "Fri 08:30-09:15")
    (expect-text (test-id "when-focus") "Wed 07:00-09:00")
    (expect-text (test-id "status-s6") "Available")
    (expect-text (test-id "summary") "4h 45m")
    (expect-text (test-id "stat-slots") "6")
    (expect-text (test-id "stat-conflicts") "0")
  )
)
