(test "Availability picker — single item, then the empty list"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Mark review available"))
    (click (role button :name "Mark review busy"))
    (mark-metrics)
    (select-option (label "Timezone") "auckland")
    (click (role button :name "Mark review available"))
    (select-option (label "Timezone") "kolkata")
    (select-option (label "Timezone") "nyc")
    (fill (label "Slot name") "Client call")
    (fill (label "Start time") "25:00")
    (fill (label "Start time") "0830")
    (fill (label "Start time") "08:60")
    (fill (label "Start time") "08:30")
    (fill (label "Length") "0")
    (fill (label "Length") "abc")
    (fill (label "Length") "45")
    (select-option (label "Day") "Fri")
    (mark-metrics)
    (click (role button :name "Add slot"))
    (select-option (label "Timezone") "utc")
    (select-option (label "Timezone") "nyc")
    (click (role button :name "Mark s6 available"))
    (mark-metrics)
    (click (role button :name "Move s6 earlier"))
    (mark-metrics)
    (click (role button :name "Remove sunrise"))
    (click (role button :name "Remove review"))
    (click (role button :name "Remove focus"))
    (click (role button :name "Remove s6"))

    ; single item, then the empty list
    (click (role button :name "Remove midnight"))
    (expect-text (test-id "summary") "Available 0h 0m across 1 slots, 0 conflicts")
    (expect-visible (role region :name "Slot standup"))
    (expect-absent (role region :name "Slot midnight"))
    (click (role button :name "Remove standup"))
    (expect-absent (role region :name "Slot standup"))
    (expect-visible (role region :name "Week"))
    (expect-text (test-id "summary") "Available 0h 0m across 0 slots, 0 conflicts")
    (expect-text (test-id "free-days") "Mon, Tue, Wed, Thu, Fri, Sat, Sun")
  )
)
