(test "nested rollback and stale siblings return to sparse direct edits"
  (steps
    (click (test-id "use-nested"))
    (click (test-id "create-1k"))
    (click (test-id "append-one"))
    (click (test-id "stale-sibling-append"))
    (expect-absent (test-id "row-1001"))
    (expect-visible (test-id "row-1002"))
    (mark-metrics)
    (click (test-id "append-one"))
    (expect-visible (test-id "row-1003"))
    (expect-metric-delta rows_candidate_rows_visited 2)
    (expect-metric-delta rows_membership_entries_rewritten 1)
    (click (test-id "roll-back"))
    (expect-absent (test-id "row-1003"))
    (mark-metrics)
    (click (test-id "remove-middle"))
    (expect-text (test-id "count") "Rows: 1000")
    (expect-metric-delta rows_candidate_rows_visited 0)
    (expect-metric-delta rows_membership_entries_rewritten 2)))
