(test "nested 10000 row mirror follows sparse child edits"
  (steps
    (click (test-id "use-nested"))
    (click (test-id "create-10k"))
    (expect-visible (test-id "row-10000"))
    (mark-metrics)
    (click (test-id "append-one"))
    (expect-visible (test-id "row-10001"))
    (expect-metric-delta rows_candidate_rows_visited 2)
    (expect-metric-delta rows_membership_entries_rewritten 1)
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (mark-metrics)
    (click (test-id "move-first-to-end"))
    (expect-visible (test-id "row-1"))
    (expect-metric-delta rows_candidate_rows_visited 0)
    (expect-metric-delta rows_membership_entries_rewritten 0)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (mark-metrics)
    (click (test-id "remove-middle"))
    (expect-text (test-id "count") "Rows: 10000")
    (expect-metric-delta rows_candidate_rows_visited 0)
    (expect-metric-delta-at-most rows_membership_entries_rewritten 2)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 1)))
