(test "Loan comparator — initial mounted state"
  (steps
    ; 1. initial mounted state

    (expect-visible (role heading :name "Loan Comparator"))
    (expect-visible (role region :name "Loan Comparator"))
    (expect-visible (role region :name "Scenario A"))
    (expect-visible (role region :name "Scenario B"))
    (expect-visible (role region :name "Scenario C"))
    (expect-visible (role region :name "Scenario A schedule"))
    (expect-visible (role region :name "Scenario B schedule"))
    (expect-visible (role region :name "Scenario C schedule"))
    (expect-visible (role region :name "Comparison"))
    (expect-visible (role region :name "Scenario summaries"))
    (expect-visible (role heading :name "Scenario A"))
    (expect-visible (role heading :name "Scenario B"))
    (expect-visible (role heading :name "Scenario C"))
    (expect-visible (role heading :name "Comparison"))
    (expect-value (label "Scenario A principal") "2400")
    (expect-value (label "Scenario A annual rate") "6")
    (expect-value (label "Scenario A term months") "12")
    (expect-value (label "Scenario A extra payment") "0")
    (expect-value (label "Scenario B principal") "2400")
    (expect-value (label "Scenario B annual rate") "12")
    (expect-value (label "Scenario B term months") "12")
    (expect-value (label "Scenario B extra payment") "0")
    (expect-value (label "Scenario C principal") "2400")
    (expect-value (label "Scenario C annual rate") "6")
    (expect-value (label "Scenario C term months") "24")
    (expect-value (label "Scenario C extra payment") "0")
    (expect-text (test-id "a-inputs") "inputs ok")
    (expect-text (test-id "b-inputs") "inputs ok")
    (expect-text (test-id "c-inputs") "inputs ok")
    (expect-text (test-id "a-rate") "6.00%")
    (expect-text (test-id "b-rate") "12.00%")
    (expect-text (test-id "c-rate") "6.00%")
    (expect-text (test-id "a-payment") "$206.56")
    (expect-text (test-id "a-total-interest") "$78.62")
    (expect-text (test-id "a-total-paid") "$2478.62")
    (expect-text (test-id "a-payoff") "12 months")
    (expect-text (test-id "a-final-balance") "$0.00")
    (expect-text (test-id "b-payment") "$213.24")
    (expect-text (test-id "b-total-interest") "$158.78")
    (expect-text (test-id "b-total-paid") "$2558.78")
    (expect-text (test-id "b-payoff") "12 months")
    (expect-text (test-id "b-final-balance") "$0.00")
    (expect-text (test-id "c-payment") "$106.37")
    (expect-text (test-id "c-total-interest") "$152.71")
    (expect-text (test-id "c-total-paid") "$2552.71")
    (expect-text (test-id "c-payoff") "24 months")
    (expect-text (test-id "c-final-balance") "$0.00")
    ; Amortisation rows: first, second and final month of each schedule.
    (expect-text (test-id "a-month-1") "Month 1 | interest $12.00 | principal $194.56 | balance $2205.44")
    (expect-text (test-id "a-month-2") "Month 2 | interest $11.02 | principal $195.54 | balance $2009.90")
    (expect-text (test-id "a-month-12") "Month 12 | interest $1.02 | principal $205.44 | balance $0.00")
    (expect-text (test-id "b-month-1") "Month 1 | interest $24.00 | principal $189.24 | balance $2210.76")
    (expect-text (test-id "b-month-12") "Month 12 | interest $2.11 | principal $211.03 | balance $0.00")
    (expect-text (test-id "c-month-1") "Month 1 | interest $12.00 | principal $94.37 | balance $2305.63")
    (expect-text (test-id "c-month-24") "Month 24 | interest $0.52 | principal $105.68 | balance $0.00")
    (expect-absent (test-id "a-month-13"))
    ; Cross-scenario derived comparison.
    (expect-text (test-id "cheapest") "Scenario A ($78.62)")
    (expect-text (test-id "interest-spread") "$80.16")
    (expect-text (test-id "schedule-invariant") "All balances clear")
    (expect-value (label "Comparison pair") "ab")
    (expect-text (test-id "break-even") "Never")
    (expect-text (test-id "summary-a") "$206.56 / mo, 12 months, $78.62 interest")
    (expect-text (test-id "summary-b") "$213.24 / mo, 12 months, $158.78 interest")
    (expect-text (test-id "summary-c") "$106.37 / mo, 24 months, $152.71 interest")
  )
)
