(test "Kanban board — adding cards: empty, duplicate, valid"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Move right: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move up: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move down: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Flag: Ship search filters"))
    (mark-metrics)
    (fill (label "Filter cards") "Design")
    (mark-metrics)
    (fill (label "Filter cards") "")
    (fill (label "Filter cards") "Rotate")
    (mark-metrics)
    (click (role button :name "Delete: Rotate API keys"))
    (fill (label "Filter cards") "")
    (mark-metrics)
    (click (role button :name "Move right: Audit billing events"))
    (click (role button :name "Move left: Audit billing events"))
    (fill (label "WIP limit") "2")
    (fill (label "WIP limit") "1")
    (fill (label "WIP limit") "abc")
    (fill (label "WIP limit") "")
    (fill (label "WIP limit") "3")

    ; adding cards: empty, duplicate, valid
    (expect-disabled (role button :name "Add card") true)
    (fill (label "New card title") "   ")
    (expect-text (test-id "add-status") "Enter a title")
    (expect-disabled (role button :name "Add card") true)
    (fill (label "New card title") "Design login screen")
    (expect-text (test-id "add-status") "Duplicate title")
    (expect-disabled (role button :name "Add card") true)
    (fill (label "New card title") "Write release notes")
    (expect-text (test-id "add-status") "Ready")
    (expect-disabled (role button :name "Add card") false)
    (mark-metrics)
    (click (role button :name "Add card"))
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta rows_reused 1)
    (expect-visible (role region :name "Write release notes"))
    (expect-text (test-id "card-position-Write release notes") "Position 2 of 2 in Backlog")
    (expect-text (test-id "card-position-Design login screen") "Position 1 of 2 in Backlog")
    (expect-text (test-id "count-backlog") "Count: 2")
    (expect-text (test-id "board-total") "Board total: 5 cards")
    (expect-value (label "New card title") "")
    (expect-text (test-id "add-status") "Enter a title")
    (expect-disabled (role button :name "Add card") true)
    (expect-disabled (role button :name "Move left: Write release notes") true)
    (expect-disabled (role button :name "Move up: Write release notes") false)
    (expect-disabled (role button :name "Move down: Write release notes") true)
  )
)
