(test "Kanban board — delete the card that currently matches the filter"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Move right: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move up: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move down: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Flag: Ship search filters"))
    (mark-metrics)
    (fill (label "Filter cards") "Design")
    (mark-metrics)
    (fill (label "Filter cards") "")

    ; delete the card that currently matches the filter
    (fill (label "Filter cards") "Rotate")
    (expect-text (test-id "board-matching") "Matching cards: 1")
    (expect-text (test-id "matching-done") "Matching: 1")
    (expect-visible (role region :name "Rotate API keys"))
    (mark-metrics)
    (click (role button :name "Delete: Rotate API keys"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 0)
    (expect-absent (role region :name "Rotate API keys"))
    (expect-text (test-id "count-done") "Count: 0")
    (expect-text (test-id "matching-done") "Matching: 0")
    (expect-text (test-id "empty-done") "No cards shown")
    (expect-text (test-id "wip-done") "WIP: 0 of 1 - within limit")
    (expect-text (test-id "board-total") "Board total: 4 cards")
    (expect-text (test-id "board-matching") "Matching cards: 0")
    (fill (label "Filter cards") "")
    (expect-text (test-id "board-total") "Board total: 4 cards")
    (expect-text (test-id "board-matching") "Matching cards: 4")
    (expect-text (test-id "count-review") "Count: 1")
  )
)
