(test "Kanban board — empty a whole column"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Move right: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move up: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move down: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Flag: Ship search filters"))
    (mark-metrics)
    (fill (label "Filter cards") "Design")
    (mark-metrics)
    (fill (label "Filter cards") "")
    (fill (label "Filter cards") "Rotate")
    (mark-metrics)
    (click (role button :name "Delete: Rotate API keys"))
    (fill (label "Filter cards") "")
    (mark-metrics)
    (click (role button :name "Move right: Audit billing events"))
    (click (role button :name "Move left: Audit billing events"))
    (fill (label "WIP limit") "2")
    (fill (label "WIP limit") "1")
    (fill (label "WIP limit") "abc")
    (fill (label "WIP limit") "")
    (fill (label "WIP limit") "3")
    (fill (label "New card title") "   ")
    (fill (label "New card title") "Design login screen")
    (fill (label "New card title") "Write release notes")
    (mark-metrics)
    (click (role button :name "Add card"))

    ; empty a whole column
    (click (role button :name "Delete: Write release notes"))
    (expect-absent (role region :name "Write release notes"))
    (expect-text (test-id "count-backlog") "Count: 1")
    (mark-metrics)
    (click (role button :name "Delete: Design login screen"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 0)
    (expect-absent (role region :name "Design login screen"))
    (expect-text (test-id "count-backlog") "Count: 0")
    (expect-text (test-id "matching-backlog") "Matching: 0")
    (expect-text (test-id "empty-backlog") "No cards shown")
    (expect-text (test-id "wip-backlog") "WIP: 0 of 3 - within limit")
    (expect-text (test-id "board-total") "Board total: 3 cards")
    (expect-text (test-id "board-matching") "Matching cards: 3")
    ; a card can still be moved back into the now-empty column
    (click (role button :name "Move left: Ship search filters"))
    (expect-text (test-id "count-backlog") "Count: 1")
    (expect-text (test-id "card-position-Ship search filters") "Position 1 of 1 in Backlog")
    (expect-text (test-id "card-flags-Ship search filters") "Flags: 1")
    (expect-text (test-id "count-progress") "Count: 1")
    (expect-text (test-id "card-position-Draft onboarding copy") "Position 1 of 1 in In Progress")
    (expect-text (test-id "empty-backlog") "Showing cards")
  )
)
