(test "Kanban board — initial render"
  (steps
    ; initial render
    (expect-visible (role heading :name "Kanban Board"))
    (expect-visible (role region :name "Board controls"))
    (expect-visible (role region :name "Board summary"))
    (expect-visible (role region :name "Backlog"))
    (expect-visible (role region :name "In Progress"))
    (expect-visible (role region :name "Review"))
    (expect-visible (role region :name "Done"))
    (expect-value (label "Filter cards") "")
    (expect-value (label "WIP limit") "1")
    (expect-value (label "New card title") "")
    (expect-text (test-id "add-status") "Enter a title")
    (expect-disabled (role button :name "Add card") true)
    (expect-text (test-id "board-total") "Board total: 5 cards")
    (expect-text (test-id "board-matching") "Matching cards: 5")
    (expect-text (test-id "board-over") "Columns over WIP: 1")
    (expect-visible (text "WIP warning: rebalance the board"))
    (expect-text (test-id "count-backlog") "Count: 2")
    (expect-text (test-id "matching-backlog") "Matching: 2")
    (expect-text (test-id "wip-backlog") "WIP: 2 of 1 - over limit")
    (expect-text (test-id "empty-backlog") "Showing cards")
    (expect-attr (role region :name "Backlog") data-wip "over")
    (expect-text (test-id "count-progress") "Count: 1")
    (expect-text (test-id "matching-progress") "Matching: 1")
    (expect-text (test-id "wip-progress") "WIP: 1 of 1 - within limit")
    (expect-attr (role region :name "In Progress") data-wip "ok")
    (expect-text (test-id "count-review") "Count: 1")
    (expect-text (test-id "matching-review") "Matching: 1")
    (expect-text (test-id "wip-review") "WIP: 1 of 1 - within limit")
    (expect-text (test-id "count-done") "Count: 1")
    (expect-text (test-id "matching-done") "Matching: 1")
    (expect-text (test-id "wip-done") "WIP: 1 of 1 - within limit")
    (expect-visible (role region :name "Draft onboarding copy"))
    (expect-visible (role region :name "Design login screen"))
    (expect-visible (role region :name "Ship search filters"))
    (expect-visible (role region :name "Audit billing events"))
    (expect-visible (role region :name "Rotate API keys"))
    (expect-text (test-id "card-position-Draft onboarding copy") "Position 1 of 2 in Backlog")
    (expect-text (test-id "card-position-Design login screen") "Position 2 of 2 in Backlog")
    (expect-text (test-id "card-position-Ship search filters") "Position 1 of 1 in In Progress")
    (expect-text (test-id "card-position-Audit billing events") "Position 1 of 1 in Review")
    (expect-text (test-id "card-position-Rotate API keys") "Position 1 of 1 in Done")
    (expect-text (test-id "card-flags-Draft onboarding copy") "Flags: 0")
    (expect-attr (role region :name "Draft onboarding copy") data-card "Draft onboarding copy")
    ; boundary controls on mount
    (expect-disabled (role button :name "Move left: Draft onboarding copy") true)
    (expect-disabled (role button :name "Move right: Draft onboarding copy") false)
    (expect-disabled (role button :name "Move up: Draft onboarding copy") true)
    (expect-disabled (role button :name "Move down: Draft onboarding copy") false)
    (expect-disabled (role button :name "Move up: Design login screen") false)
    (expect-disabled (role button :name "Move down: Design login screen") true)
    (expect-disabled (role button :name "Move left: Rotate API keys") false)
    (expect-disabled (role button :name "Move right: Rotate API keys") true)
    (expect-disabled (role button :name "Move up: Ship search filters") true)
    (expect-disabled (role button :name "Move down: Ship search filters") true)
  )
)
