(test "Kanban board — WIP limit crosses and un crosses"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Move right: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move up: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move down: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Flag: Ship search filters"))
    (mark-metrics)
    (fill (label "Filter cards") "Design")
    (mark-metrics)
    (fill (label "Filter cards") "")
    (fill (label "Filter cards") "Rotate")
    (mark-metrics)
    (click (role button :name "Delete: Rotate API keys"))
    (fill (label "Filter cards") "")
    (mark-metrics)
    (click (role button :name "Move right: Audit billing events"))
    (click (role button :name "Move left: Audit billing events"))

    ; WIP limit crosses and un crosses
    (fill (label "WIP limit") "2")
    (expect-text (test-id "wip-progress") "WIP: 2 of 2 - within limit")
    (expect-attr (role region :name "In Progress") data-wip "ok")
    (expect-text (test-id "board-over") "Columns over WIP: 0")
    (expect-visible (text "WIP status: every column is within its limit"))
    (expect-absent (text "WIP warning: rebalance the board"))
    (fill (label "WIP limit") "1")
    (expect-text (test-id "wip-progress") "WIP: 2 of 1 - over limit")
    (expect-attr (role region :name "In Progress") data-wip "over")
    (expect-text (test-id "board-over") "Columns over WIP: 1")
    (expect-visible (text "WIP warning: rebalance the board"))
    (expect-absent (text "WIP status: every column is within its limit"))
    ; invalid input falls back to "unlimited"
    (fill (label "WIP limit") "abc")
    (expect-text (test-id "wip-progress") "WIP: 2 - unlimited")
    (expect-text (test-id "wip-review") "WIP: 1 - unlimited")
    (expect-attr (role region :name "In Progress") data-wip "unlimited")
    (expect-text (test-id "board-over") "Columns over WIP: 0")
    (fill (label "WIP limit") "")
    (expect-text (test-id "wip-progress") "WIP: 2 - unlimited")
    (expect-text (test-id "board-over") "Columns over WIP: 0")
    (fill (label "WIP limit") "3")
    (expect-text (test-id "wip-progress") "WIP: 2 of 3 - within limit")
    (expect-text (test-id "board-over") "Columns over WIP: 0")
  )
)
