(test "Kanban board — WIP limit crosses and un crosses"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Move right: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move up: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move down: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Flag: Ship search filters"))
    (mark-metrics)
    (fill (label "Filter cards") "Design")
    (mark-metrics)
    (fill (label "Filter cards") "")
    (fill (label "Filter cards") "Rotate")
    (mark-metrics)
    (click (role button :name "Delete: Rotate API keys"))
    (fill (label "Filter cards") "")
    (mark-metrics)
    (click (role button :name "Move right: Audit billing events"))
    (click (role button :name "Move left: Audit billing events"))
    ; WIP limit crosses and un crosses
    (fill (label "WIP limit") "2")
    (expect-text (test-id "wip-progress") "WIP 2/2")
    (expect-attr (role region :name "In Progress") data-wip "ok")
    (expect-text (test-id "board-over") "0")
    (expect-absent (text "Rebalance the board: at least one column is over its WIP limit."))
    (expect-absent (text "Rebalance the board: at least one column is over its WIP limit."))
    (fill (label "WIP limit") "1")
    (expect-text (test-id "wip-progress") "Over 2/1")
    (expect-attr (role region :name "In Progress") data-wip "over")
    (expect-text (test-id "board-over") "1")
    (expect-visible (text "Rebalance the board: at least one column is over its WIP limit."))
    ; invalid input falls back to "unlimited"
    (fill (label "WIP limit") "abc")
    (expect-text (test-id "wip-progress") "No WIP limit")
    (expect-text (test-id "wip-review") "No WIP limit")
    (expect-attr (role region :name "In Progress") data-wip "unlimited")
    (expect-text (test-id "board-over") "0")
    (fill (label "WIP limit") "")
    (expect-text (test-id "wip-progress") "No WIP limit")
    (expect-text (test-id "board-over") "0")
    (fill (label "WIP limit") "3")
    (expect-text (test-id "wip-progress") "WIP 2/3")
    (expect-text (test-id "board-over") "0")
  )
)
