(test "Support inbox — a failed sync"
  (steps
    ; Given the state established by earlier scenarios
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|new|-")
    (click (test-id "open-c1"))
    (mark-metrics)
    (click (test-id "open-c3"))
    (resolve-stale-task "inbox" "c9|Stale conversation|Nobody|me#")
    (click (test-id "open-c2"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (change (label "Assigned to me") "mine")
    (change (label "Unread") "unread")
    (change (label "All") "all")
    (click (test-id "open-c1"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (fill (label "Message") "Refund issued")
    (mark-metrics)
    (click (role button :name "Send message"))
    (tick-interval 4000)
    (mark-metrics)
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (resolve-task "send" "p1")
    (click (test-id "open-c3"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1")
    (click (test-id "open-c1"))
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1")
    (fill (label "Message") "Second reply")
    (mark-metrics)
    (click (role button :name "Send message"))
    (mark-metrics)
    (reject-task "send" "p2")
    (click (role button :name "Discard failed message"))
    (mark-metrics)
    (tick-interval 4000)
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1;m10|c2|customer|Still broken|new|-")
    (tick-interval 4000)
    (mark-metrics)
    (resolve-task "inbox" "c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me;c1|Card declined|Ada Lovelace|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1;m10|c2|customer|Still broken|new|-")
    (uncheck (label "Poll for updates"))
    (tick-interval-if-active 4000)
    (check (label "Poll for updates"))
    (tick-interval 4000)
    (resolve-task "inbox" "#")

    ; a failed sync

    (tick-interval 4000)
    (expect-pending-task "inbox" 1)
    (reject-task "inbox" "gateway timeout")
    (expect-pending-task "inbox" 0)
    (expect-text (test-id "sync-status") "Failed — gateway timeout")
    (expect-text (test-id "summary-conversations") "0")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "0")
    ; a later poll recovers
    (tick-interval 4000)
    (resolve-task "inbox" "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-")
    (expect-text (test-id "sync-status") "Up to date")
    (expect-text (test-id "summary-conversations") "3")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "0")
    (expect-text (test-id "thread-title") "Card declined")
    (expect-text (test-id "body-m1") "My card was declined")
    (expect-text (test-id "filter-notice") "All open conversations are listed.")
  )
)
