(test "Support inbox — a send fails and rolls back"
  (setup (manual-effects))
  (steps
    ; Deliver one earlier reply so rollback must preserve its sibling row.
    (stub-http "initial inbox" :url "/api/inbox" :status 200 :body "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (run-effect 1)
    (click (test-id "open-c1"))
    (stub-http "read c1" :url "/api/inbox" :status 200 :body "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (run-effect 2)
    (fill (label "Message") "Refund issued")
    (click (role button :name "Send message"))
    (stub-http "first reply accepted" :url "/api/inbox/send" :status 200 :body "p1")
    (run-effect 3)
    (tick-interval 4000)
    (stub-http "first reply delivered" :url "/api/inbox" :status 200 :body "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-;m9|c1|agent|Refund issued|read|p1")
    (run-effect 4)

    ; A second reply fails; only its optimistic row is rolled back.
    (expect-text (test-id "thread-count") "3 messages")
    (expect-text (test-id "body-p1") "Refund issued")
    (fill (label "Message") "Second reply")
    (expect-disabled (role button :name "Send message") false)
    (mark-metrics)
    (click (role button :name "Send message"))
    (expect-pending-effects 1)
    (expect-metric-delta rows_created 1)
    (expect-text (test-id "thread-count") "4 messages")
    (expect-visible (role region :name "Message p2"))
    (expect-text (test-id "body-p2") "Second reply")
    (expect-text (test-id "mstate-p2") "sending")
    (expect-text (test-id "send-state") "Sending…")
    (expect-text (test-id "summary-conversations") "3")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "1")
    (mark-metrics)
    (stub-http "second reply rejected" :url "/api/inbox/send" :status 503 :body "delivery unavailable")
    (run-effect 5)
    (expect-pending-effects 0)
    (expect-absent (role region :name "Message p2"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (expect-text (test-id "thread-count") "3 messages")
    (expect-text (test-id "send-state") "Failed")
    (expect-text (test-id "send-error") "Send failed: Second reply")
    (expect-text (test-id "summary-conversations") "3")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "0")
    ; the composer stays locked until the failure is dealt with
    (expect-disabled (role button :name "Send message") true)
    ; the rollback must not disturb its siblings
    (expect-visible (role region :name "Message p1"))
    (expect-text (test-id "body-p1") "Refund issued")
    (expect-text (test-id "mstate-p1") "delivered")
    (expect-text (test-id "body-m1") "My card was declined")
    (click (role button :name "Discard failed message"))
    (expect-text (test-id "send-state") "Discarded")
    (expect-text (test-id "send-error") "No send errors")
    (expect-absent (role region :name "Message p2"))
    (expect-visible (role region :name "Message p1"))
  )
)
