(test "Support inbox — optimistic sending"
  (setup (manual-effects))
  (steps
    ; Load the inbox with no unread messages before opening the composer.
    (stub-http "initial inbox" :url "/api/inbox" :status 200 :body "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (run-effect 1)

    ; optimistic sending

    (click (test-id "open-c1"))
    (stub-http "inbox snapshot" :url "/api/inbox" :status 200 :body "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (run-effect 2)
    (expect-text (test-id "thread-title") "Card declined")
    (expect-disabled (role button :name "Send message") true)
    (fill (label "Message") "Refund issued")
    (expect-value (label "Message") "Refund issued")
    (expect-disabled (role button :name "Send message") false)
    (mark-metrics)
    (click (role button :name "Send message"))
    (expect-value (label "Message") "")
    (expect-pending-effects 1)
    (expect-text (test-id "send-state") "Sending…")
    (expect-text (test-id "summary-conversations") "3")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "1")
    (expect-visible (role region :name "Message p1"))
    (expect-text (test-id "body-p1") "Refund issued")
    (expect-text (test-id "mstate-p1") "sending")
    (expect-disabled (role button :name "Send message") true)
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    ; A poll lands while the send is still in flight. The snapshot does not carry
    ; the client id yet, so the optimistic row must survive untouched - not dropped
    ; by the newer server truth, and not duplicated by it either.
    (tick-interval 4000)
    (expect-text (test-id "poll-count") "Polls issued: 1")
    (expect-pending-effects 2)
    (mark-metrics)
    (stub-http "inbox snapshot" :url "/api/inbox" :status 200 :body "c1|Card declined|Ada Lovelace|me;c2|Cannot log in|Grace Hopper|sam;c3|Refund status|Alan Turing|me#m1|c1|customer|My card was declined|read|-;m2|c1|agent|Looking into it now|read|-;m3|c2|customer|Login loop on mobile|read|-")
    (run-effect 4)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (expect-visible (role region :name "Message p1"))
    (expect-text (test-id "body-p1") "Refund issued")
    (expect-text (test-id "mstate-p1") "sending")
    (expect-text (test-id "summary-conversations") "3")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "1")
    (expect-pending-effects 1)
    (stub-http "send acknowledgment" :url "/api/inbox/send" :status 200 :body "p1")
    (run-effect 3)
    (expect-pending-effects 0)
    (expect-text (test-id "send-state") "Sent")
    (expect-text (test-id "mstate-p1") "sent")
    (expect-text (test-id "summary-conversations") "3")
    (expect-text (test-id "summary-unread") "0")
    (expect-text (test-id "summary-sending") "0")
  )
)
