(test "Log viewer — Appending line 41 to a 40-line buffer must reuse every existing row."
  (steps
    ; Given the state established by earlier scenarios
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (uncheck (label "Show debug"))
    (fill (label "Query") "timeout")
    (fill (label "Query") "zzz-not-present")
    (check (label "Show debug"))
    (fill (label "Query") "debug")
    (uncheck (label "Show debug"))
    (uncheck (label "Follow tail"))
    (tick-interval 1000)
    (check (label "Follow tail"))
    (click (role button :name "Clear log"))
    (check (label "Show debug"))
    (fill (label "Query") "")
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)

    ; Appending line 41 to a 40-line buffer must reuse every existing row.
    (mark-metrics)
    (tick-interval 1000)
    (expect-text (test-id "line-count") "Showing 41 of 41 lines")
    (expect-visible (role region :name "Log line-41"))
    (expect-text (test-id "text-line-41") "[41] info session expired")
    (expect-metric-delta rows_reused 40)
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta scopes_created 1)
    (expect-metric-delta dirty_source_roots 1)
    ; A console row now carries a timestamp cell and a level tag alongside
    ; the message, plus a class sink for the match wash and a data-match
    ; attribute. That is five extra patches for the one created row; the
    ; budget is still flat per append, not per buffer.
  )
)
