(test "Log viewer — One more append, to show the budget is flat per line rather than per buffer."
  (steps
    ; Given the state established by earlier scenarios
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (uncheck (label "Show debug"))
    (fill (label "Query") "timeout")
    (fill (label "Query") "zzz-not-present")
    (check (label "Show debug"))
    (fill (label "Query") "debug")
    (uncheck (label "Show debug"))
    (uncheck (label "Follow tail"))
    (tick-interval 1000)
    (check (label "Follow tail"))
    (click (role button :name "Clear log"))
    (check (label "Show debug"))
    (fill (label "Query") "")
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (mark-metrics)
    (tick-interval 1000)

    ; One more append, to show the budget is flat per line rather than per buffer.
    (mark-metrics)
    (tick-interval 1000)
    (expect-text (test-id "line-count") "Showing 42 of 42 lines")
    (expect-metric-delta rows_reused 41)
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta-at-most patches_emitted 17)
  )
)
