(test "Log viewer — Reordering the buffer moves rows without creating or removing any."
  (steps
    ; Given the state established by earlier scenarios
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (uncheck (label "Show debug"))
    (fill (label "Query") "timeout")
    (fill (label "Query") "zzz-not-present")
    (check (label "Show debug"))
    (fill (label "Query") "debug")
    (uncheck (label "Show debug"))
    (uncheck (label "Follow tail"))
    (tick-interval 1000)
    (check (label "Follow tail"))
    (click (role button :name "Clear log"))
    (check (label "Show debug"))
    (fill (label "Query") "")
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (tick-interval 1000)
    (mark-metrics)
    (tick-interval 1000)
    (mark-metrics)
    (tick-interval 1000)
    (mark-metrics)
    (fill (label "Query") "timeout")

    ; Reordering the buffer moves rows without creating or removing any.
    (mark-metrics)
    (check (label "Newest first"))
    (expect-text (test-id "order-mode") "Order: newest first")
    (expect-text (test-id "line-count") "Showing 42 of 42 lines")
    (expect-visible (role region :name "Log line-1"))
    (expect-visible (role region :name "Log line-42"))
    (expect-text (test-id "tail-line") "Tail: [42] warn cache warmed")
    (expect-metric-delta rows_reused 42)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (uncheck (label "Newest first"))
    (expect-text (test-id "order-mode") "Order: oldest first")
  )
)
