(test "Spreadsheet lite — error paths"
  (steps
    ; Given the state established by earlier scenarios
    (focus (label "D2"))
    (fill (label "Formula") "=B2+C2+100")
    (fill (label "Formula") "=B2+C2")
    (blur (label "D2"))
    (focus (label "D5"))
    (blur (label "D5"))
    (focus (label "F5"))
    (blur (label "F5"))
    (focus (label "B2"))
    (mark-metrics)
    (fill (label "B2") "1500")
    (mark-metrics)
    (fill (label "B2") "1200")
    (blur (label "B2"))
    (focus (label "C12"))
    (mark-metrics)
    (fill (label "C12") "9")
    (fill (label "C12") "7")
    (blur (label "C12"))

    ; error paths

    ; Text in an arithmetic operand becomes #VALUE! and propagates down the chain.
    (focus (label "C4"))
    (fill (label "C4") "oops")
    (expect-value (label "D4") "#VALUE!")
    (expect-value (label "D5") "#VALUE!")
    (expect-value (label "D6") "#VALUE!")
    (expect-value (label "D7") "#VALUE!")
    (expect-value (label "D8") "#VALUE!")
    (expect-attr (label "D5") data-kind "error")
    ; SUM skips text members rather than failing.
    (expect-value (label "C5") "2100")
    (expect-text (test-id "status-line") "Selected: C4 | Grid mode: values | Errors: 9")
    (fill (label "C4") "150")
    (expect-value (label "D4") "400")
    (expect-value (label "D8") "1127.5")
    (blur (label "C4"))
    ; Divide by zero introduced by an edit, then removed again.
    (focus (label "B8"))
    (fill (label "B8") "0")
    (expect-value (label "D8") "#DIV/0!")
    (expect-attr (label "D8") data-kind "error")
    (fill (label "B8") "4")
    (expect-value (label "D8") "1127.5")
    (blur (label "B8"))
    ; A range that contains an error propagates that error. A cell keeps the text
    ; the user typed until it loses focus, then shows the computed value.
    (focus (label "G3"))
    (fill (label "G3") "=SUM(B9:C9)")
    (expect-value (label "G3") "=SUM(B9:C9)")
    (blur (label "G3"))
    (expect-value (label "G3") "#DIV/0!")
    (focus (label "G3"))
    (fill (label "G3") "")
    (blur (label "G3"))
    (expect-value (label "G3") "")
    ; A new cycle is reported, not hung on, and clears when broken.
    (focus (label "G4"))
    (fill (label "G4") "=G4+1")
    (blur (label "G4"))
    (expect-value (label "G4") "#CYCLE!")
    (focus (label "G4"))
    (fill (label "G4") "=1+1")
    (blur (label "G4"))
    (expect-value (label "G4") "2")
    (focus (label "G4"))
    (fill (label "G4") "")
    (blur (label "G4"))
    (expect-value (label "G4") "")
    ; Unparseable formulas.
    (focus (label "G5"))
    (fill (label "G5") "=1+")
    (blur (label "G5"))
    (expect-value (label "G5") "#ERROR!")
    (focus (label "H5"))
    (fill (label "H5") "=(1+2")
    (blur (label "H5"))
    (expect-value (label "H5") "#ERROR!")
    (focus (label "H6"))
    (fill (label "H6") "=Z9+1")
    (blur (label "H6"))
    (expect-value (label "H6") "#ERROR!")
    (focus (label "H5"))
    (fill (label "H5") "")
    (blur (label "H5"))
    (expect-value (label "H5") "")
    (focus (label "H6"))
    (fill (label "H6") "")
    (blur (label "H6"))
    (expect-value (label "H6") "")
    (focus (label "G5"))
    (fill (label "G5") "")
    (blur (label "G5"))
    (expect-value (label "G5") "")
  )
)
