(test "Spreadsheet lite — keyed row add/remove"
  (steps
    ; Given the state established by earlier scenarios
    (focus (label "D2"))
    (fill (label "Formula") "=B2+C2+100")
    (fill (label "Formula") "=B2+C2")
    (blur (label "D2"))
    (focus (label "D5"))
    (blur (label "D5"))
    (focus (label "F5"))
    (blur (label "F5"))
    (focus (label "B2"))
    (mark-metrics)
    (fill (label "B2") "1500")
    (mark-metrics)
    (fill (label "B2") "1200")
    (blur (label "B2"))
    (focus (label "C12"))
    (mark-metrics)
    (fill (label "C12") "9")
    (fill (label "C12") "7")
    (blur (label "C12"))
    (focus (label "C4"))
    (fill (label "C4") "oops")
    (fill (label "C4") "150")
    (blur (label "C4"))
    (focus (label "B8"))
    (fill (label "B8") "0")
    (fill (label "B8") "4")
    (blur (label "B8"))
    (focus (label "G3"))
    (fill (label "G3") "=SUM(B9:C9)")
    (blur (label "G3"))
    (focus (label "G3"))
    (fill (label "G3") "")
    (blur (label "G3"))
    (focus (label "G4"))
    (fill (label "G4") "=G4+1")
    (blur (label "G4"))
    (focus (label "G4"))
    (fill (label "G4") "=1+1")
    (blur (label "G4"))
    (focus (label "G4"))
    (fill (label "G4") "")
    (blur (label "G4"))
    (focus (label "G5"))
    (fill (label "G5") "=1+")
    (blur (label "G5"))
    (focus (label "H5"))
    (fill (label "H5") "=(1+2")
    (blur (label "H5"))
    (focus (label "H6"))
    (fill (label "H6") "=Z9+1")
    (blur (label "H6"))
    (focus (label "H5"))
    (fill (label "H5") "")
    (blur (label "H5"))
    (focus (label "H6"))
    (fill (label "H6") "")
    (blur (label "H6"))
    (focus (label "G5"))
    (fill (label "G5") "")
    (blur (label "G5"))
    (focus (label "E12"))
    (fill (label "E12") "10")
    (fill (label "E12") "")
    (blur (label "E12"))
    (focus (label "G6"))
    (fill (label "G6") "=2+3*4-6/3")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=-3+10")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=(1+2)*(3+4)")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=10/3")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "")
    (blur (label "G6"))
    (click (role button :name "Show formulas"))
    (click (role button :name "Show values"))

    ; keyed row add/remove

    (mark-metrics)
    (click (role button :name "Hide empty rows"))
    (expect-absent (role region :name "Row 11"))
    (expect-visible (role region :name "Row 12"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 0)
    (mark-metrics)
    (click (role button :name "Show all rows"))
    (expect-visible (role region :name "Row 11"))
    (expect-value (label "A11") "")
    ; Row 11 comes back as one outer row plus its eight cell rows.
    (expect-metric-delta rows_created 9)
    (expect-metric-delta rows_removed 0)
  )
)
