(test "Markdown elem"
  (steps
    ; Markdown Elem structural fixture

    (expect-visible (role heading :name "Markdown Elem Fixture"))
    (expect-visible (text "Release note"))
    (expect-visible (text "bold outcome"))
    (expect-visible (text "Signal.map"))
    (expect-visible (text "First item"))
    (expect-visible (text "Second item"))
    (expect-visible (text "Quote text"))
    (expect-visible (text "Allowed link"))
    (expect-attr (test-id "allowed-link") href "https://example.test/release")
    (expect-visible (text "Blocked script"))
    (expect-no-attr (text "Blocked script") href)
    ; Static view: nested list, fenced code block, and image allowlist.
    (expect-visible (text "Nested detail"))
    (expect-visible (test-id "static-code"))
    (expect-visible (text "roc check main.roc"))
    (expect-attr (test-id "static-image") src "https://example.test/badge.png")
    (expect-attr (test-id "static-image") alt "Build badge")
    (expect-visible (text "Bad badge"))
    (expect-no-attr (text "Bad badge") src)
    ; Live view mounts prefilled with a fence, a nested list, and images.
    (expect-visible (test-id "b:0:codeblock"))
    (expect-visible (text "live fence body"))
    (expect-visible (text "Alpha item"))
    (expect-visible (text "Beta nested"))
    (expect-attr (test-id "s:0:image") src "https://example.test/live-badge.png")
    (expect-visible (text "Nope image"))
    (expect-no-attr (text "Nope image") src)
    (mark-metrics)
    (fill (label "Markdown input") "Updated **copy** with `inline code`\n[Live link](https://example.test/live)\n[Bad link](javascript:alert)")
    (expect-value (label "Markdown input") "Updated **copy** with `inline code`\n[Live link](https://example.test/live)\n[Bad link](javascript:alert)")
    (expect-visible (text "Updated "))
    (expect-visible (text "copy"))
    (expect-visible (text "inline code"))
    (expect-visible (text "Live link"))
    (expect-attr (test-id "s:0:link") href "https://example.test/live")
    (expect-visible (text "Bad link"))
    (expect-no-attr (text "Bad link") href)
    (expect-metric-delta-at-most patches_emitted 80)
    (expect-metric-delta-at-most active_graph_records_rebuilt 24)
    ; Live view: image allowlist under typing.
    (mark-metrics)
    (fill (label "Markdown input") "Photo ![Shot](https://example.test/shot.png) and ![Evil](javascript:x) end")
    (expect-attr (test-id "s:1:image") src "https://example.test/shot.png")
    (expect-attr (test-id "s:1:image") alt "Shot")
    (expect-visible (text "Evil"))
    (expect-no-attr (text "Evil") src)
    (expect-metric-delta-at-most patches_emitted 80)
    (expect-metric-delta-at-most active_graph_records_rebuilt 24)
  )
)
