(test "Data grid — inline editing"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by team"))
    (click (role button :name "Sort by id"))
    (mark-metrics)
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))
    (click (role button :name "First page"))

    ; 4. inline editing
    (mark-metrics)
    (fill (label "Note for Node-0003") "needs review")
    (expect-value (label "Note for Node-0003") "needs review")
    (expect-value (label "Note for Node-0002") "")
    (expect-value (label "Note for Node-0004") "")
    (expect-text (test-id "row-name-3") "Node-0003")
    (expect-text (test-id "row-score-3") "120")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 10)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta set_value 1)
    (expect-metric-delta dirty_source_roots 1)
    ; editing the last row on the page
    (mark-metrics)
    (fill (label "Note for Node-0009") "last on page")
    (expect-value (label "Note for Node-0009") "last on page")
    (expect-value (label "Note for Node-0008") "")
    (expect-value (label "Note for Node-0003") "needs review")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 10)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta set_value 1)
    ; notes survive paging away and back
    (click (role button :name "Next page"))
    (expect-value (label "Note for Node-0010") "")
    (click (role button :name "Previous page"))
    (expect-value (label "Note for Node-0003") "needs review")
    (expect-value (label "Note for Node-0009") "last on page")
  )
)
