(test "Data grid — per row selection"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by team"))
    (click (role button :name "Sort by id"))
    (mark-metrics)
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))
    (click (role button :name "First page"))
    (mark-metrics)
    (fill (label "Note for Node-0003") "needs review")
    (mark-metrics)
    (fill (label "Note for Node-0009") "last on page")
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))

    ; 5. per row selection
    (mark-metrics)
    (check (label "Select Node-0002"))
    (expect-checked (label "Select Node-0002") true)
    (expect-checked (label "Select Node-0001") false)
    (expect-checked (label "Select Node-0003") false)
    (expect-text (test-id "summary-selected-here") "1")
    (expect-text (test-id "summary-selected-all") "1")
    (expect-checked (label "Select all matching rows") false)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 10)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta set_checked 1)
    (expect-metric-delta set_value 0)
    (uncheck (label "Select Node-0002"))
    (expect-checked (label "Select Node-0002") false)
    (expect-text (test-id "summary-selected-all") "0")
  )
)
