(test "moving a row keeps its selector membership without touching the index"
  (steps
    (click (role button :name "Create 1,000 rows"))
    (mark-metrics)
    (click (role button :name "Move second row"))
    (expect-visible (test-id "row-2"))
    ; A pure move changes render order only; no membership is visited.
    (expect-metric-delta rows_render_roots_moved 1)
    (expect-metric-delta selector_registry_visits 0)
    (expect-metric-delta selector_registrations 0)
    (expect-metric-delta selector_memberships_released 0)
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_removed 0)
    (mark-metrics)
    (click (role button :name "Select row 2"))
    (expect-attr (test-id "row-2") class "danger")
    (expect-attr (test-id "pinned-2") class "danger")
    (expect-metric-delta selector_members_dirtied 2)
    (expect-metric-delta-at-most derived_calls_into_roc 5)
    (mark-metrics)
    (click (role button :name "Remove row 2"))
    (expect-absent (test-id "row-2"))
    (expect-metric-delta selector_memberships_released 2)
    (expect-metric-delta selector_registry_visits 2)
    (expect-attr (test-id "pinned-2") class "danger")))
