(test "Kanban board — initial render"
  (steps
    ; initial render
    (expect-visible (role heading :name "Kanban Board"))
    (expect-visible (role region :name "Board controls"))
    (expect-visible (role region :name "Board summary"))
    (expect-visible (role region :name "Backlog"))
    (expect-visible (role region :name "In Progress"))
    (expect-visible (role region :name "Review"))
    (expect-visible (role region :name "Done"))
    (expect-value (label "Filter cards") "")
    (expect-value (label "WIP limit") "1")
    (expect-value (label "New card title") "")
    (expect-text (test-id "add-status") "Enter a title")
    (expect-disabled (role button :name "Add card") true)
    (expect-text (test-id "board-total") "5")
    (expect-text (test-id "board-matching") "5")
    (expect-text (test-id "board-over") "1")
    (expect-visible (text "Rebalance the board: at least one column is over its WIP limit."))
    (expect-text (test-id "count-backlog") "2 cards")
    (expect-text (test-id "matching-backlog") "2 shown")
    (expect-text (test-id "wip-backlog") "Over 2/1")
    (expect-absent (test-id "empty-backlog"))
    (expect-attr (role region :name "Backlog") data-wip "over")
    (expect-text (test-id "count-progress") "1 card")
    (expect-text (test-id "matching-progress") "1 shown")
    (expect-text (test-id "wip-progress") "WIP 1/1")
    (expect-attr (role region :name "In Progress") data-wip "ok")
    (expect-text (test-id "count-review") "1 card")
    (expect-text (test-id "matching-review") "1 shown")
    (expect-text (test-id "wip-review") "WIP 1/1")
    (expect-text (test-id "count-done") "1 card")
    (expect-text (test-id "matching-done") "1 shown")
    (expect-text (test-id "wip-done") "WIP 1/1")
    (expect-visible (role region :name "Draft onboarding copy"))
    (expect-visible (role region :name "Design login screen"))
    (expect-visible (role region :name "Ship search filters"))
    (expect-visible (role region :name "Audit billing events"))
    (expect-visible (role region :name "Rotate API keys"))
    (expect-text (test-id "card-position-Draft onboarding copy") "1 of 2 in Backlog")
    (expect-text (test-id "card-position-Design login screen") "2 of 2 in Backlog")
    (expect-text (test-id "card-position-Ship search filters") "1 of 1 in In Progress")
    (expect-text (test-id "card-position-Audit billing events") "1 of 1 in Review")
    (expect-text (test-id "card-position-Rotate API keys") "1 of 1 in Done")
    (expect-absent (test-id "card-flags-Draft onboarding copy"))
    (expect-attr (role region :name "Draft onboarding copy") data-card "Draft onboarding copy")
    ; boundary controls on mount
    (expect-disabled (role button :name "Move left: Draft onboarding copy") true)
    (expect-disabled (role button :name "Move right: Draft onboarding copy") false)
    (expect-disabled (role button :name "Move up: Draft onboarding copy") true)
    (expect-disabled (role button :name "Move down: Draft onboarding copy") false)
    (expect-disabled (role button :name "Move up: Design login screen") false)
    (expect-disabled (role button :name "Move down: Design login screen") true)
    (expect-disabled (role button :name "Move left: Rotate API keys") false)
    (expect-disabled (role button :name "Move right: Rotate API keys") true)
    (expect-disabled (role button :name "Move up: Ship search filters") true)
    (expect-disabled (role button :name "Move down: Ship search filters") true)
  )
)
