(test "Kanban board — move the only card out of a column, leaving it empty"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Move right: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move up: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Move down: Draft onboarding copy"))
    (mark-metrics)
    (click (role button :name "Flag: Ship search filters"))
    (mark-metrics)
    (fill (label "Filter cards") "Design")
    (mark-metrics)
    (fill (label "Filter cards") "")
    (fill (label "Filter cards") "Rotate")
    (mark-metrics)
    (click (role button :name "Delete: Rotate API keys"))
    (fill (label "Filter cards") "")
    ; move the only card out of a column, leaving it empty
    (mark-metrics)
    (click (role button :name "Move right: Audit billing events"))
    (expect-metric-delta rows_removed 1)
    (expect-metric-delta rows_created 1)
    (expect-metric-delta rows_reused 0)
    (expect-text (test-id "count-review") "0 cards")
    (expect-text (test-id "empty-review") "No cards")
    (expect-text (test-id "wip-review") "WIP 0/1")
    (expect-text (test-id "count-done") "1 card")
    (expect-text (test-id "card-position-Audit billing events") "1 of 1 in Done")
    (expect-disabled (role button :name "Move right: Audit billing events") true)
    (expect-disabled (role button :name "Move left: Audit billing events") false)
    (click (role button :name "Move left: Audit billing events"))
    (expect-text (test-id "count-review") "1 card")
    (expect-text (test-id "count-done") "0 cards")
    (expect-text (test-id "card-position-Audit billing events") "1 of 1 in Review")
    (expect-absent (test-id "empty-review"))
  )
)
