(test "Explicit task cancel is terminal and late results cannot replace it"
  (steps
    (expect-pending-task "lookup" 1)
    (click (role button :name "Cancel"))
    (expect-pending-task "lookup" 0)
    (expect-canceled-task "lookup" 1)
    (expect-text (text "Task status: failed canceled") "Task status: failed canceled")
    (mark-metrics)
    (click (role button :name "Cancel"))
    (expect-metric-delta set_text 0)
    (expect-canceled-task "lookup" 1)
    (resolve-stale-task "lookup" "late result")
    (expect-metric-delta stale_task_results_ignored 1)
    (expect-text (text "Task status: failed canceled") "Task status: failed canceled")
    (click (role button :name "Refresh"))
    (expect-pending-task "lookup" 1)
    (expect-text (text "Task status: loading") "Task status: loading")
    (resolve-task "lookup" "fresh result")
    (expect-pending-task "lookup" 0)
    (expect-text (text "Task status: done fresh result") "Task status: done fresh result")
  )
)
