(test "Effect latest wins"
  (setup (manual-effects))
  (steps
    (expect-visible (role heading :name "Effect latest wins"))
    (expect-text (test-id "status") "Loading")
    (expect-pending-effects 1)
    (click (role button :name "Refresh"))
    (expect-pending-effects 2)
    (stub-http "older request" :url "/api/latest/0" :status 200 :body "stale result")
    (run-effect 1)
    (expect-pending-effects 1)
    (expect-text (test-id "status") "Loading")
    (stub-http "newest request" :url "/api/latest/1" :status 200 :body "fresh result")
    (run-effect 2)
    (expect-text (test-id "status") "Done: fresh result")

    ; Warm the transition before checking its retained-allocation plateau.
    (click (role button :name "Refresh"))
    (stub-http "warm transition" :url "/api/latest/2" :status 200 :body "other result")
    (run-effect 3)
    (expect-text (test-id "status") "Done: other result")
    (mark-metrics)
    (click (role button :name "Refresh"))
    (stub-http "repeat transition" :url "/api/latest/3" :status 200 :body "third result")
    (run-effect 4)
    (expect-text (test-id "status") "Done: third result")
    (expect-pending-effects 0)
    (expect-metric-delta retained_alloc_delta 0)
    (expect-metric-delta host_retained_bytes_delta 0)
  )
)
