(test "Data grid — filtering"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by team"))
    (click (role button :name "Sort by id"))
    (mark-metrics)
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))
    (click (role button :name "First page"))
    (mark-metrics)
    (fill (label "Note for Node-0003") "needs review")
    (mark-metrics)
    (fill (label "Note for Node-0009") "last on page")
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))
    (mark-metrics)
    (check (label "Select Node-0002"))
    (uncheck (label "Select Node-0002"))

    ; 6. filtering
    (mark-metrics)
    (fill (label "Filter") "Node-119")
    (expect-value (label "Filter") "Node-119")
    (expect-text (test-id "summary-matching") "Matching rows: 10")
    (expect-text (test-id "summary-total") "Total score: 2585")
    (expect-text (test-id "summary-average") "Average score: 258")
    (expect-text (test-id "summary-highest") "Highest score: 431")
    (expect-text (test-id "summary-lowest") "Lowest score: 104")
    (expect-text (test-id "rows-showing") "Showing 10 of 10 rows")
    (expect-text (test-id "page-label") "Page 1 of 1")
    (expect-disabled (role button :name "Next page") true)
    (expect-text (test-id "row-name-1190") "Node-1190")
    (expect-text (test-id "row-score-1199") "431")
    (expect-absent (test-id "row-name-0"))
    (expect-metric-delta rows_created 10)
    (expect-metric-delta rows_reused 0)
    (expect-metric-delta rows_removed 10)
    (expect-metric-delta set_value 11)
    (expect-metric-delta-at-most patches_emitted 340)
    ; select all, scoped to the current filter
    (mark-metrics)
    (check (label "Select all matching rows"))
    (expect-checked (label "Select all matching rows") true)
    (expect-checked (label "Select Node-1190") true)
    (expect-checked (label "Select Node-1199") true)
    (expect-text (test-id "summary-selected-here") "Selected in filter: 10")
    (expect-text (test-id "summary-selected-all") "Selected overall: 10")
    (expect-metric-delta rows_created 0)
    (expect-metric-delta rows_reused 10)
    (expect-metric-delta rows_removed 0)
    (expect-metric-delta set_checked 11)
    (expect-metric-delta set_value 0)
    ; selection survives a filter change: it is keyed by row id, not by the query
    (fill (label "Filter") "")
    (expect-text (test-id "summary-matching") "Matching rows: 1200")
    (expect-text (test-id "summary-selected-here") "Selected in filter: 10")
    (expect-text (test-id "summary-selected-all") "Selected overall: 10")
    (expect-checked (label "Select all matching rows") false)
    (expect-checked (label "Select Node-0000") false)
    (expect-text (test-id "page-label") "Page 1 of 120")
    ; and it is still there when the narrower filter comes back
    (fill (label "Filter") "Node-119")
    (expect-checked (label "Select all matching rows") true)
    (expect-checked (label "Select Node-1195") true)
    (uncheck (label "Select all matching rows"))
    (expect-text (test-id "summary-selected-all") "Selected overall: 0")
    (expect-checked (label "Select Node-1190") false)
  )
)
