(test "Data grid — initial mount"
  (steps
    ; 1. initial mount
    (expect-visible (role heading :name "Data Grid"))
    (expect-visible (role region :name "Data Grid"))
    (expect-visible (role region :name "Grid controls"))
    (expect-visible (role region :name "Summary"))
    (expect-visible (role region :name "Rows"))
    (expect-visible (role region :name "Paging"))
    (expect-visible (text "Dataset rows: 1200"))
    (expect-value (label "Filter") "")
    (expect-text (test-id "sort-caption") "Sorted by id ascending")
    (expect-text (test-id "summary-matching") "1200")
    (expect-text (test-id "summary-total") "596952")
    (expect-text (test-id "summary-average") "497")
    (expect-text (test-id "summary-highest") "999")
    (expect-text (test-id "summary-lowest") "0")
    (expect-text (test-id "summary-selected-here") "0")
    (expect-text (test-id "summary-selected-all") "0")
    (expect-text (test-id "rows-showing") "Showing 10 of 1200 rows")
    (expect-text (test-id "page-label") "Page 1 of 120")
    (expect-checked (label "Select all matching rows") false)
    (expect-disabled (role button :name "Previous page") true)
    (expect-disabled (role button :name "Next page") false)
    ; only the first ten rows are rendered
    (expect-text (test-id "row-name-0") "Node-0000")
    (expect-text (test-id "row-team-0") "Delta")
    (expect-text (test-id "row-score-0") "0")
    (expect-text (test-id "row-name-9") "Node-0009")
    (expect-text (test-id "row-score-9") "414")
    (expect-absent (test-id "row-name-10"))
    (expect-absent (test-id "row-name-1199"))
    (expect-value (label "Note for Node-0000") "")
    (expect-checked (label "Select Node-0000") false)
  )
)
