(test "Data grid — paging past the end"
  (steps
    ; Given the state established by earlier scenarios
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by name"))
    (click (role button :name "Sort by team"))
    (click (role button :name "Sort by id"))
    (mark-metrics)
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))
    (click (role button :name "First page"))
    (mark-metrics)
    (fill (label "Note for Node-0003") "needs review")
    (mark-metrics)
    (fill (label "Note for Node-0009") "last on page")
    (click (role button :name "Next page"))
    (click (role button :name "Previous page"))
    (mark-metrics)
    (check (label "Select Node-0002"))
    (uncheck (label "Select Node-0002"))
    (mark-metrics)
    (fill (label "Filter") "Node-119")
    (mark-metrics)
    (check (label "Select all matching rows"))
    (fill (label "Filter") "")
    (fill (label "Filter") "Node-119")
    (uncheck (label "Select all matching rows"))
    (fill (label "Filter") "Node-0007")
    (mark-metrics)
    (fill (label "Filter") "no-such-row")
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (click (role button :name "Sort by score"))
    (click (role button :name "Sort by id"))

    ; 9. paging past the end
    (fill (label "Filter") "")
    (expect-text (test-id "page-label") "Page 1 of 120")
    (click (role button :name "Next page"))
    (click (role button :name "Next page"))
    (click (role button :name "Next page"))
    (expect-text (test-id "page-label") "Page 4 of 120")
    (expect-text (test-id "row-name-30") "Node-0030")
    ; narrowing the filter strands the requested page past the end; the derived
    ; page clamps to the last real page instead of rendering an empty window
    (fill (label "Filter") "Node-119")
    (expect-text (test-id "page-label") "Page 1 of 1")
    (expect-text (test-id "rows-showing") "Showing 10 of 10 rows")
    (expect-text (test-id "row-name-1190") "Node-1190")
    (expect-disabled (role button :name "Next page") true)
    ; widening again restores the originally requested page
    (fill (label "Filter") "")
    (expect-text (test-id "page-label") "Page 4 of 120")
    (expect-text (test-id "row-name-30") "Node-0030")
    (click (role button :name "First page"))
    (expect-text (test-id "page-label") "Page 1 of 120")
    (expect-value (label "Note for Node-0003") "needs review")
  )
)
