(test "Data grid — sorting"
  (steps
    ; 2. sorting
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (expect-text (test-id "sort-caption") "Sorted by score ascending")
    (expect-text (test-id "row-score-0") "0")
    (expect-text (test-id "row-score-621") "0")
    (expect-text (test-id "row-score-1108") "5")
    (expect-absent (test-id "row-name-1"))
    (expect-text (test-id "rows-showing") "Showing 10 of 1200 rows")
    (expect-text (test-id "summary-total") "Total score: 596952")
    (expect-metric-delta rows_created 9)
    (expect-metric-delta rows_reused 1)
    (expect-metric-delta rows_removed 9)
    (expect-metric-delta set_value 9)
    (expect-metric-delta-at-most patches_emitted 302)
    ; reverse the same column
    (mark-metrics)
    (click (role button :name "Sort by score"))
    (expect-text (test-id "sort-caption") "Sorted by score descending")
    (expect-text (test-id "row-score-702") "999")
    (expect-text (test-id "row-score-540") "993")
    (expect-absent (test-id "row-name-0"))
    (expect-metric-delta rows_created 10)
    (expect-metric-delta rows_reused 0)
    (expect-metric-delta rows_removed 10)
    (click (role button :name "Sort by name"))
    (expect-text (test-id "sort-caption") "Sorted by name ascending")
    (expect-text (test-id "row-name-0") "Node-0000")
    (expect-text (test-id "row-name-9") "Node-0009")
    (click (role button :name "Sort by name"))
    (expect-text (test-id "sort-caption") "Sorted by name descending")
    (expect-text (test-id "row-name-1199") "Node-1199")
    (expect-text (test-id "row-name-1190") "Node-1190")
    (expect-absent (test-id "row-name-0"))
    (click (role button :name "Sort by team"))
    (expect-text (test-id "sort-caption") "Sorted by team ascending")
    (expect-text (test-id "row-team-3") "Atlas")
    (expect-text (test-id "row-team-39") "Atlas")
    (click (role button :name "Sort by id"))
    (expect-text (test-id "sort-caption") "Sorted by id ascending")
    (expect-text (test-id "row-name-0") "Node-0000")
  )
)
