(test "Cancel preserves the draft and prevents stale task results from replacing it"
  (steps
    (shortcut (test-id "notes-editor") "o" 1)
    (resolve-file-choice "notes-open" (chosen "/tmp/Ideas café.txt"))
    (expect-pending-task "notes-read" 1)
    (click (role button :name "Cancel operation"))
    (expect-pending-task "notes-read" 0)
    (expect-canceled-task "notes-read" 1)
    (expect-text (test-id "note-status") "No changes")
    (fill (label "Note text") "Current draft")
    (resolve-stale-task "notes-read" "6:files120:/tmp/Ideas café.txt9:Late body")
    (expect-value (label "Note text") "Current draft")
    (expect-text (test-id "document-name") "Untitled note")
    (shortcut (test-id "notes-editor") "s" 1)
    (resolve-file-choice "notes-save-path" (chosen "/tmp/Ideas café.txt"))
    (fill (label "Note text") "Newer draft")
    (shortcut (test-id "notes-editor") "Escape" 0)
    (expect-pending-task "notes-write" 0)
    (expect-canceled-task "notes-write" 1)
    (expect-value (label "Note text") "Newer draft")
    (expect-text (test-id "note-status") "Unsaved changes")
    (expect-text (test-id "document-name") "Untitled note")
    (shortcut (test-id "notes-editor") "s" 1)
    (shortcut (test-id "notes-editor") "Escape" 0)
    (expect-pending-task "notes-save-path" 0)
    (expect-value (label "Note text") "Newer draft")
))
