(test "Canceling close keeps the draft and a later discard completes a fresh request"
  (steps
    (fill (label "Note text") "Keep this note")
    (request-window-close)
    (click (role button :name "Keep editing"))
    (expect-window-closed false)
    (expect-value (label "Note text") "Keep this note")
    (expect-disabled (label "Note text") false)
    (request-window-close)
    (stub-file-choice "notes-save-path" (canceled))
    (click (role button :name "Save and close"))
    (expect-window-closed false)
    (expect-value (label "Note text") "Keep this note")
    (request-window-close)
    (click (role button :name "Discard and close"))
    (expect-window-closed true)))
