(test "Discard confirmation preserves canceled drafts and restores both fields together"
  (steps
    (click (role button :name "Revert changes"))
    (expect-absent (test-id "discard-confirmation"))
    (fill (label "Document title") "Trip plan")
    (fill (label "Note text") "Take the train")
    (click (role button :name "Revert changes"))
    (expect-visible (test-id "discard-confirmation"))
    (click (role button :name "Keep editing"))
    (expect-absent (test-id "discard-confirmation"))
    (expect-value (label "Document title") "Trip plan")
    (expect-value (label "Note text") "Take the train")
    (click (role button :name "Revert changes"))
    (click (role button :name "Discard changes"))
    (expect-absent (test-id "discard-confirmation"))
    (expect-value (label "Document title") "Untitled note")
    (expect-value (label "Note text") "")
    (expect-text (test-id "note-summary") "0 words · 0 characters")
    (expect-text (test-id "note-status") "No changes")))
