(test "Multiline editing derives Unicode counts and exact dirty state"
  (steps
    (expect-text (test-id "document-name") "Untitled note")
    (expect-value (label "Note text") "")
    (expect-text (test-id "note-summary") "0 words · 0 characters")
    (expect-text (test-id "note-status") "No changes")
    (expect-disabled (role button :name "Revert changes") true)
    (fill (label "Note text") "Hello café\nSecond line")
    (expect-value (label "Note text") "Hello café\nSecond line")
    (expect-text (test-id "note-summary") "4 words · 22 characters")
    (expect-text (test-id "note-status") "Unsaved changes")
    (mark-metrics)
    (fill (label "Note text") "Hello café\nSecond line")
    (expect-metric-delta derived_calls_into_roc 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (fill (label "Note text") "")
    (expect-text (test-id "note-status") "No changes")
))
