(test "Editing a note derives statistics and tracks exact draft changes"
  (steps
    (expect-value (label "Document title") "Untitled note")
    (expect-value (label "Note text") "")
    (expect-text (test-id "note-summary") "0 words · 0 characters")
    (expect-text (test-id "note-status") "No changes")
    (fill (label "Note text") "Hello café")
    (expect-value (label "Note text") "Hello café")
    (expect-text (test-id "note-summary") "2 words · 10 characters")
    (expect-text (test-id "note-status") "Unsaved changes")
    (mark-metrics)
    (fill (label "Note text") "Hello café")
    (expect-metric-delta derived_calls_into_roc 0)
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (fill (label "Document title") "Weekend ideas")
    (expect-text (test-id "note-summary") "2 words · 10 characters")
    (fill (label "Note text") "")
    (expect-text (test-id "note-status") "Unsaved changes")
    (fill (label "Document title") "Untitled note")
    (expect-text (test-id "note-status") "No changes")))
