(test "Typed read and write failures preserve the accepted document and allow retry"
  (steps
    (shortcut (test-id "notes-editor") "o" 1)
    (stub-file-reject "notes-read" :kind invalid-utf8 :detail "document bytes")
    (resolve-file-choice "notes-open" (chosen "/tmp/Ideas café.txt"))
    (expect-value (label "Note text") "")
    (expect-text (test-id "note-problem") "Not valid UTF-8: document bytes")
    (expect-text (test-id "document-name") "Untitled note")
    (fill (label "Note text") "Do not lose this")
    (shortcut (test-id "notes-editor") "s" 1)
    (stub-file-reject "notes-write" :kind permission-denied :detail "destination")
    (resolve-file-choice "notes-save-path" (chosen "/tmp/Ideas café.txt"))
    (expect-value (label "Note text") "Do not lose this")
    (expect-text (test-id "note-status") "Unsaved changes")
    (expect-text (test-id "note-problem") "Permission denied: destination")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-text (test-id "note-problem") "")
    (stub-file-write "notes-write" :path "/tmp/Ideas café.txt" :bytes 16)
    (resolve-file-choice "notes-save-path" (chosen "/tmp/Ideas café.txt"))
    (expect-text (test-id "note-status") "No changes")
    (fill (label "Note text") "Edited again")
    (shortcut (test-id "notes-editor") "s" 3)
    (resolve-file-choice "notes-save-path" (canceled))
    (expect-value (label "Note text") "Edited again")
    (expect-text (test-id "document-name") "Ideas café.txt")
    (expect-text (test-id "note-status") "Unsaved changes")
))
