(test "Typed read and write failures preserve the accepted document and allow retry"
  (steps
    (shortcut (test-id "notes-editor") "o" 1)
    (resolve-task "notes-open" "6:files16:chosen20:/tmp/Ideas café.txt")
    (reject-task "notes-read" "6:files112:invalid-utf814:document bytes")
    (expect-value (label "Note text") "")
    (expect-text (test-id "note-problem") "Not valid UTF-8: document bytes")
    (expect-text (test-id "document-name") "Untitled note")
    (fill (label "Note text") "Do not lose this")
    (shortcut (test-id "notes-editor") "s" 1)
    (resolve-task "notes-save-path" "6:files16:chosen20:/tmp/Ideas café.txt")
    (reject-task "notes-write" "6:files117:permission-denied11:destination")
    (expect-value (label "Note text") "Do not lose this")
    (expect-text (test-id "note-status") "Unsaved changes")
    (expect-text (test-id "note-problem") "Permission denied: destination")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-text (test-id "note-problem") "")
    (resolve-task "notes-save-path" "6:files16:chosen20:/tmp/Ideas café.txt")
    (resolve-task "notes-write" "6:files120:/tmp/Ideas café.txt2:16")
    (expect-text (test-id "note-status") "No changes")
    (fill (label "Note text") "Edited again")
    (shortcut (test-id "notes-editor") "s" 3)
    (resolve-task "notes-save-path" "6:files18:canceled")
    (expect-value (label "Note text") "Edited again")
    (expect-text (test-id "document-name") "Ideas café.txt")
    (expect-text (test-id "note-status") "Unsaved changes")
))
