(test "Opening confirms dirty text then installs one complete Unicode file"
  (steps
    (fill (label "Note text") "Keep this draft")
    (shortcut (test-id "notes-editor") "o" 1)
    (expect-visible (test-id "discard-confirmation"))
    (click (role button :name "Keep editing"))
    (expect-value (label "Note text") "Keep this draft")
    (shortcut (test-id "notes-editor") "o" 1)
    (stub-file-choice "notes-open" (canceled))
    (click (role button :name "Discard changes"))
    (expect-value (label "Note text") "Keep this draft")
    (expect-text (test-id "note-status") "Unsaved changes")
    (shortcut (test-id "notes-editor") "o" 1)
    (stub-file-choice "notes-open" (chosen "/tmp/Ideas café.txt"))
    (stub-file-read "notes-read" :path "/tmp/Ideas café.txt" :text "Heading\n\ncafé 🙂\n")
    (click (role button :name "Discard changes"))
    (expect-text (test-id "document-name") "Ideas café.txt")
    (expect-value (label "Note text") "Heading\n\ncafé 🙂\n")
    (expect-text (test-id "note-status") "No changes")
    (expect-text (test-id "note-summary") "2 words · 16 characters")
    (expect-disabled (label "Note text") false)
    (shortcut (test-id "notes-editor") "n" 1)
    (expect-value (label "Note text") "")
    (expect-text (test-id "document-name") "Untitled note")
    (expect-text (test-id "note-status") "No changes")
))
