(test "Saves own their submitted snapshot and later saves reuse the chosen path"
  (steps
    (fill (label "Note text") "First revision")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-text (test-id "note-status") "Choose where to save…")
    (expect-pending-task "notes-save-path" 1)
    (expect-disabled (label "Note text") true)
    (stub-file-write "notes-write" :path "/tmp/Ideas café.txt" :bytes 14)
    (resolve-file-choice "notes-save-path" (chosen "/tmp/Ideas café.txt"))
    (expect-text (test-id "document-name") "Ideas café.txt")
    (expect-value (label "Note text") "First revision")
    (expect-text (test-id "note-status") "No changes")
    (expect-disabled (label "Note text") false)
    (fill (label "Note text") "Second revision")
    (expect-text (test-id "note-status") "Unsaved changes")
    (click (role button :name "Revert changes"))
    (click (role button :name "Discard changes"))
    (expect-value (label "Note text") "First revision")
    (expect-text (test-id "note-status") "No changes")
    (fill (label "Note text") "Second revision")
    (stub-file-write "notes-write" :path "/tmp/Ideas café.txt" :bytes 15)
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-save-path" 0)
    (expect-value (label "Note text") "Second revision")
    (expect-text (test-id "note-status") "No changes")
))
