(test "Background saves own their submitted snapshot and serialize repeated saves"
  (steps
    ; The window identity is the same decision the header shows: application
    ; name, open document, and a leading mark while the draft is unsaved.
    (expect-document-title "Untitled note - Notes")
    (fill (label "Note text") "First revision")
    (expect-document-title "* Untitled note - Notes")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-text (test-id "note-status") "Choose where to save…")
    (expect-pending-task "notes-save-path" 1)
    (expect-disabled (label "Note text") true)
    (resolve-file-choice "notes-save-path" (chosen "/tmp/Ideas café.txt"))
    (expect-text (test-id "note-status") "Saving document…")
    (expect-disabled (label "Note text") false)
    (expect-disabled (role button :name "Save") true)
    (fill (label "Note text") "Second revision")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-write" 1)
    (expect-canceled-task "notes-write" 0)
    (resolve-file-write "notes-write" :path "/tmp/Ideas café.txt" :bytes 14)
    (expect-text (test-id "document-name") "Ideas café.txt")
    (expect-value (label "Note text") "Second revision")
    (expect-text (test-id "note-status") "Unsaved changes")
    (expect-document-title "* Ideas café.txt - Notes")
    (click (role button :name "Revert changes"))
    (click (role button :name "Discard changes"))
    (expect-value (label "Note text") "First revision")
    (expect-text (test-id "note-status") "No changes")
    (expect-document-title "Ideas café.txt - Notes")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-save-path" 0)
    (expect-pending-task "notes-write" 1)
    (resolve-file-write "notes-write" :path "/tmp/Ideas café.txt" :bytes 14)
    (expect-text (test-id "note-status") "No changes")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-write" 1)
    (resolve-file-write "notes-write" :path "/tmp/Ideas café.txt" :bytes 14)
    (expect-text (test-id "note-status") "No changes")
))
