(test "Background saves own their submitted snapshot and serialize repeated saves"
  (steps
    (fill (label "Note text") "First revision")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-text (test-id "note-status") "Choose where to save…")
    (expect-pending-task "notes-save-path" 1)
    (expect-disabled (label "Note text") true)
    (resolve-task "notes-save-path" "6:files16:chosen20:/tmp/Ideas café.txt")
    (expect-text (test-id "note-status") "Saving document…")
    (expect-disabled (label "Note text") false)
    (expect-disabled (role button :name "Save") true)
    (fill (label "Note text") "Second revision")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-write" 1)
    (expect-canceled-task "notes-write" 0)
    (resolve-task "notes-write" "6:files120:/tmp/Ideas café.txt2:14")
    (expect-text (test-id "document-name") "Ideas café.txt")
    (expect-value (label "Note text") "Second revision")
    (expect-text (test-id "note-status") "Unsaved changes")
    (click (role button :name "Revert changes"))
    (click (role button :name "Discard changes"))
    (expect-value (label "Note text") "First revision")
    (expect-text (test-id "note-status") "No changes")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-save-path" 0)
    (expect-pending-task "notes-write" 1)
    (resolve-task "notes-write" "6:files120:/tmp/Ideas café.txt2:14")
    (expect-text (test-id "note-status") "No changes")
    (shortcut (test-id "notes-editor") "s" 1)
    (expect-pending-task "notes-write" 1)
    (resolve-task "notes-write" "6:files120:/tmp/Ideas café.txt2:14")
    (expect-text (test-id "note-status") "No changes")
))
