(test "Exact typed shortcuts retain and dispose scoped reducers"
  (steps
    (expect-text (test-id "shortcut-count") "Count: 0")
    (fill (label "Draft") "First line\nSecond café")
    (mark-metrics)
    (shortcut (test-id "keyboard-region") "s" 1)
    (expect-text (test-id "shortcut-count") "Count: 1")
    (expect-value (label "Draft") "First line\nSecond café")
    (expect-metric-delta scopes_created 0)
    (expect-metric-delta scopes_disposed 0)
    (shortcut (test-id "keyboard-region") "s" 3)
    (expect-text (test-id "shortcut-count") "Count: 11")
    (click (role button :name "Toggle editor"))
    (expect-absent (test-id "keyboard-region"))
    (click (role button :name "Toggle editor"))
    (expect-text (test-id "shortcut-count") "Count: 0")
    (expect-value (label "Draft") "")
    (shortcut (test-id "keyboard-region") "s" 3)
    (expect-text (test-id "shortcut-count") "Count: 10")
    (shortcut (test-id "keyboard-region") "s" 1)
    (expect-text (test-id "shortcut-count") "Count: 11")))
