(test "Spreadsheet lite — grid mode toggle"
  (steps
    ; Given the state established by earlier scenarios
    (focus (label "D2"))
    (fill (label "Formula") "=B2+C2+100")
    (fill (label "Formula") "=B2+C2")
    (blur (label "D2"))
    (focus (label "D5"))
    (blur (label "D5"))
    (focus (label "F5"))
    (blur (label "F5"))
    (focus (label "B2"))
    (mark-metrics)
    (fill (label "B2") "1500")
    (mark-metrics)
    (fill (label "B2") "1200")
    (blur (label "B2"))
    (focus (label "C12"))
    (mark-metrics)
    (fill (label "C12") "9")
    (fill (label "C12") "7")
    (blur (label "C12"))
    (focus (label "C4"))
    (fill (label "C4") "oops")
    (fill (label "C4") "150")
    (blur (label "C4"))
    (focus (label "B8"))
    (fill (label "B8") "0")
    (fill (label "B8") "4")
    (blur (label "B8"))
    (focus (label "G3"))
    (fill (label "G3") "=SUM(B9:C9)")
    (blur (label "G3"))
    (focus (label "G3"))
    (fill (label "G3") "")
    (blur (label "G3"))
    (focus (label "G4"))
    (fill (label "G4") "=G4+1")
    (blur (label "G4"))
    (focus (label "G4"))
    (fill (label "G4") "=1+1")
    (blur (label "G4"))
    (focus (label "G4"))
    (fill (label "G4") "")
    (blur (label "G4"))
    (focus (label "G5"))
    (fill (label "G5") "=1+")
    (blur (label "G5"))
    (focus (label "H5"))
    (fill (label "H5") "=(1+2")
    (blur (label "H5"))
    (focus (label "H6"))
    (fill (label "H6") "=Z9+1")
    (blur (label "H6"))
    (focus (label "H5"))
    (fill (label "H5") "")
    (blur (label "H5"))
    (focus (label "H6"))
    (fill (label "H6") "")
    (blur (label "H6"))
    (focus (label "G5"))
    (fill (label "G5") "")
    (blur (label "G5"))
    (focus (label "E12"))
    (fill (label "E12") "10")
    (fill (label "E12") "")
    (blur (label "E12"))
    (focus (label "G6"))
    (fill (label "G6") "=2+3*4-6/3")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=-3+10")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=(1+2)*(3+4)")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=10/3")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "")
    (blur (label "G6"))

    ; grid mode toggle

    (click (role button :name "Show formulas"))
    (expect-text (test-id "stat-selected") "G6")
    (expect-text (test-id "stat-mode") "Formulas")
    (expect-text (test-id "status-line") "4")
    (expect-value (label "D2") "=B2+C2")
    (expect-value (label "D5") "=SUM(D2:D4)")
    (expect-value (label "A2") "Rent")
    (expect-value (label "B9") "=1/0")
    (click (role button :name "Show values"))
    (expect-value (label "D2") "2500")
    (expect-value (label "D5") "4100")
    (expect-value (label "B9") "#DIV/0!")
  )
)
