(test "Spreadsheet lite — the new dependent updates with it"
  (steps
    ; Given the state established by earlier scenarios
    (focus (label "D2"))
    (fill (label "Formula") "=B2+C2+100")
    (fill (label "Formula") "=B2+C2")
    (blur (label "D2"))
    (focus (label "D5"))
    (blur (label "D5"))
    (focus (label "F5"))
    (blur (label "F5"))
    (focus (label "B2"))
    (mark-metrics)
    (fill (label "B2") "1500")
    (mark-metrics)
    (fill (label "B2") "1200")
    (blur (label "B2"))
    (focus (label "C12"))
    (mark-metrics)
    (fill (label "C12") "9")
    (fill (label "C12") "7")
    (blur (label "C12"))
    (focus (label "C4"))
    (fill (label "C4") "oops")
    (fill (label "C4") "150")
    (blur (label "C4"))
    (focus (label "B8"))
    (fill (label "B8") "0")
    (fill (label "B8") "4")
    (blur (label "B8"))
    (focus (label "G3"))
    (fill (label "G3") "=SUM(B9:C9)")
    (blur (label "G3"))
    (focus (label "G3"))
    (fill (label "G3") "")
    (blur (label "G3"))
    (focus (label "G4"))
    (fill (label "G4") "=G4+1")
    (blur (label "G4"))
    (focus (label "G4"))
    (fill (label "G4") "=1+1")
    (blur (label "G4"))
    (focus (label "G4"))
    (fill (label "G4") "")
    (blur (label "G4"))
    (focus (label "G5"))
    (fill (label "G5") "=1+")
    (blur (label "G5"))
    (focus (label "H5"))
    (fill (label "H5") "=(1+2")
    (blur (label "H5"))
    (focus (label "H6"))
    (fill (label "H6") "=Z9+1")
    (blur (label "H6"))
    (focus (label "H5"))
    (fill (label "H5") "")
    (blur (label "H5"))
    (focus (label "H6"))
    (fill (label "H6") "")
    (blur (label "H6"))
    (focus (label "G5"))
    (fill (label "G5") "")
    (blur (label "G5"))
    (focus (label "E12"))
    (fill (label "E12") "10")
    (fill (label "E12") "")
    (blur (label "E12"))
    (focus (label "G6"))
    (fill (label "G6") "=2+3*4-6/3")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=-3+10")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=(1+2)*(3+4)")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "=10/3")
    (blur (label "G6"))
    (focus (label "G6"))
    (fill (label "G6") "")
    (blur (label "G6"))
    (click (role button :name "Show formulas"))
    (click (role button :name "Show values"))
    (mark-metrics)
    (click (role button :name "Hide empty rows"))
    (mark-metrics)
    (click (role button :name "Show all rows"))
    (mark-metrics)
    (click (role button :name "Reverse row order"))
    (click (role button :name "Top to bottom"))
    (focus (label "B3"))
    (fill (label "B3") "500")
    (fill (label "B3") "400")
    (blur (label "B3"))

    ; the new dependent updates with it

    (focus (label "G1"))
    (fill (label "G1") "=C12+1")
    (blur (label "G1"))
    (expect-value (label "G1") "8")
    (expect-text (test-id "bar-depends") "C12")
    (focus (label "C12"))
    (mark-metrics)
    (fill (label "C12") "8")
    (expect-value (label "G1") "9")
    ; Two rows away from each other, two rows re-diffed: 12 outer plus 2 x 8 inner.
    (expect-metric-delta rows_reused 28)
    (expect-metric-delta set_value 3)
    (expect-metric-delta bind_event 0)
    (fill (label "C12") "7")
    (expect-value (label "G1") "8")
    (blur (label "C12"))
    ; Sibling cells in a re-diffed row are only ever written once, at mount.
    (expect-updates (label "A12") 1)
    (expect-updates (label "D12") 1)
    (expect-updates (label "A1") 1)
  )
)
